/**
 * CR-015 multimedia ("מולטימדיה · מסכים ושלט"): the typed client of the media API. The binding contract is
 * docs/architecture/MEDIA_API.md - section numbers below (§) refer to it; the design is docs/changes/CR-015-MEDIA-SCREENS.md.
 * The backend is the authority for every permission, capability, allow-list, rate limit and validation rule; the helpers
 * here only format, order cards and mirror the rules the UI needs to hide what the server would refuse anyway.
 *
 * Without a backend (static preview, design review, unit specs) every call is answered by the in-memory MOCK adapter in
 * ./media-screens-mock.ts (eight screens from the approved mockup; mutations work), so S2 / S3 can build before S1 lands.
 * The HTTP API lives under /api/v1/multimedia (/api/v1/media is the camera video router - a different thing).
 *
 * Owned by the coordinator (contract). The implementation agents do not edit this file; a needed change is a contract
 * change (MEDIA_API.md §5).
 */
import { del, get, post, put } from './client';
import { commandId } from './request-id';
import { isApi } from './session';
import { mediaMock } from './media-screens-mock';

// ------------------------------------------------------------------------------------------------ vocabulary (§2)

export type MediaKind = 'screen' | 'receiver' | 'speaker' | 'player' | 'group';
export type ProfileId = 'samsung_smart' | 'lg_webos' | 'android_tv' | 'generic';
/** The screen's power as the vendor endpoint reports it; `art` = Samsung Frame art mode. */
export type PowerState = 'on' | 'off' | 'art' | 'standby' | 'unavailable' | 'unknown';
export type PlayState = 'playing' | 'paused' | 'idle' | null;
export type NowKind = 'app' | 'source' | 'channel' | 'art' | 'home' | 'saver' | 'none';
export type AudioTarget = 'screen' | 'linked';
export type Size = 's' | 'm' | 'l';
export type GroupBy = 'floor' | 'area' | 'none';
export type Glyph = 'antenna' | 'hdmi' | 'gamepad' | 'speaker' | 'image' | 'film' | 'playRect' | 'sparkle' | 'music' | 'ball' | 'news' | 'smile' | 'globe' | 'app';

export const KEY_IDS = [
  'up', 'down', 'left', 'right', 'ok', 'back', 'home', 'menu', 'exit', 'info', 'guide', 'source', 'tools', 'settings', 'chlist', 'prech',
  'volup', 'voldown', 'mute', 'chup', 'chdown', 'n0', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6', 'n7', 'n8', 'n9',
  'red', 'green', 'yellow', 'blue', 'play', 'pause', 'stop', 'rew', 'ff',
] as const;
export type KeyId = (typeof KEY_IDS)[number];

/** The remote's sections (§2.4); `more` ones sit behind "עוד מקשים". */
export const REMOTE_SECTIONS = ['recent', 'nav', 'dpad', 'touch', 'vol', 'ch', 'pbk', 'nums', 'colors', 'text', 'xtra'] as const;
export type RemoteSection = (typeof REMOTE_SECTIONS)[number];
export const SECTION_LABEL: Record<RemoteSection, string> = {
  recent: 'אחרונים', nav: 'חזרה · בית · תפריט', dpad: 'חצים ואישור', touch: 'משטח מגע', vol: 'עוצמה', ch: 'ערוצים', pbk: 'ניגון',
  nums: 'מספרים', colors: 'מקשי צבע', text: 'הקלדה', xtra: 'מקשים נוספים',
};
/** Decision 5b: shown by default, in this order; the rest behind "עוד מקשים". `touch` is the d-pad's alternative (off). */
export const DEFAULT_REMOTE: RemoteConfig = {
  sections: [
    { id: 'recent', on: true }, { id: 'nav', on: true }, { id: 'dpad', on: true }, { id: 'touch', on: false }, { id: 'vol', on: true },
    { id: 'ch', on: true }, { id: 'pbk', on: true }, { id: 'nums', on: true }, { id: 'colors', on: true }, { id: 'text', on: true }, { id: 'xtra', on: true },
  ],
  more: ['nums', 'colors', 'text', 'xtra'],
  scope: 'default',
};

// ------------------------------------------------------------------------------------------------ model (§2)

export interface NowShowing {
  kind: NowKind;
  /** What the card says: the app or source name as curated, a channel, "מצב אמנות"... */
  label: string;
  app_id: string | null;
  source_id: string | null;
  title: string | null;
  channel: string | null;
  position_s: number | null;
  duration_s: number | null;
  /** UTC ISO instant the position was reported at (the client interpolates while playing). */
  position_at: string | null;
  /** Relative URL of the proxied content art (never an HA URL), or null: then a neutral glyph + `hue`. */
  artwork: string | null;
  glyph: Glyph;
  /** Our own hue 0-359 for the glow (never a brand colour). */
  hue: number | null;
}

export interface MediaLive {
  power: PowerState;
  play: PlayState;
  /** false = the state is a heuristic or not reported since our last command (bulk off skips it). */
  confirmed: boolean;
  /** UTC ISO: unavailable since. */
  since: string | null;
  now: NowShowing;
  volume: { level: number | null; muted: boolean | null; target: AudioTarget; step_only: boolean };
  sound_output: string | null;
}

export interface MediaCaps {
  power_on: boolean;
  /** Why power-on is disabled (tooltip only): `no_remote_wake`, `unavailable`. */
  power_on_reason: string | null;
  power_off: boolean;
  volume_set: boolean;
  volume_step: boolean;
  mute: boolean;
  sources: boolean;
  apps: boolean;
  sound_outputs: string[];
  transport: { play: boolean; pause: boolean; stop: boolean; next: boolean; previous: boolean; seek: boolean };
  keys: KeyId[];
  text: boolean;
  touchpad: boolean;
  art_mode: boolean;
}

export interface MediaCan {
  control: boolean;
  power: boolean;
  /** A public screen: source / app / text allowed (media.public). Always true on a non-public screen. */
  public_ok: boolean;
  bulk: boolean;
}

export interface AudioLink {
  key: string;
  name: string;
  default: AudioTarget;
}

/** One physical device as the list shows it (§2.1). */
export interface MediaDevice {
  key: string;
  name: string;
  kind: MediaKind;
  profile: ProfileId;
  floor_id: string | null;
  floor_name: string | null;
  area_id: string | null;
  area_name: string | null;
  public: boolean;
  live: MediaLive;
  caps: MediaCaps;
  audio_link: AudioLink | null;
  can: MediaCan;
}

export interface SourceItem {
  /** The TV's own string - sent back as is; never the display label. */
  id: string;
  label: string;
  kind: 'source' | 'app' | 'channel';
  glyph: Glyph;
  hue: number | null;
}

export interface RecentItem {
  kind: 'source' | 'app';
  id: string;
  label: string;
  glyph: Glyph;
}

export interface RemoteConfig {
  sections: { id: RemoteSection; on: boolean }[];
  more: RemoteSection[];
  /** Where the effective config came from. */
  scope: 'default' | 'device';
}

/** GET /multimedia/devices/{key} (§3.3). */
export interface MediaDeviceDetail extends MediaDevice {
  sources: SourceItem[];
  apps: SourceItem[];
  recent: RecentItem[];
  remote: RemoteConfig;
  /** Extra keys enabled for this model in settings (added to `caps.keys` already). */
  model_keys: KeyId[];
}

export interface MediaStatus {
  enabled: boolean;
  bridge: { paired: boolean; version: string | null; media_ready: boolean };
  can: { read: boolean; control: boolean; power: boolean; public: boolean; bulk: boolean; layout: boolean; configure: boolean; personalize: boolean };
  counts: { screens: number; on: number; pending_approval: number | null };
  profiles_version: number;
}

// ------------------------------------------------------------------------------------------------ commands (§3.4)

export type TransportAction = 'play' | 'pause' | 'play_pause' | 'stop' | 'next' | 'previous';
export type MediaCommand =
  | { command: 'power_on' }
  | { command: 'power_off' }
  | { command: 'volume_set'; level: number; target?: AudioTarget }
  | { command: 'volume_step'; direction: 'up' | 'down'; target?: AudioTarget }
  | { command: 'mute'; muted: boolean; target?: AudioTarget }
  | { command: 'source'; source_id: string }
  | { command: 'app'; app_id: string }
  | { command: 'sound_output'; output: string }
  | { command: 'transport'; action: TransportAction }
  | { command: 'key'; key: KeyId }
  | { command: 'text'; text: string };
export type CommandName = MediaCommand['command'];

export type CommandStatus = 'accepted' | 'sent' | 'refused';
export interface CommandResult {
  command_id: string;
  status: CommandStatus;
  /** The ha_actions record to poll (GET /ha/actions/{id}) when the effect is confirmable; null for keys / text / steps. */
  action_id: string | null;
  confirm: 'state' | 'attribute' | 'none';
  error: string | null;
}

export const TEXT_MAX = 200;
export const KEY_RATE_PER_S = 5;
export const KEY_BURST = 8;
export const VOLUME_RATE_PER_S = 4;
export const CONFIRM_TIMEOUT_MS = 8000;
export const HOLD_REPEAT_MS = 200;
export const HOLD_MAX_MS = 10_000;

/** Commands that need media.power (the rest need media.control). */
export const POWER_COMMANDS: readonly CommandName[] = ['power_on', 'power_off', 'source', 'app', 'sound_output'];
/** Commands a public screen reserves for media.public holders. */
export const PUBLIC_COMMANDS: readonly CommandName[] = ['source', 'app', 'text'];

export const ERROR_LABEL: Record<string, string> = {
  rate_limited: 'יותר מדי לחיצות; נסו שוב',
  power_pending: 'פקודת הפעלה קודמת עדיין ממתינה',
  not_supported: 'המסך אינו תומך בפעולה זו',
  screen_off: 'המסך כבוי',
  unavailable: 'המסך אינו זמין',
  public_screen: 'מסך ציבורי: נדרשת הרשאה נפרדת',
  bridge_outdated: 'נדרש עדכון של רכיב החיבור',
  forbidden: 'אין הרשאה',
  not_confirmed: 'המסך לא אישר את הפקודה',
};

// ------------------------------------------------------------------------------------------------ layout (§2.5)

export interface CardCfg {
  on: boolean;
  size: Size;
  /** null = same as `on`. */
  phone_on: boolean | null;
  /** null = the desktop size, at most medium. */
  phone_size: Exclude<Size, 'l'> | null;
}
export interface MediaLayout {
  version: 1;
  group_by: GroupBy;
  /** HA floor ids; empty = the home screen's floor order. */
  floor_order: string[];
  /** device keys in the "מועדפים" top row, in order. */
  pinned: string[];
  /** device keys in their global order (inside a group the relative order applies). */
  order: string[];
  cards: Record<string, CardCfg>;
}
export interface MediaPersonal {
  group_by: GroupBy | null;
  order: string[] | null;
  cards: Record<string, { on?: boolean; size?: Size }>;
}
export interface LayoutResponse {
  installation: MediaLayout;
  personal: MediaPersonal | null;
  revision: number;
  can_edit: boolean;
  can_personalize: boolean;
}

export const DEFAULT_CARD: CardCfg = { on: true, size: 'm', phone_on: null, phone_size: null };
export const EMPTY_LAYOUT: MediaLayout = { version: 1, group_by: 'floor', floor_order: [], pinned: [], order: [], cards: {} };

// ------------------------------------------------------------------------------------------------ bulk (§3.9)

export type BulkScope = 'floor' | 'area';
export interface BulkPreview {
  scope: BulkScope;
  id: string;
  label: string;
  counts: { send: number; already_off: number; not_confirmed: number; unavailable: number; not_allowed: number };
  devices: { key: string; name: string; will: 'off' | 'skip'; reason: 'already_off' | 'not_confirmed' | 'unavailable' | 'not_allowed' | null }[];
}

// ------------------------------------------------------------------------------------------------ the adapter

/** One implementation per transport: HTTP (the real backend) or the in-memory mock. Same shapes, same errors. */
export interface MediaAdapter {
  status(): Promise<MediaStatus>;
  list(query?: { floor?: string; area?: string; q?: string }): Promise<{ devices: MediaDevice[] }>;
  get(key: string): Promise<MediaDeviceDetail>;
  command(key: string, body: MediaCommand & { client_request_id: string; expires_at: string }): Promise<CommandResult>;
  layout(): Promise<LayoutResponse>;
  saveLayout(layout: MediaLayout, baseRevision: number): Promise<LayoutResponse>;
  resetLayout(): Promise<LayoutResponse>;
  remoteDefault(): Promise<RemoteConfig>;
  saveRemoteDefault(cfg: RemoteConfig): Promise<RemoteConfig>;
  saveDeviceRemote(key: string, body: DeviceRemoteBody): Promise<MediaDeviceDetail>;
  bulkPreview(scope: BulkScope, id: string): Promise<BulkPreview>;
  bulkRun(scope: BulkScope, id: string, clientRequestId: string, expiresAt: string): Promise<{ bulk_id: string; status: string }>;
}

export interface DeviceRemoteBody {
  /** null = back to the installation default. */
  remote: Omit<RemoteConfig, 'scope'> | null;
  sources?: { id: string; label: string | null; hidden: boolean; kind?: SourceItem['kind']; glyph?: Glyph | null }[];
  apps?: { id: string; label: string | null; hidden: boolean; glyph?: Glyph | null }[];
}

const enc = encodeURIComponent;
const qs = (q: Record<string, string | undefined>) => {
  const p = new URLSearchParams();
  for (const [k, v] of Object.entries(q)) if (v) p.set(k, v);
  const s = p.toString();
  return s ? `?${s}` : '';
};

export const httpAdapter: MediaAdapter = {
  status: () => get('multimedia/status'),
  list: (q = {}) => get(`multimedia/devices${qs({ kind: 'screen', ...q })}`),
  get: (key) => get(`multimedia/devices/${enc(key)}`),
  command: (key, body) => post(`multimedia/devices/${enc(key)}/commands`, body),
  layout: () => get('multimedia/layout'),
  saveLayout: (layout, base_revision) => put('multimedia/layout', { layout, base_revision }),
  resetLayout: async () => {
    await del('multimedia/layout');
    return get<LayoutResponse>('multimedia/layout');
  },
  remoteDefault: () => get('multimedia/remote-default'),
  saveRemoteDefault: (cfg) => put('multimedia/remote-default', { sections: cfg.sections, more: cfg.more }),
  saveDeviceRemote: (key, body) => put(`multimedia/devices/${enc(key)}/remote`, body),
  bulkPreview: (scope, id) => get(`multimedia/actions/preview${qs({ scope, id })}`),
  bulkRun: (scope, id, client_request_id, expires_at) => post('multimedia/actions', { scope, id, kind: 'screens_off', confirmed: true, client_request_id, expires_at }),
};

/** The adapter in force: HTTP with a backend, the mock otherwise. */
export const media = (): MediaAdapter => (isApi() ? httpAdapter : mediaMock());

const expiry = (ms = 15_000) => new Date(Date.now() + ms).toISOString();

/** Sends one command with a fresh request id (one per deliberate tap; never retried). */
export function sendCommand(key: string, cmd: MediaCommand, requestId: string = commandId()): Promise<CommandResult> {
  return media().command(key, { ...cmd, client_request_id: requestId, expires_at: expiry() });
}

// ------------------------------------------------------------------------------------------------ pure helpers

export const isOn = (l: Pick<MediaLive, 'power'>): boolean => l.power === 'on';
/** Lit on the card (glow): on, or showing art. */
export const isLit = (l: Pick<MediaLive, 'power'>): boolean => l.power === 'on' || l.power === 'art';
export const isDead = (l: Pick<MediaLive, 'power'>): boolean => l.power === 'unavailable' || l.power === 'unknown';

/** The card's state line (clean operator wording, no hints). */
export function stateText(d: Pick<MediaDevice, 'live'>): string {
  const l = d.live;
  if (l.power === 'unavailable') return 'לא זמין';
  if (l.power === 'unknown') return 'מצב לא ידוע';
  if (l.power === 'art') return 'מצב אמנות';
  if (l.power === 'off' || l.power === 'standby') return 'כבוי';
  if (l.play === 'playing') return l.now.label ? `מנגן · ${l.now.label}` : 'מנגן';
  if (l.play === 'paused') return l.now.label ? `מושהה · ${l.now.label}` : 'מושהה';
  return l.now.label || 'דולק';
}

/** Whether the UI should offer a command at all (the server re-checks everything). */
export function commandOffered(d: Pick<MediaDevice, 'live' | 'caps' | 'can' | 'public'>, c: MediaCommand): boolean {
  const { live, caps, can } = d;
  if (POWER_COMMANDS.includes(c.command) ? !can.power : !can.control) return false;
  if (PUBLIC_COMMANDS.includes(c.command) && !can.public_ok) return false;
  if (isDead(live)) return false;
  if (c.command === 'power_on') return caps.power_on && live.power !== 'on';
  if (c.command === 'power_off') return caps.power_off && isLit(live);
  if (!isOn(live)) return false; // off, standby, art: only power
  switch (c.command) {
    case 'volume_set': return caps.volume_set && c.level >= 0 && c.level <= 100;
    case 'volume_step': return caps.volume_step || caps.keys.includes(c.direction === 'up' ? 'volup' : 'voldown');
    case 'mute': return caps.mute;
    case 'source': return caps.sources;
    case 'app': return caps.apps;
    case 'sound_output': return caps.sound_outputs.includes(c.output);
    case 'transport': return c.action === 'play_pause' ? caps.transport.play || caps.transport.pause : c.action === 'previous' ? caps.transport.previous : caps.transport[c.action];
    case 'key': return caps.keys.includes(c.key);
    case 'text': return caps.text && c.text.length > 0 && c.text.length <= TEXT_MAX;
  }
  return false;
}

const SECTION_KEYS: Partial<Record<RemoteSection, KeyId[]>> = {
  nav: ['back', 'home', 'menu'],
  dpad: ['up', 'down', 'left', 'right', 'ok'],
  touch: ['up', 'down', 'left', 'right', 'ok'],
  ch: ['chup', 'chdown'],
  nums: ['n0', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6', 'n7', 'n8', 'n9'],
  colors: ['red', 'green', 'yellow', 'blue'],
  xtra: ['exit', 'info', 'guide', 'source', 'tools', 'settings', 'chlist', 'prech'],
};

/** The sections the remote draws for this screen: switched on in the config AND backed by a capability; split into the
 * always-visible ones and the ones behind "עוד מקשים". Recent is shown only when there is something to repeat. */
export function remoteSections(d: Pick<MediaDeviceDetail, 'caps' | 'remote' | 'recent'>): { main: RemoteSection[]; more: RemoteSection[] } {
  const { caps } = d;
  const has = (s: RemoteSection): boolean => {
    if (s === 'recent') return d.recent.length > 0 && (caps.sources || caps.apps);
    if (s === 'vol') return caps.volume_set || caps.volume_step || caps.mute;
    if (s === 'pbk') return caps.transport.play || caps.transport.pause;
    if (s === 'text') return caps.text;
    if (s === 'touch') return caps.touchpad;
    return (SECTION_KEYS[s] ?? []).some((k) => caps.keys.includes(k));
  };
  const main: RemoteSection[] = [];
  const more: RemoteSection[] = [];
  for (const { id, on } of d.remote.sections) {
    if (!on || !has(id)) continue;
    (d.remote.more.includes(id) ? more : main).push(id);
  }
  return { main, more };
}

/** The layout the page draws: the installation's, with the personal override on top (only when the server sent one). */
export function effectiveLayout(installation: MediaLayout, personal: MediaPersonal | null): MediaLayout {
  if (!personal) return installation;
  const cards: Record<string, CardCfg> = { ...installation.cards };
  for (const [k, v] of Object.entries(personal.cards)) cards[k] = { ...(cards[k] ?? DEFAULT_CARD), ...v };
  return { ...installation, group_by: personal.group_by ?? installation.group_by, order: personal.order ?? installation.order, cards };
}

export interface CardGroup {
  id: string;
  label: string;
  items: { device: MediaDevice; size: Size }[];
}

/** Orders and groups the visible cards: "מועדפים" first, then by floor / area / one group; hidden cards dropped; devices
 * the layout does not know yet go last in their group at the default size. */
export function resolveCards(devices: MediaDevice[], layout: MediaLayout, phone: boolean): CardGroup[] {
  const cfg = (k: string): CardCfg => layout.cards[k] ?? DEFAULT_CARD;
  const shown = devices.filter((d) => {
    const c = cfg(d.key);
    return phone ? c.phone_on ?? c.on : c.on;
  });
  const rank = new Map(layout.order.map((k, i) => [k, i]));
  const byOrder = (a: MediaDevice, b: MediaDevice) => (rank.get(a.key) ?? 1e6) - (rank.get(b.key) ?? 1e6) || a.name.localeCompare(b.name, 'he');
  const size = (d: MediaDevice): Size => {
    const c = cfg(d.key);
    return phone ? c.phone_size ?? (c.size === 'l' ? 'm' : c.size) : c.size;
  };
  const item = (d: MediaDevice) => ({ device: d, size: size(d) });
  const groups: CardGroup[] = [];
  const pinned = layout.pinned.map((k) => shown.find((d) => d.key === k)).filter((d): d is MediaDevice => !!d);
  if (pinned.length) groups.push({ id: 'pinned', label: 'מועדפים', items: pinned.map(item) });
  const rest = shown.filter((d) => !layout.pinned.includes(d.key)).sort(byOrder);
  if (layout.group_by === 'none') {
    if (rest.length) groups.push({ id: 'all', label: 'כל המסכים', items: rest.map(item) });
    return groups;
  }
  const idOf = (d: MediaDevice) => (layout.group_by === 'floor' ? d.floor_id : d.area_id) ?? 'none';
  const nameOf = (d: MediaDevice) => (layout.group_by === 'floor' ? d.floor_name : d.area_name) ?? 'ללא שיוך';
  const ids = [...new Set(rest.map(idOf))];
  const floorRank = new Map(layout.floor_order.map((f, i) => [f, i]));
  if (layout.group_by === 'floor') ids.sort((a, b) => (floorRank.get(a) ?? 1e6) - (floorRank.get(b) ?? 1e6));
  for (const id of ids) {
    const members = rest.filter((d) => idOf(d) === id);
    groups.push({ id, label: nameOf(members[0]), items: members.map(item) });
  }
  return groups;
}

/** Moves one key inside an order list (the editor's up / down and drop target). */
export function moveKey(order: string[], key: string, to: number): string[] {
  const from = order.indexOf(key);
  if (from < 0) return order;
  const out = [...order];
  out.splice(from, 1);
  out.splice(Math.max(0, Math.min(out.length, to)), 0, key);
  return out;
}

/** The screens a floor / area "כבה מסכים" would send (the preview's `send` count; the server decides). */
export function bulkCandidates(devices: MediaDevice[]): MediaDevice[] {
  return devices.filter((d) => d.can.bulk && d.caps.power_off && ((isOn(d.live) && d.live.confirmed) || d.live.power === 'art'));
}

/** Client mirror of the server's key limit: a token bucket of `burst` presses refilled at `perSecond` (5/s, burst 8, the
 * same rule as services/media_commands.py). A press over it is dropped - never queued. */
export class KeyThrottle {
  private tokens: number;
  private last: number | null = null;
  constructor(private readonly perSecond = KEY_RATE_PER_S, private readonly burst = KEY_BURST) {
    this.tokens = burst;
  }
  /** true = send now; false = drop this press. */
  take(now: number = Date.now()): boolean {
    if (this.last !== null) this.tokens = Math.min(this.burst, this.tokens + (Math.max(0, now - this.last) / 1000) * this.perSecond);
    this.last = now;
    if (this.tokens < 1) return false;
    this.tokens -= 1;
    return true;
  }
}
