/**
 * CR-016 multimedia phase 2 ("נגנים ורמקולים · קבוצות"): the typed client of the players API. The binding contract is
 * docs/architecture/MEDIA_PLAYERS_API.md (section numbers "§" below; this file is the authoritative TypeScript mirror of its §2),
 * the design is docs/changes/CR-016-MEDIA-PLAYERS.md ("CR §n"). It extends the CR-015 client (./media-screens.ts), which stays
 * valid unchanged: the base types are reused and extended here, never redefined.
 *
 * The backend is the authority for every permission, capability, ceiling, confirmation and validation rule; the pure helpers
 * below only format, order, plan and mirror the rules the UI needs to hide or pre-compute what the server would refuse or
 * clamp anyway (group volume plan, join diff, party rule, night window).
 *
 * Without a backend (static preview, design review, unit specs) every call is answered by the in-memory MOCK adapter in
 * ./media-players-mock.ts (two fixture houses: with and without a music library) - selected exactly like CR-015's
 * (`isApi() ? http : mock`). This file and the mock import each other (the client needs the mock for the selector, the mock
 * needs a few pure helpers): neither reads the other's module-level values while it loads; every table in the mock is built
 * on first use.
 *
 * Owned by the coordinator (contract). The implementation agents do not edit this file; a needed change is a contract change
 * (MEDIA_PLAYERS_API.md §5).
 */
import { del, describeError, get, post, put, ApiError } from './client';
import { commandId } from './request-id';
import { isApi } from './session';
import { playersMock } from './media-players-mock';
import {
  ERROR_LABEL, isDead, isOn,
  type BulkScope, type CommandResult, type Glyph, type KeyId, type MediaCan, type MediaCaps, type MediaCommand, type MediaDevice,
  type MediaLive, type MediaStatus, type NowKind, type NowShowing, type PowerState, type RecentItem, type RemoteConfig, type SourceItem,
} from './media-screens';
import type { EndpointRole as AdminEndpointRole } from './media-admin';

// ------------------------------------------------------------------------------------------------ vocabulary (§2)

/** Base `MediaKind` plus the three NON-PHYSICAL kinds: hidden by default, never offered for a merge (CR §5.1). */
export type PlayerKind = 'screen' | 'speaker' | 'player' | 'receiver' | 'group' | 'session' | 'virtual_group' | 'service';
/** The kinds the players tab and the groups tab render (the default of `list`). */
export const PLAYER_KINDS: readonly PlayerKind[] = ['speaker', 'player', 'receiver', 'group'];
export const NON_PHYSICAL_KINDS: readonly PlayerKind[] = ['session', 'virtual_group', 'service'];
/** Kinds that can take part in a live group (never a screen, a static group, a helper, a session or a service). */
export const GROUPABLE_KINDS: readonly PlayerKind[] = ['speaker', 'player', 'receiver'];

/** Which layer answers the music controls (CR §5.2). */
export type MusicProvider = 'ma' | 'sonos' | 'heos' | 'vendor' | 'none';
/** The admin client's endpoint roles plus `music` (the music layer, CR §5.2) and `mirror` (a poorer cloud twin, never primary). */
export type PlayerEndpointRole = AdminEndpointRole | 'music' | 'mirror';
export type RepeatMode = 'off' | 'one' | 'all';
export type GroupRole = 'leader' | 'member' | 'none';
export type PlayerNowKind = NowKind | 'music' | 'station';

/** Base `NowShowing`, extended: `artist` / `album` (null for screens); stations have `duration_s` null. */
export interface PlayerNow extends Omit<NowShowing, 'kind'> {
  kind: PlayerNowKind;
  artist: string | null;
  album: string | null;
}

export interface LiveGroup {
  role: GroupRole;
  leader_key: string | null;
  /** The group's OTHER devices as the server resolved them (union of every player's `group_members` and the `active_queue` owner,
   * CR §5.3): the leader is `leader_key`, never listed here, and the list is the same on every device of the group, filtered by the
   * caller's scope. For a static group (kind `group`) these are its children. The client still tolerates a list that holds the
   * leader: see `liveGroupKeys`. */
  member_keys: string[];
  name: string | null;
  /** true for a device of kind `group`. */
  static: boolean;
  /** The one layer that answers grouping for this device (CR §5.3). */
  layer: 'ma' | 'vendor' | null;
  /** Grouped in one layer and not the other -> "קיבוץ לא תואם", join disabled. */
  conflict: boolean;
}

export interface PlayerLive extends Omit<MediaLive, 'now'> {
  now: PlayerNow;
  shuffle: boolean | null;
  repeat: RepeatMode | null;
  group: LiveGroup;
  /** From the last up-next read; null without `caps.up_next`. */
  queue: { count: number; index: number | null } | null;
  /** false when no endpoint is available (CR §5.4): controls greyed, "לא זמין"; `caps` then hold the last good mask. */
  caps_known: boolean;
}

export interface PlayerCaps extends MediaCaps {
  shuffle: boolean;
  repeat: boolean;
  group: boolean;
  volume_group: boolean;
  up_next: boolean;
  favourites: boolean;
  stations: boolean;
  playlists: boolean;
  transfer: boolean;
  /** Phase 2b (CR §17): the full queue list through the direct Music Assistant connection; absent/false = the 0.1.150 depth. */
  queue_list?: boolean;
  /** Phase 2b: the "ספרייה" tab (browse by type, through the system infrastructure). */
  browse?: boolean;
  /** Phase 2b: a search field in the library tab (the direct connection is ready). */
  search?: boolean;
}

export interface PlayerCan extends MediaCan {
  group: boolean;
  /** Phase 2b: media.queue + media.control at the anchor (move / next / delete / clear). */
  queue?: boolean;
  /** Phase 2b: media.browse at the anchor. */
  browse?: boolean;
}

export interface VolumeNight {
  /** "HH:MM", local time. */
  from: string;
  to: string;
  max: number;
}

export interface ReceiverZone {
  id: string;
  name: string;
  power: 'on' | 'off' | 'unknown';
  volume: number | null;
  source_id: string | null;
  sound_mode: string | null;
}

/** One device as the players list shows it: the base `MediaDevice`, extended (§2). */
export interface PlayerDevice extends Omit<MediaDevice, 'kind' | 'live' | 'caps' | 'can'> {
  kind: PlayerKind;
  live: PlayerLive;
  caps: PlayerCaps;
  can: PlayerCan;
  /** null = no ceiling (decision 7ב: there is no default). */
  volume_max: number | null;
  volume_night: VolumeNight | null;
  music_provider: MusicProvider;
  /** Receivers with Main / Zone2 (Main first); null otherwise. */
  zones: ReceiverZone[] | null;
  /** Kind `virtual_group` only: the helper's member keys (a shortcut, never joinable). */
  virtual_members: string[] | null;
}

/** GET /multimedia/devices/{key}: the list row plus the receiver's sources (sound modes are `caps.sound_outputs`). */
export interface PlayerDeviceDetail extends PlayerDevice {
  sources: SourceItem[];
  apps: SourceItem[];
  recent: RecentItem[];
  remote: RemoteConfig;
  model_keys: KeyId[];
}

export interface PlayerStatus extends Omit<MediaStatus, 'bridge' | 'can' | 'counts'> {
  bridge: MediaStatus['bridge'] & { players_ready: boolean };
  can: MediaStatus['can'] & { group: boolean };
  counts: MediaStatus['counts'] & { players: number; playing: number; groups: number; unplaced: number; suggestions: number | null };
  /** false = the installation has no floors: group by area (CR §7.1). */
  floors: boolean;
  library: { provider: MusicProvider; state: 'ready' | 'none' | 'unavailable' };
  /** Phase 2b: the direct Music Assistant connection's state only (the address never leaves the settings). */
  direct?: { state: MaState };
}

// ------------------------------------------------------------------------------------------------ up next, library, suggestions, groups

export interface QueueEntry {
  name: string;
  artist: string | null;
  album: string | null;
  duration_s: number | null;
}
/** GET /multimedia/devices/{key}/up-next. */
export interface UpNext {
  /** false: the read failed or is older than 10 s (server side) -> "לא זמין", never "empty". */
  confirmed: boolean;
  count: number | null;
  index: number | null;
  shuffle: boolean | null;
  repeat: RepeatMode | null;
  current: QueueEntry | null;
  /** Null without a music library (only count / index are set). */
  next: QueueEntry | null;
  read_at: string | null;
}

export type LibraryKind = 'favourites' | 'stations' | 'playlists';
export interface LibraryItem {
  /** ^[a-f0-9]{24}$, server-issued, valid 30 min: the only way to start an item. */
  item_ref: string;
  /** Only in the curation editor's read (`library(key, kind, 0, true)`, a media.layout holder): the administrator hid it. */
  hidden?: boolean;
  kind: 'track' | 'album' | 'artist' | 'playlist' | 'radio';
  name: string;
  artist: string | null;
  glyph: Glyph;
  hue: number | null;
}
export interface LibraryPage {
  kind: LibraryKind;
  items: LibraryItem[];
  curated: boolean;
  read_at: string;
  provider: MusicProvider;
}
export const ITEM_REF_RE = /^[a-f0-9]{24}$/;

// ------------------------------------------------------------------------------------------------ phase 2b: the full queue, the library tab, the connection (CR §17.7)

/** One row of `GET devices/{key}/queue`: `item` is opaque (issued to this user for this device, 10 min). */
export interface QueueRow extends QueueEntry {
  item: string;
  /** Absolute position in the queue (0 = the first row ever queued). */
  index: number;
  /** The current row and what is already buffered: never moved or deleted. */
  locked: boolean;
}
export interface QueueList {
  /** false: the read failed -> "לא זמין", never an empty queue. */
  confirmed: boolean;
  count: number | null;
  index: number | null;
  /** The last locked index (-1 when nothing plays). */
  locked_to: number | null;
  offset: number;
  items: QueueRow[];
  shuffle: boolean | null;
  repeat: RepeatMode | null;
  read_at: string | null;
}
export type QueueOp = 'move' | 'next' | 'delete' | 'clear';
export interface QueueEditBody { op: QueueOp; item?: string; to?: number; confirmed?: boolean; client_request_id: string; expires_at: string }
export interface QueueEditResult { status: 'accepted' | 'refused'; op: QueueOp; to?: number; error?: number | null }

export type BrowseType = 'track' | 'album' | 'artist' | 'playlist' | 'radio';
export const BROWSE_TYPES: readonly BrowseType[] = ['track', 'album', 'artist', 'playlist', 'radio'];
export const BROWSE_TYPE_LABEL: Record<BrowseType, string> = { track: 'שירים', album: 'אלבומים', artist: 'אמנים', playlist: 'פלייליסטים', radio: 'תחנות' };
/** GET devices/{key}/browse. */
export interface BrowsePage { type: BrowseType; q: string | null; items: LibraryItem[]; offset: number; more: boolean; read_at: string; provider: MusicProvider }
export const SEARCH_DEBOUNCE_MS = 400;
export const SEARCH_MAX = 60;
export const LIBRARY_TAB = 'library' as const;
export const LIBRARY_TAB_TEXT = 'ספרייה';

export type MaState = 'off' | 'ready' | 'unreachable' | 'unauthorized' | 'schema_too_old' | 'error';
/** GET /multimedia/admin/ma-connection (system.configure): the token is never returned. */
export interface MaConnection {
  enabled: boolean;
  url: string | null;
  token_set: boolean;
  token_set_at: string | null;
  token_expiring: boolean;
  state: MaState;
  min_schema: number;
  last_test: (MaTest & { at: string }) | null;
}
export interface MaTest { state: MaState; server_version: string | null; schema_version: number | null; players: number | null }
export interface MaConnectionBody { enabled?: boolean; url?: string | null; token?: string; clear_token?: boolean }
/** Settings wording (technical names are allowed in settings only). */
export const MA_STATE_LABEL: Record<MaState, string> = {
  off: 'כבוי', ready: 'מחובר', unreachable: 'השרת אינו נגיש', unauthorized: 'האסימון נדחה', schema_too_old: 'גרסת השרת ישנה מדי', error: 'שגיאה',
};

/** The tab "ספרייה" is offered: the device browses (caps) and the caller holds media.browse. */
export const browseOffered = (d: Pick<PlayerDevice, 'caps' | 'can'>): boolean => !!d.caps.browse && !!d.can.browse;
/** The full queue replaces the up-next block. */
export const fullQueueOffered = (d: Pick<PlayerDevice, 'caps'>): boolean => !!d.caps.queue_list;

/** Where a row dropped between rows `before` and `after` lands: never inside the locked zone, never past the end. */
export function queueDropTarget(fromIndex: number, toIndex: number, lockedTo: number, last: number): number | null {
  const to = Math.max(lockedTo + 1, Math.min(last, toIndex));
  return to === fromIndex || fromIndex <= lockedTo ? null : to;
}
/** The optimistic order after a move (the server's next read is the truth). Indexes are absolute. */
export function reorderRows(rows: readonly QueueRow[], from: number, to: number): QueueRow[] {
  const i = rows.findIndex((r) => r.index === from);
  if (i < 0) return [...rows];
  const out = rows.slice();
  const [row] = out.splice(i, 1);
  const j = Math.max(0, Math.min(out.length, i + (to - from)));
  out.splice(j, 0, row);
  const base = rows[0]?.index ?? 0;
  return out.map((r, n) => ({ ...r, index: base + n }));
}

export interface MergeSuggestion {
  id: string;
  endpoint_id: string;
  device_key: string;
  rule: '3b' | '5b' | '5';
  reason: 'same_model' | 'same_name_area_one_side' | 'same_name_area';
  endpoint_label: string;
  device_name: string;
}
export const SUGGESTION_REASON_LABEL: Record<MergeSuggestion['reason'], string> = {
  same_model: 'דגם זהה', same_name_area_one_side: 'שם זהה · חדר באחד הצדדים', same_name_area: 'שם וחדר זהים',
};

/** GET /multimedia/groups: a live group (its leader), a static group, or a helper shortcut (see media-players-mock). */
export interface MediaGroup {
  leader_key: string;
  name: string;
  static: boolean;
  floor_ids: string[];
  /** Every device of the group, the leader included (the per-room rows of the panel and the groups tab). */
  members: { key: string; name: string; area_name: string | null; volume: number | null; muted: boolean | null; available: boolean }[];
  /** The max of the powered members, like MA. */
  volume: number | null;
  can: { group: boolean; volume: boolean };
}

export interface GroupPreset {
  /** hex32. */
  id: string;
  name: string;
  leader_key: string;
  member_keys: string[];
  volumes: Record<string, number> | null;
  revision: number;
  /** Keys that are no longer approved. */
  missing: string[];
  /** An apply in flight or finished < 30 s ago. */
  running: { bulk_id: string; started_at: string } | null;
}
export interface GroupPresetBody {
  name: string;
  leader_key: string;
  member_keys: string[];
  volumes: Record<string, number> | null;
}

export interface FavouritesCuration {
  kinds_on: LibraryKind[];
  /** `name` / `artist` / `kind` come only to a holder of media.layout (the curation editor), where the server knows them - so a
   * hidden item can be listed and shown again without reading the library. */
  items: { item_ref: string; hidden: boolean; order: number; name?: string; artist?: string | null; kind?: LibraryItem['kind'] }[];
  revision: number;
}

// ------------------------------------------------------------------------------------------------ commands and group runs (§2, §3)

export type PlayerOnlyCommand =
  | { command: 'seek'; position_s: number }
  | { command: 'shuffle'; on: boolean }
  | { command: 'repeat'; mode: RepeatMode }
  | { command: 'play_item'; item_ref: string; enqueue?: 'play' | 'next' | 'add' }
  | { command: 'transfer'; from_key: string };
/** The base union plus the five new commands (no `announce`, decision 6א). On a multi-zone receiver a command carries
 * `zone` (default: the first zone); Zone2 accepts power / volume / mute / source / sound_output only. */
export type PlayerCommand = (MediaCommand | PlayerOnlyCommand) & {
  zone?: string;
  /** The answer to a 409 `confirm_required` of a command to a static group or a party (four rooms or more, or more than one floor): resend with `true` after the
   * user saw the preview (accepted by power_*, source, sound_output, transport, seek, shuffle, repeat and play_item). */
  confirmed?: boolean;
};
export type PlayerCommandName = PlayerCommand['command'];
export const ZONE2_COMMANDS: readonly PlayerCommandName[] = ['power_on', 'power_off', 'volume_set', 'volume_step', 'mute', 'source', 'sound_output'];

export type MemberOutcome = 'joined' | 'not_joined' | 'left' | 'set' | 'unknown' | 'skipped_muted' | 'skipped_off' | 'skipped_unavailable' | 'clamped' | 'not_allowed';

export interface GroupJoinBody { leader_key: string; member_keys: string[]; confirmed?: boolean; client_request_id: string; expires_at: string }
export interface GroupLeaveBody { device_keys: string[]; client_request_id: string; expires_at: string }
export interface GroupVolumeBody { level: number; mode: 'relative' | 'absolute'; client_request_id: string; expires_at: string }
export interface GroupPreview {
  devices: number;
  floors: number;
  needs_confirmation: boolean;
  needs_bulk: boolean;
  /** `key: "*"` is the ONE aggregate row for rooms the caller may not read ("חדרים נוספים", with their `count`): never a device, never named. */
  members: { key: string; name: string; area_name: string | null; will: 'join' | 'leave' | 'stay' | 'skip'; reason: string | null; count?: number }[];
}
/** The names a confirmation lists: the rooms, and the aggregate row as "חדרים נוספים (N)". */
export const previewNames = (p: Pick<GroupPreview, 'members'>): string[] => p.members.map((m) => (m.key === '*' ? `${m.name}${m.count ? ` (${m.count})` : ''}` : m.name));
export interface GroupRunResult { bulk_id: string; status: 'accepted' | 'refused'; preview?: GroupPreview }
/** GET /devices/actions/{bulk_id} for the group kinds: one record per member, naming the room (never an entity id). */
export interface GroupRecord {
  bulk_id: string;
  status: 'running' | 'done';
  members: {
    device_key: string;
    area_name: string | null;
    outcome: MemberOutcome;
    level?: number;
    /** What the operation meant to do with the room (`join`, `leave`, `stay`, `set`, `pause`, `skip`). A `skip` row (a room that
     * was not playing, was muted ...) is not a failure of a pause. */
    will?: string;
    name?: string;
    /** A saved group's volume has its own record: `set` / `clamped` / `unknown`. */
    volume_outcome?: MemberOutcome;
  }[];
}

export type PlayerStateFilter = 'playing' | 'off' | 'unavailable';
export interface PlayerListQuery {
  /** Default: `PLAYER_KINDS`. */
  kind?: readonly PlayerKind[];
  floor?: string;
  /** `'none'` = the unplaced bucket. */
  area?: string;
  q?: string;
  state?: PlayerStateFilter;
}

/** Floor / area "עצור מוזיקה" (kind `players_pause` of the bulk route; shape modelled on CR-015's screens preview). */
export interface PausePreview {
  scope: BulkScope;
  id: string;
  label: string;
  counts: { send: number; not_playing: number; unavailable: number; not_allowed: number };
  devices: { key: string; name: string; will: 'pause' | 'skip'; reason: 'not_playing' | 'unavailable' | 'not_allowed' | null }[];
}

export const PARTY_MIN_DEVICES = 4;
export const JOIN_BATCH_MS = 500;
export const GROUP_VOLUME_RATE_PER_S = 2;
export const UP_NEXT_REFRESH_MS = 30_000;
export const PRESET_RUNNING_MS = 30_000;

export const PLAYER_ERROR_LABEL: Record<string, string> = {
  ...ERROR_LABEL,
  screen_off: 'הנגן כבוי',
  unavailable: 'הנגן אינו זמין',
  confirm_required: 'נדרש אישור',
  bulk_required: 'קבוצה לכל הבית דורשת הרשאה נפרדת',
  group_pending: 'פעולת קיבוץ קודמת עדיין רצה',
  not_groupable: 'הנגן אינו יכול להצטרף לקבוצה הזו',
  unknown_item: 'הפריט אינו זמין; טענו את הרשימה מחדש',
  not_playing: 'אין מה להעביר: הנגן לא מנגן',
  no_library: 'אין ספריית מוזיקה',
  caps_unknown: 'הנגן אינו זמין',
  revision_conflict: 'נערך במקום אחר; טענו מחדש',
  use_group_volume: 'עוצמת קבוצה נשלטת ממסך הקבוצה',
  use_media_screen: 'הנגן מנוהל מהמולטימדיה',
  media_managed_control: 'הנגן מנוהל מהמולטימדיה',
  locked: 'השיר הזה כבר מתנגן',
  queue_changed: 'התור השתנה',
  ma_unavailable: 'התור אינו זמין כרגע',
  search_unavailable: 'החיפוש אינו זמין כרגע',
};
/** Refusals that depend on the server's `reason` (a short Hebrew line each): the leader's followers are not the caller's, an unmute above the ceiling. */
const REASON_LABEL: Record<string, string> = {
  'forbidden:group_member': 'אין הרשאה לשלוט בכל חדרי הקבוצה',
  'not_supported:ceiling': 'העוצמה גבוהה מהתקרה: הנמיכו ואז בטלו השתקה',
};

/** The Hebrew line of an error of the players API: the table above by code, else the server's own message. */
export function playerErrorText(err: unknown): string {
  if (err instanceof ApiError) {
    const reason = (err.body.details as { reason?: unknown } | undefined)?.reason;
    const byReason = typeof reason === 'string' ? REASON_LABEL[`${err.code}:${reason}`] : undefined;
    if (byReason) return byReason;
  }
  if (err instanceof ApiError && PLAYER_ERROR_LABEL[err.code]) return PLAYER_ERROR_LABEL[err.code];
  return describeError(err);
}
/** The code of an ApiError, or null. */
export const errorCode = (err: unknown): string | null => (err instanceof ApiError ? err.code : null);
/** 409 `confirm_required` -> the preview to show in the confirmation dialog (from `details.preview`, or the body itself); else null. */
export function confirmPreview(err: unknown): GroupPreview | null {
  if (!(err instanceof ApiError) || err.code !== 'confirm_required') return null;
  const body = err.body as unknown as { details?: { preview?: GroupPreview }; preview?: GroupPreview };
  return body.details?.preview ?? body.preview ?? null;
}

/** 409 `confirm_required` of a queue `clear` -> how many rows it would remove (`details.count`); else null. */
export function confirmCount(err: unknown): number | null {
  if (!(err instanceof ApiError) || err.code !== 'confirm_required') return null;
  const c = (err.body.details as { count?: unknown } | undefined)?.count;
  return typeof c === 'number' ? c : null;
}

export const MEMBER_OUTCOME_LABEL: Record<MemberOutcome, string> = {
  joined: 'הצטרף', not_joined: 'לא הצטרף', left: 'יצא', set: 'עודכן', unknown: 'לא ידוע', skipped_muted: 'מושתק', skipped_off: 'כבוי',
  skipped_unavailable: 'לא זמין', clamped: 'הוגבל לתקרה', not_allowed: 'אין הרשאה',
};
/** "פרגולה לא הצטרף": the room, then what happened. */
export const memberOutcomeLine = (room: string, outcome: MemberOutcome): string => `${room} ${MEMBER_OUTCOME_LABEL[outcome]}`;
/** Outcomes that are a problem the user has to hear about (the rest are fine or expected). */
export const OUTCOME_FAILED: readonly MemberOutcome[] = ['not_joined', 'unknown', 'not_allowed'];

// ------------------------------------------------------------------------------------------------ the adapter

/** One implementation per transport: HTTP (the real backend) or the in-memory mock. Same shapes, same errors. List reads
 * return arrays; the wire envelopes are `{groups}`, `{presets}` and `{suggestions}` (a bare array is accepted too). */
export interface PlayersAdapter {
  status(): Promise<PlayerStatus>;
  list(query?: PlayerListQuery): Promise<{ devices: PlayerDevice[] }>;
  get(key: string): Promise<PlayerDeviceDetail>;
  command(key: string, body: PlayerCommand & { client_request_id: string; expires_at: string }): Promise<CommandResult>;
  upNext(key: string): Promise<UpNext>;
  /** `all`: the curation editor's read (media.layout), hidden items included with `hidden: true`. */
  library(key: string, kind: LibraryKind, offset?: number, all?: boolean): Promise<LibraryPage>;
  groups(): Promise<MediaGroup[]>;
  /** 409 `confirm_required` (an ApiError; see `confirmPreview`) when the party rule asks and `confirmed` is not set. */
  join(body: GroupJoinBody): Promise<GroupRunResult>;
  leave(body: GroupLeaveBody): Promise<GroupRunResult>;
  groupVolume(leaderKey: string, body: GroupVolumeBody): Promise<GroupRunResult>;
  groupRecord(bulkId: string): Promise<GroupRecord>;
  presets(): Promise<GroupPreset[]>;
  createPreset(body: GroupPresetBody): Promise<GroupPreset>;
  savePreset(id: string, body: GroupPresetBody, baseRevision: number): Promise<GroupPreset>;
  deletePreset(id: string, baseRevision: number): Promise<void>;
  applyPreset(id: string, body: { confirmed?: boolean; client_request_id: string; expires_at: string }): Promise<GroupRunResult>;
  favourites(): Promise<FavouritesCuration>;
  saveFavourites(curation: Omit<FavouritesCuration, 'revision'>, baseRevision: number): Promise<FavouritesCuration>;
  pausePreview(scope: BulkScope, id: string): Promise<PausePreview>;
  pauseRun(scope: BulkScope, id: string, clientRequestId: string, expiresAt: string): Promise<{ bulk_id: string; status: string }>;
  /** Settings (`system.configure`): the merge wizard's list (3.27) and the folded non-physical entries (3.28). */
  suggestions(): Promise<MergeSuggestion[]>;
  /** `approved` (true on a helper group an administrator switched on): only an approved helper group is listed as a shortcut in the groups tab. */
  nonPhysical(): Promise<{ devices: (PlayerDevice & { approved?: boolean })[] }>;
  /** Phase 2b (CR §17.7). */
  queue(key: string, offset?: number): Promise<QueueList>;
  /** 409 `confirm_required` (+ `details.count`) for `clear` without `confirmed`. */
  queueEdit(key: string, body: QueueEditBody): Promise<QueueEditResult>;
  browse(key: string, type: BrowseType, q?: string, offset?: number): Promise<BrowsePage>;
  maConnection(): Promise<MaConnection>;
  saveMaConnection(body: MaConnectionBody): Promise<MaConnection>;
  testMaConnection(): Promise<MaTest>;
}

const enc = encodeURIComponent;
const qs = (q: Record<string, string | undefined>) => {
  const p = new URLSearchParams();
  for (const [k, v] of Object.entries(q)) if (v) p.set(k, v);
  const s = p.toString();
  return s ? `?${s}` : '';
};
/** Accepts `[...]` or `{ [key]: [...] }`. */
const rows = <T>(r: unknown, key: string): T[] => (Array.isArray(r) ? (r as T[]) : (((r as Record<string, unknown> | null)?.[key] as T[] | undefined) ?? []));

export const httpPlayers: PlayersAdapter = {
  status: () => get('multimedia/status'),
  list: (q = {}) => get(`multimedia/devices${qs({ kind: (q.kind ?? PLAYER_KINDS).join(','), floor: q.floor, area: q.area, q: q.q, state: q.state })}`),
  get: (key) => get(`multimedia/devices/${enc(key)}`),
  command: (key, body) => post(`multimedia/devices/${enc(key)}/commands`, body),
  upNext: (key) => get(`multimedia/devices/${enc(key)}/up-next`),
  library: (key, kind, offset, all) => get(`multimedia/devices/${enc(key)}/library${qs({ kind, offset: offset ? String(offset) : undefined, all: all ? '1' : undefined })}`),
  groups: async () => rows<MediaGroup>(await get<unknown>('multimedia/groups'), 'groups'),
  join: (body) => post('multimedia/groups/join', body),
  leave: (body) => post('multimedia/groups/leave', body),
  groupVolume: (leader, body) => post(`multimedia/groups/${enc(leader)}/volume`, body),
  // the server's record is `{id, status: queued | waiting | done, done, items: [{device_key, name, area_name, will, outcome, level?, volume_outcome?}]}`:
  // it is final only when `done` says so (a `waiting` record still has rooms to read back)
  groupRecord: async (id) => {
    const r = await get<{ id?: string; bulk_id?: string; status?: string; done?: boolean; items?: GroupRecord['members']; members?: GroupRecord['members'] }>(`devices/actions/${enc(id)}`);
    return { bulk_id: r.bulk_id ?? r.id ?? id, status: r.done === true || r.status === 'done' ? 'done' : 'running', members: r.items ?? r.members ?? [] };
  },
  presets: async () => rows<GroupPreset>(await get<unknown>('multimedia/groups/presets'), 'presets'),
  createPreset: (body) => post('multimedia/groups/presets', body),
  savePreset: (id, body, base_revision) => put(`multimedia/groups/presets/${enc(id)}`, { ...body, base_revision }),
  deletePreset: (id, base) => del(`multimedia/groups/presets/${enc(id)}?base_revision=${base}`),
  applyPreset: (id, body) => post(`multimedia/groups/presets/${enc(id)}/apply`, body),
  favourites: () => get('multimedia/favourites'),
  saveFavourites: (c, base_revision) => put('multimedia/favourites', { ...c, base_revision }),
  pausePreview: (scope, id) => get(`multimedia/actions/preview${qs({ scope, id, kind: 'players_pause' })}`),
  pauseRun: (scope, id, client_request_id, expires_at) => post('multimedia/actions', { scope, id, kind: 'players_pause', confirmed: true, client_request_id, expires_at }),
  suggestions: async () => rows<MergeSuggestion>(await get<unknown>('multimedia/admin/suggestions'), 'suggestions'),
  nonPhysical: () => get(`multimedia/admin/devices${qs({ kind: NON_PHYSICAL_KINDS.join(',') })}`),
  queue: (key, offset) => get(`multimedia/devices/${enc(key)}/queue${qs({ offset: offset !== undefined ? String(offset) : undefined })}`),
  queueEdit: (key, body) => post(`multimedia/devices/${enc(key)}/queue`, body),
  browse: (key, type, q, offset) => get(`multimedia/devices/${enc(key)}/browse${qs({ type, q: q?.trim() || undefined, offset: offset ? String(offset) : undefined })}`),
  maConnection: () => get('multimedia/admin/ma-connection'),
  saveMaConnection: (body) => put('multimedia/admin/ma-connection', body),
  testMaConnection: () => post('multimedia/admin/ma-connection/test', {}),
};

/** One queue edit with a fresh request id (one per deliberate gesture; never retried). */
export const sendQueueEdit = (key: string, op: QueueOp, extra: { item?: string; to?: number; confirmed?: boolean } = {}, requestId: string = commandId()): Promise<QueueEditResult> =>
  players().queueEdit(key, { op, ...extra, client_request_id: requestId, expires_at: new Date(Date.now() + 15_000).toISOString() });

/** The adapter in force: HTTP with a backend, the mock otherwise (same selector as CR-015's `media()`). */
export const players = (): PlayersAdapter => (isApi() ? httpPlayers : playersMock());

const expiry = (ms = 15_000) => new Date(Date.now() + ms).toISOString();

/** Sends one command with a fresh request id (one per deliberate tap; never retried). */
export function sendPlayerCommand(key: string, cmd: PlayerCommand, requestId: string = commandId()): Promise<CommandResult> {
  return players().command(key, { ...cmd, client_request_id: requestId, expires_at: expiry() } as PlayerCommand & { client_request_id: string; expires_at: string });
}
/** Joins `memberKeys` to the leader (one deliberate batch). `confirmed` only after the user saw the preview dialog. */
export const sendJoin = (leaderKey: string, memberKeys: string[], confirmed = false, requestId: string = commandId()): Promise<GroupRunResult> =>
  players().join({ leader_key: leaderKey, member_keys: memberKeys, ...(confirmed ? { confirmed: true } : {}), client_request_id: requestId, expires_at: expiry() });
export const sendLeave = (deviceKeys: string[], requestId: string = commandId()): Promise<GroupRunResult> =>
  players().leave({ device_keys: deviceKeys, client_request_id: requestId, expires_at: expiry() });
export const sendGroupVolume = (leaderKey: string, level: number, mode: GroupVolumeBody['mode'] = 'relative', requestId: string = commandId()): Promise<GroupRunResult> =>
  players().groupVolume(leaderKey, { level: Math.round(level), mode, client_request_id: requestId, expires_at: expiry() });
export const sendApplyPreset = (id: string, confirmed = false, requestId: string = commandId()): Promise<GroupRunResult> =>
  players().applyPreset(id, { ...(confirmed ? { confirmed: true } : {}), client_request_id: requestId, expires_at: expiry() });

// ------------------------------------------------------------------------------------------------ pure helpers: state

export const isPlayerKind = (k: PlayerKind): boolean => PLAYER_KINDS.includes(k);
export const isNonPhysical = (k: PlayerKind): boolean => NON_PHYSICAL_KINDS.includes(k);
/** The leader's transport plays it: a member plays with the leader. */
export const isMember = (d: Pick<PlayerDevice, 'live'>): boolean => d.live.group.role === 'member';
export const isLeader = (d: Pick<PlayerDevice, 'live'>): boolean => d.live.group.role === 'leader';
export const isGrouped = (d: Pick<PlayerDevice, 'live'>): boolean => d.live.group.role !== 'none';
export const isPlaying = (d: Pick<PlayerDevice, 'live'>): boolean => d.live.power === 'on' && d.live.play === 'playing';
export const isAvailable = (l: Pick<PlayerLive, 'power'>): boolean => !isDead(l);
/** The device has a power control at all. A Cast entity is never one (its "on" launches an app): a Cast-only speaker is `on` while it is
 * reachable and `off` (asleep) when it is not, with neither `power_on` nor `power_off` - the UI draws no power button for it. */
export const powerControlled = (d: Pick<PlayerDevice, 'caps' | 'zones'>): boolean => d.caps.power_on || d.caps.power_off || !!d.zones?.length;

/** The device's leader inside `devices` (itself when it is not a member, or when the leader is not in the list). */
export function resolveLeader<T extends Pick<PlayerDevice, 'key' | 'live'>>(d: T, devices: readonly T[]): T {
  const g = d.live.group;
  if (g.role !== 'member' || !g.leader_key) return d;
  return devices.find((x) => x.key === g.leader_key) ?? d;
}

/** Leader first, then the other keys, each once. Tolerates `member_keys` with or without the leader in it (HA lists the
 * leader in `group_members`; the contract does not say whether the resolved list does). Empty for role `none`. */
export function liveGroupKeys(g: Pick<LiveGroup, 'role' | 'leader_key' | 'member_keys'>, selfKey?: string): string[] {
  if (g.role === 'none') return [];
  const leader = g.role === 'leader' ? (g.leader_key ?? selfKey ?? null) : g.leader_key;
  return [...new Set([...(leader ? [leader] : []), ...g.member_keys])];
}

export interface StateTextOptions {
  /** The leader's room or name, for "מנגן עם סלון" (members only; see `leaderLabel`). */
  leaderLabel?: string | null;
  /** Append " · <title>" while something plays. The mockup keeps the title on its own line, so the default is off. */
  withTitle?: boolean;
}
/** The room or name a member card quotes: "מנגן עם סלון". */
export const leaderLabel = (leader: Pick<PlayerDevice, 'name' | 'area_name'>): string => leader.area_name || leader.name;

/** The card's state line (clean operator wording, no hints): "מנגן", "תחנה", "מושהה", "לא מנגן", "כבוי", "לא זמין", "מנגן עם סלון". */
export function playerStateText(d: Pick<PlayerDevice, 'live' | 'kind'>, opts: StateTextOptions = {}): string {
  const l = d.live;
  if (l.power === 'unavailable') return 'לא זמין';
  if (l.power === 'unknown') return 'מצב לא ידוע';
  if (l.power === 'off' || l.power === 'standby') return 'כבוי';
  if (d.kind === 'receiver') return l.now.label || 'דולק';
  const title = opts.withTitle && l.now.title ? ` · ${l.now.title}` : '';
  if (l.play === 'playing' || l.play === 'paused') {
    const paused = l.play === 'paused';
    if (l.group.role === 'member' && opts.leaderLabel) return `מנגן עם ${opts.leaderLabel}${paused ? ' · מושהה' : ''}${title}`;
    if (paused) return `מושהה${title}`;
    return `${l.now.kind === 'station' ? 'תחנה' : 'מנגן'}${title}`;
  }
  return 'לא מנגן';
}

/** The state filter of the players tab: "מנגנים" / "כבויים" (off or idle) / "לא זמינים". */
export function matchesState(d: Pick<PlayerDevice, 'live'>, f: PlayerStateFilter | null | undefined): boolean {
  if (!f) return true;
  if (f === 'unavailable') return d.live.power === 'unavailable';
  if (f === 'playing') return isPlaying(d);
  return d.live.power === 'off' || d.live.power === 'standby' || (d.live.power === 'on' && !isPlaying(d));
}

/** The group chip of a card: a leader says how many rooms, a member names its leader, a conflict says so. */
export function groupChip(d: Pick<PlayerDevice, 'live'>, leaderName?: string | null): { kind: 'leader' | 'member' | 'conflict'; text: string } | null {
  const g = d.live.group;
  if (g.conflict) return { kind: 'conflict', text: 'קיבוץ לא תואם' };
  if (g.role === 'leader') return { kind: 'leader', text: `${Math.max(2, liveGroupKeys(g).length)} חדרים` };
  if (g.role === 'member') return { kind: 'member', text: leaderName ?? '' };
  return null;
}

/** Client mirror of the playback position: the reported position plus the time since it was reported, capped at the
 * duration. Null for stations and when no position was reported (no bar). */
export function interpolatePosition(
  now: Pick<PlayerNow, 'kind' | 'position_s' | 'duration_s' | 'position_at'>, playing: boolean, at: number = Date.now(),
): number | null {
  if (now.kind === 'station' || now.position_s === null) return null;
  let pos = now.position_s;
  if (playing && now.position_at) {
    const t = Date.parse(now.position_at);
    if (Number.isFinite(t)) pos += Math.max(0, at - t) / 1000;
  }
  if (now.duration_s !== null) pos = Math.min(pos, now.duration_s);
  return Math.max(0, Math.floor(pos));
}

/** The next repeat mode on the repeat button: off -> all -> one -> off. */
export const nextRepeat = (m: RepeatMode | null): RepeatMode => (m === 'off' || m === null ? 'all' : m === 'all' ? 'one' : 'off');

// ------------------------------------------------------------------------------------------------ pure helpers: up next

export const UP_NEXT_UNAVAILABLE = 'לא זמין';
/** Rows beyond the current and the next one ("עוד N"); 0 when unknown. */
export function upNextMore(u: UpNext | null): number {
  if (!u || !u.confirmed || u.count === null || u.index === null) return 0;
  return Math.max(0, u.count - (u.index + 1) - (u.next ? 1 : 0));
}
/** The line under "הבא בתור": "לא זמין" whenever the read is missing or unconfirmed (never "empty"); the next item;
 * else how many follow ("עוד 5", the no-library case where only count / index are known); else that nothing follows.
 * The age of the read is the server's call (`confirmed`): the client refreshes every `UP_NEXT_REFRESH_MS`, so a read is always
 * older than 10 s for most of that time and must not turn unavailable by itself. */
export function upNextText(u: UpNext | null): string {
  if (!u || !u.confirmed) return UP_NEXT_UNAVAILABLE;
  if (u.next) return u.next.artist ? `${u.next.name} · ${u.next.artist}` : u.next.name;
  const more = upNextMore(u);
  if (more > 0) return `עוד ${more}`;
  return 'אין המשך';
}

// ------------------------------------------------------------------------------------------------ pure helpers: volume

const hhmm = (s: string): number => {
  const m = /^(\d{1,2}):(\d{2})$/.exec(s);
  return m ? Number(m[1]) * 60 + Number(m[2]) : NaN;
};
/** Whether `now` (local time) is inside the night window; a window that crosses midnight (22:00 - 07:00) works; from == to is empty. */
export function inNightWindow(night: VolumeNight | null, now: Date = new Date()): boolean {
  if (!night) return false;
  const from = hhmm(night.from);
  const to = hhmm(night.to);
  if (!Number.isFinite(from) || !Number.isFinite(to) || from === to) return false;
  const t = now.getHours() * 60 + now.getMinutes();
  return from < to ? t >= from && t < to : t >= from || t < to;
}
/** Unmuting reveals the level the device was muted at: when a ceiling (or a night window) set LATER is below it the server refuses (422 `not_supported`, reason
 * `ceiling`). Returns the ceiling the level must be lowered to first, else null (the unmute can go as it is). */
export function unmuteCeiling(d: Pick<PlayerDevice, 'volume_max' | 'volume_night' | 'live'>, now: Date = new Date()): number | null {
  const c = effectiveCeiling(d, now);
  const level = d.live.volume.level;
  return c !== null && (level === null || level > c) ? c : null;
}

/** The ceiling in force right now: the lower of `volume_max` and the night window's max inside the window - only where an
 * administrator set them (decision 7ב: no default, so null = no ceiling and nothing is clamped). */
export function effectiveCeiling(d: Pick<PlayerDevice, 'volume_max' | 'volume_night'>, now: Date = new Date()): number | null {
  const caps = [d.volume_max, inNightWindow(d.volume_night, now) ? d.volume_night!.max : null].filter((c): c is number => c !== null);
  return caps.length ? Math.min(...caps) : null;
}
/** `level` (0-100 integer) limited to the ceiling in force. */
export function clampVolume(d: Pick<PlayerDevice, 'volume_max' | 'volume_night'>, level: number, now: Date = new Date()): number {
  const c = effectiveCeiling(d, now);
  return Math.max(0, Math.min(c === null ? 100 : c, Math.round(level)));
}

/** What the group-volume plan reads of a member (a `PlayerDevice` fits). */
export interface PlanMember {
  key: string;
  volume_max: number | null;
  volume_night: VolumeNight | null;
  can: { control: boolean };
  live: { power: PowerState; volume: { level: number | null; muted: boolean | null } };
}
export interface VolumeStep {
  key: string;
  from: number | null;
  /** The level to write; null when the member is skipped (or unknown). */
  to: number | null;
  outcome: MemberOutcome;
}
const powered = (m: PlanMember): boolean => m.live.power === 'on' || m.live.power === 'art';

/** The group's volume: the max of the powered members (like MA); null when none is powered or none reports a level. */
export function groupLevel(members: readonly PlanMember[]): number | null {
  const levels = members.filter(powered).map((m) => m.live.volume.level).filter((v): v is number => v !== null);
  return levels.length ? Math.max(...levels) : null;
}

/**
 * The per-member plan of a group volume change (CR §6.2; the server does the same and reports the same outcomes).
 * - `relative` (default): every member is scaled by the same factor from its current level (balance kept), the factor being
 *   `level / group level` so the loudest member lands on `level`; when the group level is 0 / unknown there is no balance to
 *   keep and every member goes to `level`. A member without a reported level is `unknown` (nothing to scale).
 * - `absolute`: one level on all.
 * - A member is skipped, never raised: not in the caller's scope (`not_allowed`), unavailable, off, muted.
 * - Each written level is limited to the member's ceiling in force (`volume_max`, the night window) ONLY where one is set;
 *   a member that hit it is `clamped`.
 * `level` (the result) is what the slider should show afterwards: the max of the powered members.
 */
export function groupVolumePlan(members: readonly PlanMember[], level: number, mode: 'relative' | 'absolute' = 'relative', now: Date = new Date()): { steps: VolumeStep[]; level: number | null } {
  const target = Math.max(0, Math.min(100, Math.round(level)));
  const base = groupLevel(members);
  const factor = mode === 'relative' && base !== null && base > 0 ? target / base : null;
  const steps: VolumeStep[] = members.map((m) => {
    const from = m.live.volume.level;
    const skip = (outcome: MemberOutcome): VolumeStep => ({ key: m.key, from, to: null, outcome });
    if (!m.can.control) return skip('not_allowed');
    if (m.live.power === 'unavailable' || m.live.power === 'unknown') return skip('skipped_unavailable');
    if (!powered(m)) return skip('skipped_off');
    if (m.live.volume.muted) return skip('skipped_muted');
    let want = target;
    if (factor !== null) {
      if (from === null) return skip('unknown');
      want = Math.max(0, Math.min(100, Math.round(from * factor)));
    }
    const ceiling = effectiveCeiling(m, now);
    const to = ceiling === null ? want : Math.min(want, ceiling);
    return { key: m.key, from, to, outcome: to < want ? 'clamped' : 'set' };
  });
  const after = members.filter(powered).map((m) => steps.find((s) => s.key === m.key)!.to ?? m.live.volume.level).filter((v): v is number => v !== null);
  return { steps, level: after.length ? Math.max(...after) : null };
}

// ------------------------------------------------------------------------------------------------ pure helpers: grouping

export interface JoinDiff { join: string[]; leave: string[]; stay: string[] }
/** Current members vs. the wanted ones (the leader is never in either; duplicates dropped): who joins, who leaves, who stays.
 * The same diff serves the ticked rooms of the panel and a saved group's "הפעל" (unjoin the extras, join the missing). */
export function joinDiff(current: readonly string[], desired: readonly string[], leaderKey?: string): JoinDiff {
  const clean = (l: readonly string[]) => [...new Set(l)].filter((k) => k !== leaderKey);
  const cur = clean(current);
  const want = clean(desired);
  return { join: want.filter((k) => !cur.includes(k)), leave: cur.filter((k) => !want.includes(k)), stay: cur.filter((k) => want.includes(k)) };
}

/** The ticks of the group section between two sends (`JOIN_BATCH_MS` of quiet, then one request): a second tick of the
 * same room cancels the first. `isMember` = whether the room is in the group right now. */
export class JoinDraft {
  private add = new Set<string>();
  private remove = new Set<string>();
  toggle(key: string, isMember: boolean): void {
    const set = isMember ? this.remove : this.add;
    if (!set.delete(key)) set.add(key);
  }
  /** The room has an unsent change (spinner). */
  has(key: string): boolean {
    return this.add.has(key) || this.remove.has(key);
  }
  get size(): number {
    return this.add.size + this.remove.size;
  }
  get additions(): number {
    return this.add.size;
  }
  /** The members after the draft is applied to `current`. */
  desired(current: readonly string[]): string[] {
    return [...new Set([...current.filter((k) => !this.remove.has(k)), ...this.add])];
  }
  diff(current: readonly string[], leaderKey?: string): JoinDiff {
    return joinDiff(current, this.desired(current), leaderKey);
  }
  clear(): void {
    this.add.clear();
    this.remove.clear();
  }
}

/** The party rule (CR §6.2): a group of 4 or more devices, or one spanning more than one floor, needs a confirmation before
 * the request. Devices without a floor (unplaced, or an installation without floors) never count as a floor. The server decides
 * (409 `confirm_required`); this only opens the dialog early, and "building-wide needs media.bulk" is the server's alone. */
export function needsConfirmation(devices: readonly Pick<PlayerDevice, 'floor_id'>[]): boolean {
  return devices.length >= PARTY_MIN_DEVICES || new Set(devices.map((d) => d.floor_id).filter((f): f is string => f !== null)).size > 1;
}

/** Whether a device shows the "קבוצה" section at all (no live GROUPING, or not allowed, or not known: none). */
export const groupSectionOffered = (d: Pick<PlayerDevice, 'kind' | 'caps' | 'can' | 'live'>): boolean =>
  GROUPABLE_KINDS.includes(d.kind) && d.caps.group && d.can.group && d.live.caps_known && isAvailable(d.live) && !d.live.group.conflict;

/** The rooms offered as checkboxes for this leader: approved devices of the SAME grouping layer (MA with MA, vendor with
 * vendor - never a mix), available, with live GROUPING, not in another group (its own members stay ticked), not in conflict
 * (CR §5.3). `devices` are the approved ones the caller may see. */
export function groupCandidates(leader: Pick<PlayerDevice, 'key' | 'live'>, devices: readonly PlayerDevice[]): PlayerDevice[] {
  const layer = leader.live.group.layer;
  if (layer === null) return [];
  return devices.filter((d) => {
    const g = d.live.group;
    if (d.key === leader.key || !GROUPABLE_KINDS.includes(d.kind)) return false;
    if (!d.caps.group || !d.live.caps_known || !isAvailable(d.live) || g.conflict || g.layer !== layer) return false;
    return g.role === 'none' || (g.role === 'member' && g.leader_key === leader.key);
  });
}

// ------------------------------------------------------------------------------------------------ pure helpers: sections

/** "לא משויכים" (CR §7.1): devices without an area, in a last section of their own and out of floor scope. */
export function unplacedBucket<T extends Pick<PlayerDevice, 'area_id'>>(devices: readonly T[]): { placed: T[]; unplaced: T[] } {
  return { placed: devices.filter((d) => d.area_id !== null), unplaced: devices.filter((d) => d.area_id === null) };
}
export const hasFloors = (devices: readonly Pick<PlayerDevice, 'floor_id'>[]): boolean => devices.some((d) => d.floor_id !== null);

export interface PlayerSection {
  /** A floor id, `all` (floors-less: one list) or `none` (the unplaced bucket, always last). */
  id: string;
  label: string;
  devices: PlayerDevice[];
}
export const UNPLACED_LABEL = 'לא משויכים';
export const ALL_ROOMS_LABEL = 'כל החדרים';
export const NO_ROOM_LABEL = 'ללא חדר';

/** The players tab's sections: one per floor (the layout's order, else first seen) + "לא משויכים" last; with no floors one
 * list "כל החדרים" (the room chips are the filter) + "לא משויכים". Empty sections are dropped. `order` = device keys. */
export function playerSections(devices: readonly PlayerDevice[], opts: { floors: boolean; order?: readonly string[]; floorOrder?: readonly string[] }): PlayerSection[] {
  const rank = new Map((opts.order ?? []).map((k, i) => [k, i]));
  const byOrder = (a: PlayerDevice, b: PlayerDevice) => (rank.get(a.key) ?? 1e6) - (rank.get(b.key) ?? 1e6) || a.name.localeCompare(b.name, 'he');
  const { placed, unplaced } = unplacedBucket(devices);
  const out: PlayerSection[] = [];
  if (opts.floors) {
    const ids = [...new Set(placed.map((d) => d.floor_id ?? 'none'))];
    const fr = new Map((opts.floorOrder ?? []).map((f, i) => [f, i]));
    ids.sort((a, b) => (fr.get(a) ?? 1e6) - (fr.get(b) ?? 1e6));
    for (const id of ids) {
      const ds = placed.filter((d) => (d.floor_id ?? 'none') === id).sort(byOrder);
      out.push({ id, label: ds[0].floor_name ?? ds[0].area_name ?? UNPLACED_LABEL, devices: ds });
    }
  } else if (placed.length) {
    out.push({ id: 'all', label: ALL_ROOMS_LABEL, devices: [...placed].sort(byOrder) });
  }
  if (unplaced.length) out.push({ id: 'none', label: UNPLACED_LABEL, devices: [...unplaced].sort(byOrder) });
  return out;
}

/** The room chips (the area filter): one per area with its count, "ללא חדר" last when something is unplaced. */
export function roomChips(devices: readonly Pick<PlayerDevice, 'area_id' | 'area_name'>[]): { id: string; name: string; count: number }[] {
  const by = new Map<string, { id: string; name: string; count: number }>();
  for (const d of devices) {
    if (d.area_id === null) continue;
    const c = by.get(d.area_id) ?? { id: d.area_id, name: d.area_name ?? d.area_id, count: 0 };
    c.count += 1;
    by.set(d.area_id, c);
  }
  const chips = [...by.values()].sort((a, b) => a.name.localeCompare(b.name, 'he'));
  const none = devices.filter((d) => d.area_id === null).length;
  return none ? [...chips, { id: 'none', name: NO_ROOM_LABEL, count: none }] : chips;
}

// ------------------------------------------------------------------------------------------------ pure helpers: what a device offers

/** Whether the UI should offer a command at all (the server re-checks everything). Greyed, never guessed, without `caps_known`. */
export function playerCommandOffered(d: Pick<PlayerDevice, 'live' | 'caps' | 'can' | 'zones'>, c: PlayerCommand): boolean {
  const { live, caps, can } = d;
  if (!live.caps_known || isDead(live)) return false;
  const power = c.command === 'power_on' || c.command === 'power_off' || c.command === 'source' || c.command === 'sound_output';
  if (power ? !can.power : !can.control) return false;
  // a second zone: its own state, and only the commands it accepts
  const zone = c.zone && d.zones && c.zone !== d.zones[0]?.id ? d.zones.find((z) => z.id === c.zone) ?? null : null;
  if (c.zone && d.zones && c.zone !== d.zones[0]?.id) {
    if (!zone || !ZONE2_COMMANDS.includes(c.command)) return false;
    if (c.command === 'power_on') return caps.power_on && zone.power !== 'on';
    if (c.command === 'power_off') return caps.power_off && zone.power === 'on';
    if (zone.power !== 'on') return false;
  } else {
    if (c.command === 'power_on') return caps.power_on && live.power !== 'on';
    if (c.command === 'power_off') return caps.power_off && isOn(live);
    if (!isOn(live)) return false;
  }
  switch (c.command) {
    case 'volume_set': return caps.volume_set && c.level >= 0 && c.level <= 100;
    case 'volume_step': return caps.volume_step;
    case 'mute': return caps.mute;
    case 'source': return caps.sources;
    case 'sound_output': return caps.sound_outputs.includes(c.output);
    case 'transport': return c.action === 'play_pause' ? caps.transport.play || caps.transport.pause : c.action === 'previous' ? caps.transport.previous : caps.transport[c.action];
    case 'seek': return caps.transport.seek && live.now.duration_s !== null && c.position_s >= 0 && c.position_s <= live.now.duration_s;
    case 'shuffle': return caps.shuffle;
    case 'repeat': return caps.repeat;
    case 'play_item': return (caps.favourites || caps.stations || caps.playlists) && ITEM_REF_RE.test(c.item_ref);
    case 'transfer': return caps.transfer && c.from_key.length > 0;
    default: return false; // keys / text / app: not a player thing
  }
}

/** The library tabs the panel shows, in order: per the device's caps, the provider (Sonos has no playlists) and the
 * administrator's `kinds_on`. Empty = no library at all (the panel has no tabs, "הבא בתור" reads "לא זמין"). */
export function libraryTabs(d: Pick<PlayerDevice, 'caps' | 'music_provider'>, kindsOn: readonly LibraryKind[] | null = null): LibraryKind[] {
  if (d.music_provider === 'none') return [];
  const tabs: LibraryKind[] = [];
  if (d.caps.favourites) tabs.push('favourites');
  if (d.caps.stations) tabs.push('stations');
  if (d.caps.playlists && d.music_provider !== 'sonos') tabs.push('playlists');
  return kindsOn ? tabs.filter((k) => kindsOn.includes(k)) : tabs;
}
export const LIBRARY_TAB_LABEL: Record<LibraryKind, string> = { favourites: 'מועדפים', stations: 'תחנות', playlists: 'פלייליסטים' };

/** The curation applied to a page (hidden items out, the administrator's order first, the rest in the server's order). */
export function applyCuration(items: readonly LibraryItem[], c: Pick<FavouritesCuration, 'items'> | null): LibraryItem[] {
  if (!c || !c.items.length) return [...items];
  const by = new Map(c.items.map((i) => [i.item_ref, i]));
  const rank = (i: LibraryItem) => by.get(i.item_ref)?.order ?? 1e6;
  return items.filter((i) => !by.get(i.item_ref)?.hidden).map((i, n) => ({ i, n })).sort((a, b) => rank(a.i) - rank(b.i) || a.n - b.n).map((x) => x.i);
}
