/**
 * CR-018 notifications ("התראות"): the typed client of the notifications API. The binding contract is
 * docs/architecture/NOTIFICATIONS_API.md (section numbers "§" below; this file is the authoritative TypeScript mirror of its §1-§4),
 * the design is docs/changes/CR-018-NOTIFICATIONS.md ("CR §n"), the approved mockup is docs/design/mockups/notifications/index.html.
 *
 * The backend is the authority for every permission, visibility, quiet-hours, escalation and validation rule; the pure helpers below
 * only format, order, group and mirror those rules so a screen can hide or pre-compute what the server would refuse or decide anyway
 * (the inbox layout, unread counts, the snooze / acknowledge state machine, the escalation timeline, the lock-screen text at the
 * three levels, the quiet-hours pass-through matrix, the door-open flow, the source / channel matrix, scope-aware visibility).
 *
 * Without a backend (static preview, design review, unit specs) every call is answered by the in-memory MOCK adapter in
 * ./notifications-mock.ts, selected like the media clients' (`isApi() ? http : mock`) - but through a DYNAMIC import, so the two modules
 * never import each other statically: the mock imports the pure helpers from here, this file only loads the mock when it is needed.
 *
 * SAFETY RULE (CR §9): nothing in this module opens a door, disarms an alarm or runs a scene by itself. The doorbell "פתח דלת" is a deep
 * link into an in-app confirmation (`reduceDoorOpen`: press -> confirm -> sending -> result); the push actions are `open`, `ack`,
 * `snooze` and that deep link, and no action token for anything else exists.
 *
 * Owned by the coordinator (contract). The implementation agents do not edit this file; a needed change is a contract change.
 */
import { ApiError, api, apiUrl, describeError, get, post, put, type ApiErrorBody } from './client';
import { commandId } from './request-id';
import { isApi } from './session';
import type { PushSupport } from '../pwa/push';

// ------------------------------------------------------------------------------------------------ vocabulary (§1)

export type Severity = 'info' | 'alert' | 'critical';
export type Category = 'safety' | 'alerts' | 'doors' | 'device_faults' | 'automations' | 'system' | 'security';
/** v1: inbox, webpush, email. Reserved (enum values only): ha_mobile (Companion step), whatsapp (WhatsApp step), app (CR-012). */
export type Channel = 'inbox' | 'webpush' | 'email' | 'ha_mobile' | 'whatsapp' | 'app';
export type SubjectKind = 'camera' | 'entity' | 'area' | 'alarm_panel' | 'door' | 'schedule' | 'automation' | 'bulk_job' | 'system' | 'session';
export type NotifyState = 'open' | 'acknowledged' | 'resolved';
export type Weekday = 'sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat';

export interface Delivery {
  id: string;
  notification_id: string;
  user_display: string;
  channel: Channel;
  /** push host / "טלפון: <label>" / masked email - never an endpoint or an address. */
  target: string;
  status: 'queued' | 'sent' | 'retry' | 'failed' | 'gone' | 'skipped';
  /** 'quiet_hours' | 'category_off' | 'rate_limited' | 'no_reach' | 'muted' | http_<n> | an SMTP class ... */
  reason: string | null;
  attempt: number;
  at: string;
}

export interface TimelineEntry {
  at: string;
  kind: 'created' | 'folded' | 'escalated' | 'acknowledged' | 'resolved' | 'delivery_failed';
  step?: number;
  count?: number;
  by_display?: string;
  channel?: Channel;
}

/** What the inbox returns; never contains a person's name (beyond `acked_by_display`, a colleague who acknowledged) or an image URL. */
export interface Notification {
  id: string;
  /** e.g. 'camera.offline', 'rule.alert', 'sensor.leak', 'automation.failed'. */
  source: string;
  category: Category;
  severity: Severity;
  /** Hebrew, built server-side from a template; <= 80 chars. */
  title: string;
  /** <= 180 chars. */
  body: string;
  subject: { kind: SubjectKind; id: string | null; area_id: string | null };
  /** A hash route inside Arx, e.g. '#/investigate/events/<id>'. */
  link: string;
  /** Occurrences folded into this row by dedupe. */
  count: number;
  first_at: string;
  last_at: string;
  state: NotifyState;
  acked_at: string | null;
  acked_by_display: string | null;
  resolved_at: string | null;
  /** The only per-user state (owner 4ב). */
  me: { read_at: string | null; snoozed_until: string | null };
  can_ack: boolean;
  /** A snapshot is fetched separately, after sign-in (§3.6); never in a push. */
  has_snapshot: boolean;
  /** Doorbell rows only: the deep-link target of "פתח דלת"; `can_open` = the caller holds the door-open permission there. Never a token. */
  door: { id: string; name: string; can_open: boolean } | null;
  timeline: TimelineEntry[];
  my_deliveries: { channel: Channel; status: Delivery['status']; reason: string | null; at: string }[];
}

export interface QuietHours {
  enabled: boolean;
  /** "22:00", in the installation zone (`time.zone`). */
  from: string;
  to: string;
  days: Weekday[];
}
export type PassThrough = Record<Severity, { webpush: boolean; email: boolean; ha_mobile: boolean }>;
export interface EscalationSettings {
  enabled: boolean;
  /** 1-60, default 5. */
  after_min: number;
  /** 1-3, default 2. */
  steps: number;
  /** The `notify.manage` holders, or named user ids. */
  to: 'managers' | string[];
}
export type EmailSecurity = 'starttls' | 'tls' | 'none';
export interface EmailSettings {
  configured: boolean;
  host: string;
  port: number;
  security: EmailSecurity;
  user: string;
  /** The password is write-only: the API only says whether one is set. */
  password_set: boolean;
  from: string;
  recipients: string[];
  last_test: { at: string; ok: boolean; detail: string } | null;
}
export type LockscreenLevel = 'generic' | 'type_place' | 'full';
export type RetentionDays = 7 | 14 | 30 | 60 | 90;
export type CenterLayout = 'sheet' | 'page';
export type FailuresAudience = 'admins' | 'visible';

/** ONE row for the installation; `notify.manage` only (owner 4ב, 5, 6א, 7, 8א, 10ב). */
export interface NotifySettings {
  quiet: QuietHours;
  /** What is still sent during quiet hours; default: critical true, the others false. */
  pass_through: PassThrough;
  escalation: EscalationSettings;
  lockscreen: LockscreenLevel;
  /** Fixed false in v1 (a later step); shown disabled as "בקרוב". */
  image_in_push: false;
  /** A later step; shown disabled as "בקרוב". */
  companion: { critical_sound_safety: boolean };
  retention_days: RetentionDays;
  /** Owner decision 2026-10-01 (settings key `notify.center_layout`): the desktop center is a glass sheet at the content's start edge or a full screen. */
  center_layout: CenterLayout;
  /** Owner decision 2026-10-01 (settings key `notify.failures_audience`): who receives schedule / automation failure notifications: the administrators
   * (default) or everyone who may see the schedule / automation (see FAILURE_SOURCES). */
  failures_audience: FailuresAudience;
  /** Fixed. */
  deliveries_retention_days: 14;
  email: EmailSettings;
  revision: number;
  updated_at: string | null;
}

/** Per source, installation-wide (`notify.manage`). */
export interface NotifyPolicy {
  source: string;
  enabled: boolean;
  severity: Severity;
  category: Category;
  /** The condition must hold this long (door open 600, offline 120). */
  after_s: number;
  /** Occurrences inside fold into the open row. 0 = until the condition is resolved (an interpretation: see DEDUPE_UNTIL_RESOLVED). */
  dedupe_window_s: number;
  /** A quiet "resolved" update (default false; true for critical). */
  resolve_notice: boolean;
  /** `initiator` = the bulk starter / the account's owner. */
  recipients: { rule: 'scope' | 'managers' | 'initiator' | 'users'; user_ids?: string[] };
  /** inbox is fixed on; ha_mobile / whatsapp are fixed false in v1 (reserved). */
  channels: { inbox: true; webpush: boolean; email: boolean; ha_mobile: false; whatsapp: false };
  revision: number;
}

// ------------------------------------------------------------------------------------------------ requests and replies (§2)

export type InboxFilter = 'all' | 'unread' | 'critical';
export interface InboxQuery {
  state?: 'open' | 'all';
  category?: Category;
  severity_min?: Severity;
  /** The `last_at` of the oldest row of the previous page. */
  before?: string;
  limit?: number;
}
export interface InboxPage {
  notifications: Notification[];
  /** The cursor of the next page, or null when this page is the last. */
  next_before: string | null;
}
/** GET /notifications/summary: the user-menu chip and the avatar dot. `by_category` = unread rows per category. */
export interface NotifySummary {
  unread: number;
  open_critical: number;
  by_category: Partial<Record<Category, number>>;
}
export type SnoozeChoice = 60 | 'until_morning';

export interface SettingsBody {
  quiet: QuietHours;
  pass_through: PassThrough;
  escalation: EscalationSettings;
  lockscreen: LockscreenLevel;
  retention_days: RetentionDays;
  center_layout: CenterLayout;
  failures_audience: FailuresAudience;
}
export type PolicyBody = Pick<NotifyPolicy, 'enabled' | 'severity' | 'after_s' | 'dedupe_window_s' | 'resolve_notice' | 'recipients' | 'channels'>;
/** PUT /notify/email; `password` omitted = unchanged. */
export interface EmailBody {
  host: string;
  port: number;
  security: EmailSecurity;
  user: string;
  password?: string;
  from: string;
  recipients: string[];
}
/** `detail` is the SMTP class: dns, connect, tls, auth, refused, timeout. */
export interface EmailTestResult { ok: boolean; detail: string }

export interface DeliveryQuery { status?: Delivery['status']; channel?: Channel; since?: string; limit?: number }
/** GET /notify/stats: per-channel counters for the last 24 h plus the push worker's STATS (the shapes inside are open). */
export interface NotifyStats {
  since: string;
  channels: Partial<Record<Channel, { sent: number; failed: number; skipped: Record<string, number> }>>;
  worker: Record<string, number>;
}

export const SEVERITIES: readonly Severity[] = ['info', 'alert', 'critical'];
export const SEVERITY_RANK: Record<Severity, number> = { info: 0, alert: 1, critical: 2 };
export const SEVERITY_LABEL: Record<Severity, string> = { info: 'מידע', alert: 'התראה', critical: 'קריטי' };
export const WEEKDAYS: readonly Weekday[] = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'];
export const WEEKDAY_LETTER: Record<Weekday, string> = { sun: 'א', mon: 'ב', tue: 'ג', wed: 'ד', thu: 'ה', fri: 'ו', sat: 'ש' };
const WEEKDAY_NAME = ['ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי', 'שישי', 'שבת'];
export const RETENTION_CHOICES: readonly RetentionDays[] = [7, 14, 30, 60, 90];
export const ESCALATION_AFTER_MIN = { min: 1, max: 60 } as const;
export const ESCALATION_STEPS = { min: 1, max: 3 } as const;
/** `NotifyPolicy.dedupe_window_s` of a condition that folds until it is resolved ("until closed", "until back"): the contract's number
 * field has no "forever", so 0 stands for it (a window of zero seconds would fold nothing, which is never wanted). */
export const DEDUPE_UNTIL_RESOLVED = 0;
export const CENTER_LAYOUTS: readonly CenterLayout[] = ['sheet', 'page'];
export const CENTER_LAYOUT_LABEL: Record<CenterLayout, string> = { sheet: 'חלונית בצד', page: 'מסך מלא' };
export const FAILURES_AUDIENCES: readonly FailuresAudience[] = ['admins', 'visible'];
export const FAILURES_AUDIENCE_LABEL: Record<FailuresAudience, string> = { admins: 'מנהלים', visible: 'כל מי שרואה את התזמון / האוטומציה' };
/** The names of the two settings of the owner's 2026-10-01 answers, as the backend keys them. */
export const NOTIFY_SETTING_KEYS = { center_layout: 'notify.center_layout', failures_audience: 'notify.failures_audience' } as const;
/** The sources whose recipients the `failures_audience` setting decides (schedule and automation failures). */
export const FAILURE_SOURCES: readonly string[] = ['schedule.not_confirmed', 'automation.failed'];
export const LOCKSCREEN_LEVELS: readonly LockscreenLevel[] = ['generic', 'type_place', 'full'];
export const LOCKSCREEN_LABEL: Record<LockscreenLevel, string> = { generic: 'גנרי', type_place: 'סוג ומקום', full: 'מלא' };
export const CHANNEL_LABEL: Record<Channel, string> = { inbox: 'מרכז', webpush: 'דחיפה', email: 'דוא"ל', ha_mobile: 'Companion', whatsapp: 'WhatsApp', app: 'אפליקציה' };
/** Channels a v1 policy can switch; the rest are reserved. */
export const EDITABLE_CHANNELS: readonly Channel[] = ['webpush', 'email'];
export const RESERVED_CHANNELS: readonly Channel[] = ['ha_mobile', 'whatsapp', 'app'];

export const CATEGORY_LABEL: Record<Category, string> = {
  safety: 'בטיחות', device_faults: 'תקלות', system: 'מערכת', doors: 'דלתות וכניסה', automations: 'אוטומציות ותזמונים', security: 'אבטחת חשבון', alerts: 'מצלמות (חוקים)',
};
/** The order of the source filter and of the settings matrix groups. */
export const CATEGORY_ORDER: readonly Category[] = ['safety', 'device_faults', 'system', 'doors', 'automations', 'security', 'alerts'];

// ------------------------------------------------------------------------------------------------ errors (§4)

export const NOTIFY_ERROR_LABEL: Record<string, string> = {
  notification_not_found: 'ההתראה כבר לא זמינה',
  ack_not_allowed: 'אין הרשאה לאשר את ההתראה הזו',
  action_token_invalid: 'הקישור פג תוקף',
  settings_conflict: 'ההגדרות עודכנו במקום אחר; טענו מחדש',
  quiet_invalid: 'שעת ההתחלה והסיום של שעות השקט זהות',
  escalation_invalid: 'הסלמה: דקות בין 1 ל־60, שלבים בין 1 ל־3',
  channel_reserved: 'הערוץ הזה עוד לא זמין',
  channel_unavailable: 'הדוא"ל לא מוגדר',
  email_invalid: 'פרטי הדוא"ל אינם תקינים',
  rate_limited: 'יותר מדי נסיונות; נסו שוב בעוד רגע',
  forbidden: 'אין הרשאה',
  step_up_required: 'נדרש אימות נוסף',
  confirmation_required: 'נדרש אישור',
  intercom_release_in_progress: 'פתיחה קודמת של הדלת עדיין לא הוכרעה; המתינו ובדקו במצלמה',
  intercom_station_offline: 'עמדת הכניסה אינה מחוברת',
  intercom_no_lock: 'לעמדה אין מנעול משולב',
};
export const NOTIFY_ERROR_STATUS: Record<string, number> = {
  notification_not_found: 404, ack_not_allowed: 403, action_token_invalid: 401, settings_conflict: 412, quiet_invalid: 422, escalation_invalid: 422,
  channel_reserved: 422, channel_unavailable: 409, email_invalid: 422, rate_limited: 429, forbidden: 403,
};

/** An ApiError of the notifications API (the mock and the client-side validators raise these). */
export function notifyError(code: string, details: Record<string, unknown> = {}, status: number = NOTIFY_ERROR_STATUS[code] ?? 400): ApiError {
  const body: ApiErrorBody = { code, user_message: NOTIFY_ERROR_LABEL[code] ?? code, retryable: status === 429, correlation_id: '', details };
  return new ApiError(status, body);
}
/** The code of an ApiError, or null. */
export const errorCode = (err: unknown): string | null => (err instanceof ApiError ? err.code : null);
/** Seconds to wait after a 429 (`details.retry_after_s`), or null. */
export function retryAfterS(err: unknown): number | null {
  if (!(err instanceof ApiError)) return null;
  const v = (err.body.details as { retry_after_s?: unknown } | undefined)?.retry_after_s;
  return typeof v === 'number' && Number.isFinite(v) ? v : null;
}
/** The Hebrew line of an error of this API: the table by code (a 429 names the wait), else the server's own message. */
export function notifyErrorText(err: unknown): string {
  if (err instanceof ApiError && NOTIFY_ERROR_LABEL[err.code]) {
    const wait = err.code === 'rate_limited' ? retryAfterS(err) : null;
    return wait !== null ? `יותר מדי נסיונות; נסו שוב בעוד ${Math.max(1, Math.ceil(wait))} שניות` : NOTIFY_ERROR_LABEL[err.code];
  }
  return describeError(err);
}
export type ErrorContext = 'item' | 'ack' | 'action' | 'settings' | 'policy' | 'email' | 'email_test' | 'admin' | 'user';
/** A response without a code of its own (`http_<n>`) gets the contract's code for that status on that kind of route; a coded response is
 * returned untouched. */
export function mapNotifyError(err: unknown, ctx: ErrorContext): unknown {
  if (!(err instanceof ApiError) || !err.code.startsWith('http_')) return err;
  const s = err.status;
  const admin = ctx === 'settings' || ctx === 'policy' || ctx === 'email' || ctx === 'email_test' || ctx === 'admin';
  let code: string | null = null;
  if (s === 429) code = 'rate_limited';
  else if (s === 401 && ctx === 'action') code = 'action_token_invalid';
  else if (s === 403) code = admin ? 'forbidden' : ctx === 'ack' ? 'ack_not_allowed' : 'forbidden';
  else if (s === 404 && (ctx === 'item' || ctx === 'ack')) code = 'notification_not_found';
  else if (s === 412 && (ctx === 'settings' || ctx === 'policy')) code = 'settings_conflict';
  else if (s === 409 && (ctx === 'email' || ctx === 'email_test')) code = 'channel_unavailable';
  if (!code) return err;
  return new ApiError(s, { ...err.body, code, user_message: NOTIFY_ERROR_LABEL[code] ?? err.body.user_message });
}

// ------------------------------------------------------------------------------------------------ time in the installation zone

/** Every time helper takes an explicit IANA zone (the installation's `time.zone`); `undefined` = the runtime's own zone. */
interface ZoneParts { y: number; m: number; d: number; h: number; mi: number; wd: number }
const formatters = new Map<string, Intl.DateTimeFormat>();
function zoneParts(ms: number, tz?: string): ZoneParts {
  const k = tz ?? '';
  let f = formatters.get(k);
  if (!f) {
    f = new Intl.DateTimeFormat('en-US', { timeZone: tz, hourCycle: 'h23', year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric', weekday: 'short' });
    formatters.set(k, f);
  }
  const o: Record<string, string> = {};
  for (const p of f.formatToParts(new Date(ms))) o[p.type] = p.value;
  return { y: Number(o.year), m: Number(o.month), d: Number(o.day), h: Number(o.hour) % 24, mi: Number(o.minute), wd: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].indexOf(o.weekday) };
}
/** The instant at which the zone's wall clock reads y-m-d h:mi (m 1-12; d / h may overflow and are normalised). */
function zonedToUtc(y: number, m: number, d: number, h: number, mi: number, tz?: string): number {
  const guess = Date.UTC(y, m - 1, d, h, mi);
  const off = (t: number) => {
    const p = zoneParts(t, tz);
    return Date.UTC(p.y, p.m - 1, p.d, p.h, p.mi) - Math.floor(t / 60000) * 60000;
  };
  const t1 = guess - off(guess);
  const t2 = guess - off(t1);
  return t2;
}
const pad2 = (n: number) => String(n).padStart(2, '0');
/** "HH:MM" of an instant in the zone. */
export function clockText(at: number | string, tz?: string): string {
  const p = zoneParts(typeof at === 'number' ? at : Date.parse(at), tz);
  return `${pad2(p.h)}:${pad2(p.mi)}`;
}
const dayNumber = (p: ZoneParts) => Math.floor(Date.UTC(p.y, p.m - 1, p.d) / 86400000);
const dayKey = (p: ZoneParts) => `${p.y}-${pad2(p.m)}-${pad2(p.d)}`;
/** "HH:MM" -> minutes since midnight, NaN when malformed. */
export function hhmmToMin(s: string): number {
  const m = /^(\d{1,2}):(\d{2})$/.exec(s);
  if (!m || Number(m[1]) > 23 || Number(m[2]) > 59) return NaN;
  return Number(m[1]) * 60 + Number(m[2]);
}
const toMs = (at: number | string | Date): number => (typeof at === 'number' ? at : at instanceof Date ? at.getTime() : Date.parse(at));

/** "עכשיו", "לפני 12 דק׳", "14:02" (earlier today), "אתמול 21:15", "לפני 3 ימים". */
export function relativeTime(at: string | number, now: number, tz?: string): string {
  const t = toMs(at);
  const diff = now - t;
  if (diff < 60_000) return 'עכשיו';
  const days = dayNumber(zoneParts(now, tz)) - dayNumber(zoneParts(t, tz));
  if (days === 0) return diff < 3_600_000 ? `לפני ${Math.floor(diff / 60_000)} דק׳` : clockText(t, tz);
  if (days === 1) return `אתמול ${clockText(t, tz)}`;
  return `לפני ${days} ימים`;
}

// ------------------------------------------------------------------------------------------------ helpers: severity, labels

export const severityAtLeast = (s: Severity, min: Severity): boolean => SEVERITY_RANK[s] >= SEVERITY_RANK[min];
/** Descending by severity (critical first); ties keep the caller's order (stable sort). */
export const compareSeverity = (a: Severity, b: Severity): number => SEVERITY_RANK[b] - SEVERITY_RANK[a];
export function maxSeverity(list: readonly Severity[]): Severity | null {
  return list.reduce<Severity | null>((m, s) => (m === null || SEVERITY_RANK[s] > SEVERITY_RANK[m] ? s : m), null);
}
/** The place a row names: the area's name (the caller resolves areas from the catalog), or null for a row with no place (system rows). */
export const placeLabel = (n: Pick<Notification, 'subject'>, areas: Record<string, string>): string | null => (n.subject.area_id ? areas[n.subject.area_id] ?? null : null);
export const foldLabel = (n: Pick<Notification, 'count'>): string => (n.count > 1 ? `×${n.count}` : '');
export const sourceLabel = (source: string): string => sourceInfo(source)?.label ?? source;

// ------------------------------------------------------------------------------------------------ the source catalog (CR §5)

export interface SourceInfo {
  key: string;
  label: string;
  category: Category;
  severity: Severity;
  /** A pictogram name of the mockup's icon set (sw-icon style). */
  icon: string;
  /** Off by default and only reachable through rules (CR §5). */
  rulesOnly?: boolean;
}
const S = (key: string, label: string, category: Category, severity: Severity, icon: string, rulesOnly = false): SourceInfo => ({ key, label, category, severity, icon, ...(rulesOnly ? { rulesOnly } : {}) });
/** Every v1 source of CR §5, in the settings matrix order (the categories' order, then the table's). */
export const SOURCE_CATALOG: readonly SourceInfo[] = [
  S('sensor.leak', 'דליפת מים', 'safety', 'critical', 'drop'),
  S('sensor.smoke', 'עשן', 'safety', 'critical', 'flame'),
  S('sensor.gas', 'גז', 'safety', 'critical', 'gas'),
  S('sensor.co', 'פחמן חד־חמצני', 'safety', 'critical', 'gas'),
  S('alarm.triggered', 'אזעקה הופעלה', 'safety', 'critical', 'siren'),
  S('alarm.arm_failed', 'הפעלת האזעקה נכשלה', 'safety', 'alert', 'siren'),
  S('camera.offline', 'מצלמה לא זמינה', 'device_faults', 'alert', 'cameraOff'),
  S('nvr.offline', 'מקליט לא זמין', 'device_faults', 'critical', 'hdd'),
  S('nvr.storage', 'אחסון המקליט', 'device_faults', 'critical', 'hdd'),
  S('device.unavailable', 'התקן לא זמין', 'device_faults', 'info', 'wifiOff'),
  S('device.battery_low', 'סוללה חלשה', 'device_faults', 'info', 'battery'),
  S('system.health', 'תקלת מערכת', 'system', 'alert', 'warning'),
  S('backup.failed', 'גיבוי נכשל', 'system', 'alert', 'archive'),
  S('backup.stale', 'גיבוי ישן', 'system', 'info', 'archive'),
  S('update.available', 'עדכון זמין', 'system', 'info', 'download'),
  S('door.ring', 'צלצול בדלת', 'doors', 'alert', 'bellRing'),
  S('opening.left_open', 'דלת / חלון נשארו פתוחים', 'doors', 'alert', 'doorOpen'),
  S('alarm.state', 'אזעקה הופעלה / נוטרלה', 'doors', 'info', 'shield'),
  S('schedule.not_confirmed', 'תזמון לא בוצע', 'automations', 'alert', 'clock'),
  S('automation.failed', 'אוטומציה נכשלה', 'automations', 'alert', 'bolt'),
  S('automation.notify', 'הודעה מאוטומציה', 'automations', 'alert', 'bolt'),
  S('bulk.partial', 'פעולה קבוצתית הסתיימה בחלקה', 'automations', 'info', 'layers'),
  S('security.new_signin', 'כניסה חדשה לחשבון', 'security', 'alert', 'key'),
  S('security.lockout', 'נעילת כניסה', 'security', 'alert', 'key'),
  S('rule.alert', 'התראות מחוקים', 'alerts', 'alert', 'cam'),
  S('camera.motion', 'תנועה', 'alerts', 'info', 'cam', true),
  S('camera.person', 'אדם', 'alerts', 'info', 'cam', true),
  S('camera.vehicle', 'רכב', 'alerts', 'info', 'cam', true),
];
const CATALOG_BY_KEY = new Map(SOURCE_CATALOG.map((s) => [s.key, s]));
export const sourceInfo = (key: string): SourceInfo | undefined => CATALOG_BY_KEY.get(key);
/** The source filter / settings matrix groups, in order. */
export function sourcesByCategory(catalog: readonly SourceInfo[] = SOURCE_CATALOG): { category: Category; label: string; sources: SourceInfo[] }[] {
  return CATEGORY_ORDER.map((category) => ({ category, label: CATEGORY_LABEL[category], sources: catalog.filter((s) => s.category === category) })).filter((g) => g.sources.length > 0);
}

// ------------------------------------------------------------------------------------------------ defaults (CR §5, §8, §10)

export const DEFAULT_PASS_THROUGH = (): PassThrough => ({
  info: { webpush: false, email: false, ha_mobile: false },
  alert: { webpush: false, email: false, ha_mobile: false },
  critical: { webpush: true, email: true, ha_mobile: true },
});
export const DEFAULT_EMAIL = (): EmailSettings => ({ configured: false, host: '', port: 587, security: 'starttls', user: '', password_set: false, from: '', recipients: [], last_test: null });
/** The installation defaults (the mockup's quiet hours: 22:00-07:00, every day; CR §8.1 leaves "enabled" open). */
export const DEFAULT_SETTINGS = (): NotifySettings => ({
  quiet: { enabled: true, from: '22:00', to: '07:00', days: [...WEEKDAYS] },
  pass_through: DEFAULT_PASS_THROUGH(),
  escalation: { enabled: true, after_min: 5, steps: 2, to: 'managers' },
  lockscreen: 'type_place',
  image_in_push: false,
  companion: { critical_sound_safety: false },
  retention_days: 30,
  center_layout: 'sheet',
  failures_audience: 'admins',
  deliveries_retention_days: 14,
  email: DEFAULT_EMAIL(),
  revision: 1,
  updated_at: null,
});

type Rule = NotifyPolicy['recipients']['rule'];
/** [source, after_s, dedupe_window_s, recipients, push, email, enabled] - the seed of CR §5 / §6.4 (S1 seeds the same table). */
const POLICY_SEED: readonly [string, number, number, Rule, boolean, boolean, boolean][] = [
  ['rule.alert', 0, 300, 'scope', true, false, true],
  ['camera.offline', 120, DEDUPE_UNTIL_RESOLVED, 'scope', true, false, true],
  ['nvr.offline', 120, DEDUPE_UNTIL_RESOLVED, 'managers', true, true, true],
  ['nvr.storage', 0, DEDUPE_UNTIL_RESOLVED, 'managers', true, true, true],
  ['camera.motion', 0, 300, 'scope', false, false, false],
  ['camera.person', 0, 300, 'scope', false, false, false],
  ['camera.vehicle', 0, 300, 'scope', false, false, false],
  ['door.ring', 0, 60, 'scope', true, false, true],
  ['alarm.triggered', 0, DEDUPE_UNTIL_RESOLVED, 'scope', true, false, true],
  ['alarm.arm_failed', 0, 60, 'scope', true, false, true],
  ['alarm.state', 0, 60, 'scope', false, false, false],
  ['sensor.leak', 0, DEDUPE_UNTIL_RESOLVED, 'scope', true, false, true],
  ['sensor.smoke', 0, DEDUPE_UNTIL_RESOLVED, 'scope', true, false, true],
  ['sensor.gas', 0, DEDUPE_UNTIL_RESOLVED, 'scope', true, false, true],
  ['sensor.co', 0, DEDUPE_UNTIL_RESOLVED, 'scope', true, false, true],
  ['opening.left_open', 600, DEDUPE_UNTIL_RESOLVED, 'scope', true, false, true],
  ['device.unavailable', 900, DEDUPE_UNTIL_RESOLVED, 'scope', false, false, true],
  ['device.battery_low', 0, 86400, 'scope', false, false, true],
  ['schedule.not_confirmed', 0, 3600, 'managers', true, false, true],
  ['automation.failed', 0, 600, 'managers', true, false, true],
  ['automation.notify', 0, 600, 'scope', true, false, true],
  ['bulk.partial', 0, DEDUPE_UNTIL_RESOLVED, 'initiator', false, false, true],
  ['system.health', 300, DEDUPE_UNTIL_RESOLVED, 'managers', true, true, true],
  ['backup.failed', 0, 86400, 'managers', false, true, true],
  ['backup.stale', 0, 86400, 'managers', false, true, true],
  ['update.available', 0, DEDUPE_UNTIL_RESOLVED, 'managers', false, true, true],
  ['security.new_signin', 0, 3600, 'initiator', true, false, true],
  ['security.lockout', 0, 3600, 'managers', true, false, true],
];
/** One policy per source of the catalog, with the CR §5 defaults: critical sources send a resolve notice; motion / person / vehicle and
 * `alarm.state` are off (rules only); `update.available` is email + center (CR §6.4; the mockup shows it centre-only: see the report). */
export function defaultPolicies(): NotifyPolicy[] {
  return POLICY_SEED.map(([source, after_s, dedupe_window_s, rule, webpush, email, enabled]) => {
    const info = sourceInfo(source) as SourceInfo;
    return {
      source, enabled, severity: info.severity, category: info.category, after_s, dedupe_window_s, resolve_notice: info.severity === 'critical',
      recipients: { rule }, channels: { inbox: true, webpush, email, ha_mobile: false, whatsapp: false }, revision: 1,
    };
  });
}

// ------------------------------------------------------------------------------------------------ helpers: unread, snooze, acknowledge (state machine)

export const isSnoozed = (n: Pick<Notification, 'me'>, now: number): boolean => !!n.me.snoozed_until && Date.parse(n.me.snoozed_until) > now;
/** Unread = not read by this user and not snoozed; the state of the condition does not matter (a resolved row nobody read is still news). */
export const isUnread = (n: Pick<Notification, 'me'>, now: number): boolean => n.me.read_at === null && !isSnoozed(n, now);
export const unreadCount = (rows: readonly Pick<Notification, 'me'>[], now: number): number => rows.filter((n) => isUnread(n, now)).length;
/** Open and critical: the avatar dot. A snoozed row still counts (snooze hides it from the unread count only). */
export const isOpenCritical = (n: Pick<Notification, 'severity' | 'state'>): boolean => n.severity === 'critical' && n.state === 'open';
export const openCriticalCount = (rows: readonly Pick<Notification, 'severity' | 'state'>[]): number => rows.filter(isOpenCritical).length;
/** The chip / dot numbers computed from rows (the server's `/notifications/summary`; the client's fallback). */
export function summarize(rows: readonly Notification[], now: number): NotifySummary {
  const by: Partial<Record<Category, number>> = {};
  for (const n of rows) if (isUnread(n, now)) by[n.category] = (by[n.category] ?? 0) + 1;
  return { unread: unreadCount(rows, now), open_critical: openCriticalCount(rows), by_category: by };
}

/** Shared state: open -> acknowledged -> resolved. An acknowledge of an acknowledged or resolved row changes nothing; a resolve ends any
 * state; a resolved row is final (a new signal creates a new row: the partial unique index of CR §12 covers unresolved rows only). */
export type StateEvent = 'ack' | 'resolve';
export function nextState(state: NotifyState, event: StateEvent): NotifyState {
  if (state === 'resolved') return 'resolved';
  if (event === 'resolve') return 'resolved';
  return 'acknowledged';
}
const iso = (ms: number) => new Date(ms).toISOString();
/** The instant a snooze ends: `60` = one hour from now; `until_morning` = the next end of the quiet window (`quiet.to`, 07:00 by default) in the
 * installation zone, strictly after now (at 03:00 it is 07:00 the same day, at 08:00 it is 07:00 tomorrow). */
export function snoozeUntil(choice: SnoozeChoice, now: number, quiet: Pick<QuietHours, 'to'> = { to: '07:00' }, tz?: string): string {
  if (choice === 60) return iso(now + 3_600_000);
  const to = hhmmToMin(quiet.to);
  const min = Number.isFinite(to) ? to : 7 * 60;
  const p = zoneParts(now, tz);
  let at = zonedToUtc(p.y, p.m, p.d, Math.floor(min / 60), min % 60, tz);
  if (at <= now) at = zonedToUtc(p.y, p.m, p.d + 1, Math.floor(min / 60), min % 60, tz);
  return iso(at);
}
export const applyRead = (n: Notification, now: number): Notification => (n.me.read_at ? n : { ...n, me: { ...n.me, read_at: iso(now) } });
export const applySnooze = (n: Notification, until: string): Notification => (n.state === 'resolved' ? n : { ...n, me: { ...n.me, snoozed_until: until } });
/** A user's acknowledge: only an open row the caller may acknowledge; also marks it read (the mockup's behaviour). */
export function applyAck(n: Notification, byDisplay: string, now: number): Notification {
  if (!n.can_ack || n.state !== 'open') return n;
  return {
    ...n, state: nextState(n.state, 'ack'), acked_at: iso(now), acked_by_display: byDisplay, me: { ...n.me, read_at: n.me.read_at ?? iso(now) },
    timeline: [...n.timeline, { at: iso(now), kind: 'acknowledged', by_display: byDisplay }],
  };
}
export function applyResolve(n: Notification, now: number): Notification {
  if (n.state === 'resolved') return n;
  return { ...n, state: 'resolved', resolved_at: iso(now), timeline: [...n.timeline, { at: iso(now), kind: 'resolved' }] };
}
/** A repeat folded into the row: `count` and `last_at` move, the timeline gets a `folded` entry whose `count` is the new total. */
export function applyFold(n: Notification, now: number): Notification {
  const count = n.count + 1;
  return { ...n, count, last_at: iso(now), timeline: [...n.timeline, { at: iso(now), kind: 'folded', count }] };
}

export interface RowActions {
  read: boolean;
  snooze: boolean;
  snoozeMorning: boolean;
  ack: boolean;
  /** Open the device / camera (the row's deep link). */
  open: boolean;
  /** The doorbell button (a deep link into the in-app confirmation, never an action by itself). */
  door: boolean;
  snapshot: boolean;
}
/** What the row menu and the detail view offer for this row now. */
export function rowActions(n: Notification, now: number): RowActions {
  const open = n.state === 'open';
  return {
    read: n.me.read_at === null, snooze: open && !isSnoozed(n, now), snoozeMorning: open && !isSnoozed(n, now), ack: open && n.can_ack,
    open: !!n.link, door: doorButtonVisible(n), snapshot: n.has_snapshot,
  };
}

// ------------------------------------------------------------------------------------------------ helpers: inbox layout, folds, filters

/** Critical rows that are still open stay pinned at the top until acknowledged or resolved (CR §6.1). */
export const isPinned = (n: Pick<Notification, 'severity' | 'state'>): boolean => isOpenCritical(n);
const byLastDesc = (a: Notification, b: Notification) => Date.parse(b.last_at) - Date.parse(a.last_at);

export function dayLabel(at: string | number, now: number, tz?: string): string {
  const t = zoneParts(toMs(at), tz);
  const days = dayNumber(zoneParts(now, tz)) - dayNumber(t);
  if (days === 0) return 'היום';
  if (days === 1) return 'אתמול';
  return `יום ${WEEKDAY_NAME[t.wd]} ${t.d}.${t.m}`;
}
export interface DayGroup { key: string; label: string; rows: Notification[] }
export interface InboxLayout { pinned: Notification[]; days: DayGroup[] }
/** The center's list: the pinned critical rows first, then the rest grouped by the local day of `last_at`, newest first. */
export function layoutInbox(rows: readonly Notification[], now: number, tz?: string): InboxLayout {
  const sorted = [...rows].sort(byLastDesc);
  const pinned = sorted.filter(isPinned);
  const days: DayGroup[] = [];
  for (const n of sorted) {
    if (isPinned(n)) continue;
    const key = dayKey(zoneParts(Date.parse(n.last_at), tz));
    let g = days[days.length - 1];
    if (!g || g.key !== key) {
      g = { key, label: dayLabel(n.last_at, now, tz), rows: [] };
      days.push(g);
    }
    g.rows.push(n);
  }
  return { pinned, days };
}

export interface ConditionGroup {
  key: string;
  source: string;
  subject: Notification['subject'];
  rows: Notification[];
  /** The sum of the rows' `count` (occurrences of this condition). */
  total: number;
  severity: Severity;
  last_at: string;
  open: boolean;
  /** The newest row. */
  latest: Notification;
}
/** Rows of the same condition (source + subject) together: the folded-repeats view. Newest group first. */
export function groupByCondition(rows: readonly Notification[]): ConditionGroup[] {
  const map = new Map<string, Notification[]>();
  for (const n of rows) {
    const k = `${n.source}:${n.subject.kind}:${n.subject.id ?? ''}`;
    map.set(k, [...(map.get(k) ?? []), n]);
  }
  return [...map.entries()].map(([key, list]) => {
    const sorted = [...list].sort(byLastDesc);
    return {
      key, source: sorted[0].source, subject: sorted[0].subject, rows: sorted, total: sorted.reduce((s, n) => s + n.count, 0),
      severity: maxSeverity(sorted.map((n) => n.severity)) as Severity, last_at: sorted[0].last_at, open: sorted.some((n) => n.state === 'open'), latest: sorted[0],
    };
  }).sort((a, b) => Date.parse(b.last_at) - Date.parse(a.last_at));
}
export interface InboxView { filter?: InboxFilter; category?: Category | null; now: number }
/** The center's filters: all / unread / critical, plus the source filter (by category). */
export function filterInbox(rows: readonly Notification[], v: InboxView): Notification[] {
  let list = [...rows];
  if (v.category) list = list.filter((n) => n.category === v.category);
  if (v.filter === 'unread') list = list.filter((n) => isUnread(n, v.now));
  if (v.filter === 'critical') list = list.filter((n) => n.severity === 'critical');
  return list;
}
/** Rows per category (the source filter's counts). */
export function categoryCounts(rows: readonly Pick<Notification, 'category'>[]): Partial<Record<Category, number>> {
  const out: Partial<Record<Category, number>> = {};
  for (const n of rows) out[n.category] = (out[n.category] ?? 0) + 1;
  return out;
}

/** The state tag of a row: "פתוח" / "אושר · דנה" / "נפתר". */
export function stateText(n: Pick<Notification, 'state' | 'acked_by_display'>): string {
  if (n.state === 'acknowledged') return n.acked_by_display ? `אושר · ${n.acked_by_display}` : 'אושר';
  return n.state === 'resolved' ? 'נפתר' : 'פתוח';
}

// ------------------------------------------------------------------------------------------------ helpers: delivery lines and banners

export const DELIVERY_REASON_LABEL: Record<string, string> = {
  quiet_hours: 'שעות שקט', category_off: 'ערוץ כבוי למקור', rate_limited: 'הוגבל בקצב', no_reach: 'אין מכשיר רשום', muted: 'מושתק', channel_unavailable: 'הערוץ לא מוגדר',
  timeout: 'שירות הדחיפה לא ענה (timeout)', dns: 'שם השרת לא נמצא (dns)', connect: 'החיבור נדחה (connect)', tls: 'כשל בהצפנה (tls)', auth: 'פרטי ההתחברות שגויים (auth)', refused: 'השרת דחה את ההודעה (refused)',
};
/** "שעות שקט", "ההרשמה פגה (410)", "שירות הדחיפה סירב (500)". */
export function deliveryReasonText(reason: string | null): string {
  if (!reason) return '';
  if (DELIVERY_REASON_LABEL[reason]) return DELIVERY_REASON_LABEL[reason];
  const http = /^http_(\d{3})$/.exec(reason);
  if (http) return http[1] === '410' || http[1] === '404' ? `ההרשמה פגה (${http[1]})` : `שירות הדחיפה סירב (${http[1]})`;
  return reason;
}
export const DELIVERY_STATUS_LABEL: Record<Delivery['status'], string> = { queued: 'ממתין', sent: 'נשלח', retry: 'ינסה שוב', failed: 'נכשל', gone: 'ההרשמה בוטלה', skipped: 'לא נשלח' };
const channelTo = (c: Channel): string => (c === 'email' ? 'בדוא"ל' : c === 'inbox' ? 'למרכז' : 'לטלפון');
const isFailed = (s: Delivery['status']) => s === 'failed' || s === 'gone';
export interface DeliveryLine { tone: 'ok' | 'bad' | 'held' | 'pending'; text: string; at: string | null }
/** The detail view's "my delivery" line: "נשלח לטלפון · 14:02" / "לא נשלח · שעות שקט" / "המסירה לטלפון נכשלה · 14:02". Sent wins over a failure on another
 * channel; null when nothing was attempted (a source without push). The inbox itself (the center) is never a delivery line. */
export function deliveryLine(n: Pick<Notification, 'my_deliveries'>, tz?: string): DeliveryLine | null {
  const list = n.my_deliveries.filter((d) => d.channel !== 'inbox');
  if (!list.length) return null;
  const newest = (xs: typeof list) => [...xs].sort((a, b) => Date.parse(b.at) - Date.parse(a.at))[0];
  const sent = list.filter((d) => d.status === 'sent');
  if (sent.length) { const d = newest(sent); return { tone: 'ok', text: `נשלח ${channelTo(d.channel)} · ${clockText(d.at, tz)}`, at: d.at }; }
  const failed = list.filter((d) => isFailed(d.status));
  if (failed.length) { const d = newest(failed); return { tone: 'bad', text: `המסירה ${channelTo(d.channel)} נכשלה · ${clockText(d.at, tz)}`, at: d.at }; }
  const pending = list.filter((d) => d.status === 'queued' || d.status === 'retry');
  if (pending.length) { const d = newest(pending); return { tone: 'pending', text: d.status === 'retry' ? 'ינסה שוב' : 'ממתין לשליחה', at: d.at }; }
  const d = newest(list);
  return { tone: 'held', text: d.reason === 'quiet_hours' ? 'לא נשלח · שעות שקט' : `לא נשלח${d.reason ? ` · ${deliveryReasonText(d.reason)}` : ''}`, at: d.at };
}
/** The small chip on a row: a failed delivery or a held one (quiet hours); null otherwise. */
export function deliveryChip(n: Pick<Notification, 'my_deliveries'>): { tone: 'bad' | 'held'; text: string } | null {
  const line = deliveryLine(n);
  if (!line || line.tone === 'ok' || line.tone === 'pending') return null;
  return line.tone === 'bad' ? { tone: 'bad', text: 'המסירה נכשלה' } : { tone: 'held', text: 'לא נשלח' };
}
/** A row whose only attempts failed (the "delivery failed" banner counts these). */
export const hasDeliveryProblem = (n: Pick<Notification, 'my_deliveries'>): boolean => deliveryLine(n)?.tone === 'bad';

export const PUSH_BANNER: Record<Exclude<PushSupport, 'ok'>, string> = {
  insecure: 'התראות דחיפה דורשות חיבור מאובטח',
  unsupported: 'התראות דחיפה לא נתמכות במכשיר הזה',
  ios_install: 'כדי לקבל התראות הוסיפו את Arx למסך הבית',
  denied: 'ההתראות נחסמו בדפדפן',
  android_shell: 'התראות דחיפה לא נתמכות באפליקציה הזו',
};
export const PUSH_OFF_BANNER = 'ההתראות לא מופעלות במכשיר הזה';
/** The banner of a device that cannot (or does not yet) receive push; null when it can and has at least one registered device. */
export function pushBannerText(support: PushSupport, registeredHere: number): string | null {
  if (support !== 'ok') return PUSH_BANNER[support];
  return registeredHere > 0 ? null : PUSH_OFF_BANNER;
}
export interface CenterBanner { kind: 'quiet' | 'push' | 'failed'; text: string }
export interface BannerInput { settings: NotifySettings | null; now: number; tz?: string; support: PushSupport; registeredHere: number; rows: readonly Notification[] }
/** The center's header banners, in order: quiet hours active, push unavailable on this device, delivery failed. */
export function centerBanners(i: BannerInput): CenterBanner[] {
  const out: CenterBanner[] = [];
  if (i.settings) {
    const q = quietBannerText(i.settings, i.now, i.tz);
    if (q) out.push({ kind: 'quiet', text: q });
  }
  const p = pushBannerText(i.support, i.registeredHere);
  if (p) out.push({ kind: 'push', text: p });
  const failed = i.rows.filter(hasDeliveryProblem).length;
  if (failed) out.push({ kind: 'failed', text: `המסירה לטלפון נכשלה · ${failed} התראות` });
  return out;
}

// ------------------------------------------------------------------------------------------------ helpers: escalation timeline

export interface TimelineLine {
  kind: TimelineEntry['kind'] | 'pending' | 'now';
  /** The instant (ISO), or null for the "waiting for acknowledge" line. */
  at: string | null;
  /** "14:07" in the zone ('' when there is no instant). */
  clock: string;
  title: string;
  sub: string;
  pending: boolean;
}
/** The detail view's timeline ("ציר ההסלמה" for a critical row): what the server recorded (created, folded, escalated, delivery failed,
 * acknowledged, resolved), then, while a critical row is open and escalation is on, one pending line per step still to come at
 * `first_at + step * after_min`, then "ממתין לאישור" when nothing is pending. Rows below critical never escalate. */
export function escalationTimeline(n: Notification, esc: EscalationSettings | null, now: number, tz?: string): TimelineLine[] {
  const out: TimelineLine[] = [];
  const line = (kind: TimelineLine['kind'], at: string | null, title: string, sub = '', pending = false): void => {
    out.push({ kind, at, clock: at ? clockText(at, tz) : '', title, sub, pending });
  };
  const critical = n.severity === 'critical';
  for (const e of [...n.timeline].sort((a, b) => Date.parse(a.at) - Date.parse(b.at))) {
    switch (e.kind) {
      case 'created': line('created', e.at, 'נוצרה'); break;
      case 'folded': line('folded', e.at, `חזרה ${e.count ? `×${e.count}` : ''}`.trim()); break;
      case 'escalated': line('escalated', e.at, `הסלמה ${e.step ?? ''} · נשלח שוב ל־${e.count ?? 0} מנהלים`.replace('  ', ' '), esc && e.step ? `${esc.after_min * e.step} דק׳ בלי אישור · דחיפה דחופה` : ''); break;
      case 'delivery_failed': line('delivery_failed', e.at, e.channel ? `המסירה ${channelTo(e.channel)} נכשלה` : 'המסירה נכשלה', 'ההתראה במרכז'); break;
      case 'acknowledged': line('acknowledged', e.at, `אושר · ${e.by_display ?? ''}`.replace(/ · $/, ''), critical ? 'ההסלמה נעצרה' : ''); break;
      case 'resolved': line('resolved', e.at, 'נפתר'); break;
    }
  }
  let pendingShown = false;
  if (n.state === 'open' && critical && esc?.enabled) {
    const done = n.timeline.filter((e) => e.kind === 'escalated').length;
    const first = Date.parse(n.first_at);
    for (let step = done + 1; step <= esc.steps; step++) {
      const at = first + step * esc.after_min * 60_000;
      const mins = Math.ceil((at - now) / 60_000);
      line('pending', iso(at), mins > 0 ? `הסלמה ${step} בעוד ${mins} דק׳` : `הסלמה ${step} ממתינה`, step === esc.steps ? 'השלב האחרון' : '', true);
      pendingShown = true;
    }
  }
  if (n.state === 'open' && !pendingShown) line('now', null, 'ממתין לאישור');
  return out;
}
/** The title above the timeline: "ציר ההסלמה" for a critical row, else "ציר זמן". */
export const timelineTitle = (n: Pick<Notification, 'severity'>): string => (n.severity === 'critical' ? 'ציר ההסלמה' : 'ציר זמן');
/** Whether the detail view shows a timeline at all (the mockup: critical, folded or no longer open). */
export const showsTimeline = (n: Pick<Notification, 'severity' | 'count' | 'state'>): boolean => n.severity === 'critical' || n.count > 1 || n.state !== 'open';
export const escalationTarget = (esc: Pick<EscalationSettings, 'to'>): string => (esc.to === 'managers' ? 'מנהלי התראות' : `משתמשים נבחרים (${esc.to.length})`);
/** The settings section's preview: the first send, each step, the stop. */
export function escalationPreview(esc: EscalationSettings): { minute: number; text: string }[] {
  const out = [{ minute: 0, text: 'התראה קריטית נשלחת' }];
  if (!esc.enabled) return out;
  for (let i = 1; i <= esc.steps; i++) out.push({ minute: esc.after_min * i, text: `הסלמה ${i} · נשלח שוב ל${escalationTarget(esc)}` });
  out.push({ minute: -1, text: 'נעצרת באישור' });
  return out;
}

// ------------------------------------------------------------------------------------------------ helpers: lock screen (CR §11)

export interface LockscreenInput {
  /** The notification's type title ("דליפת מים"). */
  title: string;
  place: string | null;
  severity: Severity;
  at: string | number;
  /** The server template's text (names the event). */
  body: string;
  /** The device or camera name. */
  device: string | null;
  count: number;
}
export interface LockscreenText { title: string; body: string }
/** The only fields a lock-screen text can be built from: no person's name, no visitor, no image URL exists in the input. */
export const lockscreenInputOf = (n: Pick<Notification, 'title' | 'severity' | 'last_at' | 'body' | 'count'>, place: string | null, device: string | null = null): LockscreenInput => ({
  title: n.title, place, severity: n.severity, at: n.last_at, body: n.body, device, count: n.count,
});
/** The push card at the three detail levels: generic "Arx / התראה חדשה"; type_place "דליפת מים · מטבח / קריטי · 14:02"; full adds the event body and
 * the device. Never a person's name or an image, at any level. */
export function lockscreenText(level: LockscreenLevel, i: LockscreenInput, tz?: string): LockscreenText {
  if (level === 'generic') return { title: 'Arx', body: 'התראה חדשה' };
  const title = i.place ? `${i.title} · ${i.place}` : i.title;
  if (level === 'type_place') return { title, body: `${SEVERITY_LABEL[i.severity]} · ${clockText(i.at, tz)}` };
  const body = [i.body, i.device].filter((x): x is string => !!x).join(' ');
  return { title, body: i.count > 1 ? `${body} · ×${i.count}` : body };
}

export interface PushAction {
  id: 'open' | 'ack' | 'snooze' | 'open_door';
  label: string;
  /** `open`: the row's deep link; `action`: the action endpoint with a one-time token (ack / snooze only); `deeplink`: the door confirmation page. */
  kind: 'open' | 'action' | 'deeplink';
  action?: 'ack' | 'snooze';
  url?: string;
}
export const doorConfirmLink = (doorId: string, notificationId: string): string => `#/doors/${encodeURIComponent(doorId)}?confirm=${encodeURIComponent(notificationId)}`;
/** '#/doors/<id>?confirm=<notification id>' -> the two ids, or null. */
export function parseDoorConfirmLink(hash: string): { doorId: string; notificationId: string } | null {
  const m = /^#?\/doors\/([^/?#]+)\?(?:.*&)?confirm=([^&#]+)/.exec(hash);
  if (!m) return null;
  try { return { doorId: decodeURIComponent(m[1]), notificationId: decodeURIComponent(m[2]) }; } catch { return null; }
}
/** The buttons of the push at this detail level: generic offers "פתח" only; the others add "אישור" (when the recipient may), "השתק לשעה" and, on a
 * doorbell row the recipient may open, "פתח דלת" as a plain deep link. `actionsSupported` false (iOS / Safari): the tap opens Arx on the row, no buttons. */
export function pushActions(level: LockscreenLevel, n: Pick<Notification, 'id' | 'link' | 'can_ack' | 'door'>, actionsSupported = true): PushAction[] {
  const open: PushAction = { id: 'open', label: 'פתח', kind: 'open', url: n.link };
  if (level === 'generic' || !actionsSupported) return [open];
  const out: PushAction[] = [open];
  if (n.can_ack) out.push({ id: 'ack', label: 'אישור', kind: 'action', action: 'ack' });
  out.push({ id: 'snooze', label: 'השתק לשעה', kind: 'action', action: 'snooze' });
  if (n.door && n.door.can_open) out.push({ id: 'open_door', label: 'פתח דלת', kind: 'deeplink', url: doorConfirmLink(n.door.id, n.id) });
  return out;
}

// ------------------------------------------------------------------------------------------------ helpers: quiet hours and the pass-through matrix (CR §8.1)

export interface QuietWindow { active: boolean; /** The instant the active window ends (ISO), else null. */ until: string | null }
/** Whether `now` is inside the installation's quiet window. A window that crosses midnight belongs to the day it STARTS on (22:00-07:00 with
 * "fri" ticked is quiet from Friday 22:00 to Saturday 07:00); from == to is empty; an empty day list never goes quiet. */
export function quietWindow(q: QuietHours, now: number, tz?: string): QuietWindow {
  const from = hhmmToMin(q.from);
  const to = hhmmToMin(q.to);
  if (!q.enabled || !Number.isFinite(from) || !Number.isFinite(to) || from === to || !q.days.length) return { active: false, until: null };
  const p = zoneParts(now, tz);
  const t = p.h * 60 + p.mi;
  const today = WEEKDAYS[p.wd];
  const yesterday = WEEKDAYS[(p.wd + 6) % 7];
  const endAt = (dayOffset: number) => iso(zonedToUtc(p.y, p.m, p.d + dayOffset, Math.floor(to / 60), to % 60, tz));
  if (from < to) return t >= from && t < to && q.days.includes(today) ? { active: true, until: endAt(0) } : { active: false, until: null };
  if (t >= from) return q.days.includes(today) ? { active: true, until: endAt(1) } : { active: false, until: null };
  if (t < to) return q.days.includes(yesterday) ? { active: true, until: endAt(0) } : { active: false, until: null };
  return { active: false, until: null };
}
export const isQuietNow = (q: QuietHours, now: number, tz?: string): boolean => quietWindow(q, now, tz).active;
export interface PassDecision { send: boolean; reason: 'quiet_hours' | null }
/** The pass-through matrix: outside quiet hours everything is sent; inside, the center always receives, push / email / Companion follow the severity x
 * channel matrix, a reserved channel without a matrix column (whatsapp, app) is held, and an ESCALATION step bypasses quiet hours (CR §8.3). */
export function passThrough(settings: Pick<NotifySettings, 'quiet' | 'pass_through'>, severity: Severity, channel: Channel, now: number, tz?: string, opts: { escalation?: boolean } = {}): PassDecision {
  if (channel === 'inbox' || opts.escalation || !isQuietNow(settings.quiet, now, tz)) return { send: true, reason: null };
  const col = settings.pass_through[severity] as Record<string, boolean | undefined>;
  return col[channel] === true ? { send: true, reason: null } : { send: false, reason: 'quiet_hours' };
}
export interface ChannelDecision { channel: Channel; send: boolean; reason: string | null }
/** What a notification of `severity` would do on each channel of its policy now (the settings preview and the specs): `category_off` for a channel the
 * policy has off, `channel_unavailable` for email that is not configured, `quiet_hours` from the matrix. The center is always `send`. */
export function planChannels(settings: Pick<NotifySettings, 'quiet' | 'pass_through' | 'email'>, policy: Pick<NotifyPolicy, 'channels'>, severity: Severity, now: number, tz?: string, opts: { escalation?: boolean } = {}): ChannelDecision[] {
  const out: ChannelDecision[] = [{ channel: 'inbox', send: true, reason: null }];
  for (const channel of EDITABLE_CHANNELS) {
    if (!policy.channels[channel as 'webpush' | 'email']) { out.push({ channel, send: false, reason: 'category_off' }); continue; }
    if (channel === 'email' && !settings.email.configured) { out.push({ channel, send: false, reason: 'channel_unavailable' }); continue; }
    const d = passThrough(settings, severity, channel, now, tz, opts);
    out.push({ channel, send: d.send, reason: d.reason });
  }
  return out;
}
/** "שעות שקט עד 07:00 · נשלח רק קריטי" while the window is active, else null. */
export function quietBannerText(settings: Pick<NotifySettings, 'quiet' | 'pass_through'>, now: number, tz?: string): string | null {
  const w = quietWindow(settings.quiet, now, tz);
  if (!w.active || !w.until) return null;
  const passing = SEVERITIES.filter((s) => Object.values(settings.pass_through[s]).some(Boolean));
  const what = passing.length === 0 ? 'לא נשלח דבר' : passing.length === SEVERITIES.length ? 'נשלח הכול' : `נשלח רק ${passing.slice().reverse().map((s) => SEVERITY_LABEL[s]).join(', ')}`;
  return `שעות שקט עד ${clockText(w.until, tz)} · ${what}`;
}

// ------------------------------------------------------------------------------------------------ helpers: the door-open flow (CR §9)

export type DoorOpenPhase = 'idle' | 'confirm' | 'sending' | 'step_up' | 'done' | 'failed';
export interface DoorOpenState {
  phase: DoorOpenPhase;
  notification_id: string | null;
  door: { id: string; name: string } | null;
  /** The failure's code, or null. */
  error: string | null;
  /** The line to show after `done` / `failed`. */
  text: string | null;
}
export const DOOR_OPEN_IDLE: DoorOpenState = { phase: 'idle', notification_id: null, door: null, error: null, text: null };
export type DoorOpenEvent =
  | { type: 'press'; notification: Pick<Notification, 'id' | 'state' | 'door'> }
  | { type: 'confirm' }
  | { type: 'cancel' }
  | { type: 'accepted' }
  | { type: 'error'; code: string }
  | { type: 'step_up_done' }
  | { type: 'dismiss' };
/** The button is shown only on a doorbell row that is not resolved, to a caller who may open that door (`door.can_open`, computed by the server). */
export const doorButtonVisible = (n: Pick<Notification, 'door' | 'state'>): boolean => !!n.door && n.door.can_open && n.state !== 'resolved';
export const doorOpenQuestion = (name: string): string => `האם אתה בטוח שברצונך לפתוח את ${name}?`;
export const doorOpenResultText = (name: string): string => `הפקודה נשלחה אל ${name}`;
export const doorOpenBusy = (s: DoorOpenState): boolean => s.phase === 'sending';
const DOOR_ERROR_TEXT: Record<string, string> = { ...NOTIFY_ERROR_LABEL, forbidden: 'אין הרשאה לפתוח את הדלת' };
/** The flow: a press only OPENS the confirmation; nothing is sent until `confirm` follows it (and `step_up_done` after a step-up); the notification
 * never opens a door by itself. A press on a row without `door.can_open` is ignored (no button exists for that user); `cancel` is not possible while a
 * command is in flight. */
export function reduceDoorOpen(s: DoorOpenState, e: DoorOpenEvent): DoorOpenState {
  switch (e.type) {
    case 'press':
      if (s.phase === 'sending' || s.phase === 'confirm' || s.phase === 'step_up') return s;
      if (!doorButtonVisible(e.notification) || !e.notification.door) return s;
      return { phase: 'confirm', notification_id: e.notification.id, door: { id: e.notification.door.id, name: e.notification.door.name }, error: null, text: null };
    case 'confirm': return s.phase === 'confirm' ? { ...s, phase: 'sending' } : s;
    case 'step_up_done': return s.phase === 'step_up' ? { ...s, phase: 'sending', error: null } : s;
    case 'cancel': return s.phase === 'confirm' || s.phase === 'step_up' ? DOOR_OPEN_IDLE : s;
    case 'accepted': return s.phase === 'sending' && s.door ? { ...s, phase: 'done', error: null, text: doorOpenResultText(s.door.name) } : s;
    case 'error':
      if (s.phase !== 'sending') return s;
      return e.code === 'step_up_required' ? { ...s, phase: 'step_up', error: e.code, text: null } : { ...s, phase: 'failed', error: e.code, text: DOOR_ERROR_TEXT[e.code] ?? 'הפתיחה נכשלה' };
    case 'dismiss': return s.phase === 'done' || s.phase === 'failed' ? DOOR_OPEN_IDLE : s;
  }
}
/** Runs the one command of a flow that reached `sending` (through the existing release route, origin `notification:<id>`) and feeds the result back. A state
 * in any other phase sends nothing. Returns the final state. */
export async function runDoorOpen(adapter: Pick<NotifyAdapter, 'openDoor'>, state: DoorOpenState, onState: (s: DoorOpenState) => void = () => undefined): Promise<DoorOpenState> {
  if (state.phase !== 'sending' || !state.door || !state.notification_id) return state;
  let next: DoorOpenState;
  try {
    await adapter.openDoor(state.notification_id, state.door.id);
    next = reduceDoorOpen(state, { type: 'accepted' });
  } catch (err) {
    next = reduceDoorOpen(state, { type: 'error', code: errorCode(err) ?? 'failed' });
  }
  onState(next);
  return next;
}

// ------------------------------------------------------------------------------------------------ helpers: the source / channel matrix (settings §19.1, §19.7)

export const RECIPIENT_LABEL: Record<NotifyPolicy['recipients']['rule'], string> = { scope: 'כל מי שרואה', managers: 'מנהלים', initiator: 'היוזם / בעל החשבון', users: 'משתמשים נבחרים' };
export const recipientsText = (r: NotifyPolicy['recipients']): string => (r.rule === 'users' ? `${RECIPIENT_LABEL.users} (${r.user_ids?.length ?? 0})` : RECIPIENT_LABEL[r.rule]);
export interface ChannelCell {
  on: boolean;
  editable: boolean;
  /** `always`: the center; `soon`: a reserved channel ("בקרוב"); `unconfigured`: email without a mail server. */
  note: 'always' | 'soon' | 'unconfigured' | null;
}
/** One cell of the sources matrix. The center is on and fixed; Companion / WhatsApp / app are off, fixed and "בקרוב"; email is editable, and says "לא מוגדר"
 * until the mail server is configured (the policy flag is kept: it takes effect when it is). */
export function channelCell(policy: Pick<NotifyPolicy, 'channels'>, channel: Channel, settings?: Pick<NotifySettings, 'email'> | null): ChannelCell {
  if (channel === 'inbox') return { on: true, editable: false, note: 'always' };
  if (RESERVED_CHANNELS.includes(channel)) return { on: false, editable: false, note: 'soon' };
  const on = policy.channels[channel as 'webpush' | 'email'];
  return { on, editable: true, note: channel === 'email' && settings && !settings.email.configured ? 'unconfigured' : null };
}
/** The same switch the server validates: a reserved channel -> `channel_reserved` (422); the center stays on. */
export function withChannel(policy: NotifyPolicy, channel: Channel, on: boolean): NotifyPolicy {
  if (channel === 'inbox') return policy;
  if (RESERVED_CHANNELS.includes(channel)) {
    if (on) throw notifyError('channel_reserved', { channel });
    return policy;
  }
  return { ...policy, channels: { ...policy.channels, [channel]: on } };
}
/** The state of a channel in the settings "ערוצים" section. */
export function channelStatus(channel: Channel, settings: Pick<NotifySettings, 'email'>, devices: number): { state: 'always' | 'on' | 'off' | 'unconfigured' | 'soon'; text: string } {
  if (channel === 'inbox') return { state: 'always', text: 'פעיל תמיד' };
  if (channel === 'webpush') return { state: devices > 0 ? 'on' : 'off', text: devices > 0 ? `${devices} מכשירים רשומים` : 'אין מכשירים רשומים' };
  if (channel === 'email') return settings.email.configured ? { state: 'on', text: `${settings.email.recipients.length} נמענים` } : { state: 'unconfigured', text: 'לא מוגדר' };
  return { state: 'soon', text: 'בקרוב' };
}
export const policyBody = (p: NotifyPolicy): PolicyBody => ({
  enabled: p.enabled, severity: p.severity, after_s: p.after_s, dedupe_window_s: p.dedupe_window_s, resolve_notice: p.resolve_notice, recipients: p.recipients, channels: p.channels,
});
export const settingsBody = (s: NotifySettings): SettingsBody => ({
  quiet: s.quiet, pass_through: s.pass_through, escalation: s.escalation, lockscreen: s.lockscreen, retention_days: s.retention_days, center_layout: s.center_layout, failures_audience: s.failures_audience,
});
/** The recipients rule that is in force for a source: the policy's own, except for schedule / automation failures, where `failures_audience` decides
 * (`admins` -> managers, `visible` -> everyone who may see it). Visibility stays the ceiling either way. */
export function recipientsRuleFor(policy: Pick<NotifyPolicy, 'source' | 'recipients'>, settings: Pick<NotifySettings, 'failures_audience'>): NotifyPolicy['recipients']['rule'] {
  if (!FAILURE_SOURCES.includes(policy.source)) return policy.recipients.rule;
  return settings.failures_audience === 'visible' ? 'scope' : 'managers';
}
/** How the center is presented: a phone always gets the full-height bottom sheet (CR §6.1); on a larger screen the administrator's `center_layout`. */
export const centerPresentation = (settings: Pick<NotifySettings, 'center_layout'>, phone: boolean): 'bottom_sheet' | 'sheet' | 'page' => (phone ? 'bottom_sheet' : settings.center_layout);
export interface SnoozeOption { choice: SnoozeChoice; label: string }
/** The snooze choices a row offers now (owner 2026-10-01: both "שעה" and "עד הבוקר"); none for a row that is not open or already snoozed. */
export function snoozeOptions(n: Pick<Notification, 'state' | 'me'>, now: number): SnoozeOption[] {
  if (n.state !== 'open' || isSnoozed(n, now)) return [];
  return [{ choice: 60, label: 'השתק לשעה' }, { choice: 'until_morning', label: 'עד הבוקר' }];
}

// ------------------------------------------------------------------------------------------------ validation (client mirror of the server's 422s)

/** `quiet_invalid` (enabled and from == to, or a malformed time), `escalation_invalid` (after_min / steps out of range, or an empty named list), else null. */
export function validateSettings(s: Pick<SettingsBody, 'quiet' | 'escalation'>): 'quiet_invalid' | 'escalation_invalid' | null {
  const from = hhmmToMin(s.quiet.from);
  const to = hhmmToMin(s.quiet.to);
  if (!Number.isFinite(from) || !Number.isFinite(to) || (s.quiet.enabled && from === to)) return 'quiet_invalid';
  const e = s.escalation;
  const ok = Number.isInteger(e.after_min) && e.after_min >= ESCALATION_AFTER_MIN.min && e.after_min <= ESCALATION_AFTER_MIN.max
    && Number.isInteger(e.steps) && e.steps >= ESCALATION_STEPS.min && e.steps <= ESCALATION_STEPS.max && (e.to === 'managers' || e.to.length > 0);
  return ok ? null : 'escalation_invalid';
}
/** `channel_reserved` when a reserved channel is on. */
export function validatePolicy(p: Pick<PolicyBody, 'channels'>): 'channel_reserved' | null {
  const c = p.channels as Record<string, unknown>;
  return c.ha_mobile === true || c.whatsapp === true || c.app === true ? 'channel_reserved' : null;
}
const ADDRESS_RE = /^[^\s@<>,;]+@[^\s@<>,;]+\.[^\s@<>,;]+$/;
/** "a@b.c" or "Name <a@b.c>". */
export function isValidAddress(a: string): boolean {
  const m = /<([^<>]*)>\s*$/.exec(a.trim());
  return ADDRESS_RE.test(m ? m[1].trim() : a.trim());
}
/** Splits a recipients field (commas, semicolons, spaces, new lines) into distinct trimmed addresses, in order. */
export const parseRecipients = (text: string): string[] => [...new Set(text.split(/[\s,;]+/).map((x) => x.trim()).filter(Boolean))];
const HOST_RE = /^(?=.{1,253}$)[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)*$/;
/** `email_invalid` for a bad host, port (1-65535), security, from address, recipient address, or no recipient at all; else null. */
export function validateEmailBody(b: EmailBody): 'email_invalid' | null {
  const ok = HOST_RE.test(b.host.trim()) && Number.isInteger(b.port) && b.port >= 1 && b.port <= 65535 && ['starttls', 'tls', 'none'].includes(b.security)
    && isValidAddress(b.from) && b.recipients.length > 0 && b.recipients.every(isValidAddress);
  return ok ? null : 'email_invalid';
}
/** "owner@example.net" -> "o***@example.net" (what the delivery log shows). */
export const maskAddress = (a: string): string => a.replace(/^([^@])[^@]*@/, '$1***@');
export const EMAIL_TEST_DETAIL_LABEL: Record<string, string> = {
  dns: 'שם השרת לא נמצא', connect: 'החיבור נדחה', tls: 'כשל בהצפנה', auth: 'שם משתמש או סיסמה שגויים', refused: 'השרת דחה את ההודעה', timeout: 'השרת לא ענה בזמן',
};
/** The test button's result in place: "נשלח מייל בדיקה" or "החיבור נדחה (connect)". */
export const emailTestText = (r: EmailTestResult): string => (r.ok ? 'נשלח מייל בדיקה' : `${EMAIL_TEST_DETAIL_LABEL[r.detail] ?? 'הבדיקה נכשלה'} (${r.detail})`);

// ------------------------------------------------------------------------------------------------ scope-aware visibility (CR §7)

/** The viewer as the visibility rules see it: `can(permission, areaId)` is true when the user holds the permission at that area (installation-wide
 * grants answer true for every area, a floor-scoped grant for the areas of that floor); `areaId` null asks for the installation scope. */
export interface Viewer {
  user_id: string;
  can(permission: string, areaId: string | null): boolean;
}
/** The permission that makes a subject visible (CR §7 table). `null`: ownership, not a permission (bulk jobs: the initiator; sessions: the account's
 * user). Schedules and automations: the owner of record is only known to the server, so the helper falls back to the view permission. */
export const VISIBILITY_PERMISSION: Record<SubjectKind, string | null> = {
  camera: 'events.read', entity: 'devices.read', area: 'devices.read', alarm_panel: 'alarm.view', door: 'access.read', schedule: 'schedule.view', automation: 'schedule.view',
  bulk_job: null, system: 'system.configure', session: null,
};
/** Whether a row may be shown to this viewer NOW (the server re-checks at every read; this mirrors it for a permission change that arrives before the
 * next fetch). Owner-only kinds (bulk_job, session) are trusted: the server only returns the caller's own rows - except an account lockout, which
 * `system.configure` holders see too. */
export function canSeeNotification(n: Pick<Notification, 'subject' | 'source'>, v: Viewer): boolean {
  const perm = VISIBILITY_PERMISSION[n.subject.kind];
  if (perm === null) return true;
  return v.can(perm, n.subject.area_id);
}
export const filterVisible = <T extends Pick<Notification, 'subject' | 'source'>>(rows: readonly T[], v: Viewer): T[] => rows.filter((n) => canSeeNotification(n, v));
/** The permission a recipient needs to acknowledge a row (CR §8.2): `events.ack` for camera / rule rows, `alarm.view` for alarm and safety rows, none for
 * personal rows (the recipient itself); kinds §8.2 does not list follow their visibility permission. The server's `can_ack` is authoritative. */
export function ackPermission(n: Pick<Notification, 'subject' | 'source' | 'category'>): string | null {
  if (n.subject.kind === 'bulk_job' || n.subject.kind === 'session') return null;
  if (n.category === 'safety' || n.subject.kind === 'alarm_panel') return 'alarm.view';
  if (n.subject.kind === 'camera' || n.source === 'rule.alert') return 'events.ack';
  return VISIBILITY_PERMISSION[n.subject.kind];
}
export const canAckFor = (n: Pick<Notification, 'subject' | 'source' | 'category' | 'state'>, v: Viewer): boolean => {
  if (n.state !== 'open') return false;
  const perm = ackPermission(n);
  return perm === null || v.can(perm, n.subject.area_id);
};

// ------------------------------------------------------------------------------------------------ the adapter (§2)

/** One implementation per transport: HTTP (the real backend) or the in-memory mock. Same shapes, same errors. `read`, `readAll`, `snooze` and `ack`
 * answer the updated row when the server sends one, else null (apply `applyRead` / `applySnooze` / `applyAck` and refetch the summary). */
export interface NotifyAdapter {
  // every signed-in user
  list(q?: InboxQuery): Promise<InboxPage>;
  summary(): Promise<NotifySummary>;
  read(id: string): Promise<Notification | null>;
  readAll(): Promise<void>;
  snooze(id: string, choice: SnoozeChoice): Promise<Notification | null>;
  /** 403 `ack_not_allowed` unless the row's `can_ack`. */
  ack(id: string): Promise<Notification | null>;
  /** An <img src> for the row's snapshot (same origin, session cookie); null when the row has none. Fetched only inside Arx. */
  snapshotUrl(id: string): string | null;
  /** A test push to the caller's own devices (3/min). */
  test(): Promise<{ sent: number }>;
  deliveries(notificationId?: string): Promise<Delivery[]>;
  /** The push action endpoint (no session): the one-time token authorises exactly `ack` or `snooze` on one row. */
  action(token: string, action: 'ack' | 'snooze'): Promise<void>;
  /** Runs AFTER the in-app confirmation: the existing door release with the notification as its origin. Never called by a notification surface itself. */
  openDoor(notificationId: string, doorId: string): Promise<void>;
  // notify.manage
  settings(): Promise<NotifySettings>;
  saveSettings(body: SettingsBody, baseRevision: number): Promise<NotifySettings>;
  policies(): Promise<NotifyPolicy[]>;
  savePolicy(source: string, body: PolicyBody, baseRevision: number): Promise<NotifyPolicy>;
  saveEmail(body: EmailBody): Promise<EmailSettings>;
  testEmail(): Promise<EmailTestResult>;
  adminDeliveries(q?: DeliveryQuery): Promise<Delivery[]>;
  stats(): Promise<NotifyStats>;
}

const enc = encodeURIComponent;
const qs = (q: Record<string, string | number | undefined>) => {
  const p = new URLSearchParams();
  for (const [k, v] of Object.entries(q)) if (v !== undefined && v !== '') p.set(k, String(v));
  const s = p.toString();
  return s ? `?${s}` : '';
};
/** Accepts `[...]` or `{ [key]: [...] }`. */
const rows = <T>(r: unknown, key: string): T[] => (Array.isArray(r) ? (r as T[]) : (((r as Record<string, unknown> | null)?.[key] as T[] | undefined) ?? []));
/** The updated row when the reply is one, else null. */
const rowOrNull = (r: unknown): Notification | null => (r && typeof r === 'object' && typeof (r as Notification).id === 'string' && 'state' in (r as object) ? (r as Notification) : null);
async function call<T>(ctx: ErrorContext, fn: () => Promise<T>): Promise<T> {
  try { return await fn(); } catch (err) { throw mapNotifyError(err, ctx); }
}
const DEFAULT_PAGE = 50;
const commandEnvelope = () => ({ client_request_id: commandId(), expires_at: new Date(Date.now() + 15_000).toISOString().replace(/\.\d{3}Z$/, 'Z') });

export const httpNotify: NotifyAdapter = {
  list: (q = {}) => call('user', async () => {
    const limit = q.limit ?? DEFAULT_PAGE;
    const list = rows<Notification>(await get<unknown>(`notifications${qs({ state: q.state, category: q.category, severity_min: q.severity_min, before: q.before, limit })}`), 'notifications');
    return { notifications: list, next_before: list.length >= limit ? list[list.length - 1].last_at : null };
  }),
  summary: () => call('user', () => get<NotifySummary>('notifications/summary')),
  read: (id) => call('item', async () => rowOrNull(await post<unknown>(`notifications/${enc(id)}/read`))),
  readAll: () => call('user', async () => { await post('notifications/read-all'); }),
  snooze: (id, minutes) => call('item', async () => rowOrNull(await post<unknown>(`notifications/${enc(id)}/snooze`, { minutes }))),
  ack: (id) => call('ack', async () => rowOrNull(await post<unknown>(`notifications/${enc(id)}/ack`))),
  snapshotUrl: (id) => apiUrl(`notifications/${enc(id)}/snapshot`),
  test: () => call('user', () => post<{ sent: number }>('notifications/test')),
  deliveries: (id) => call('user', async () => rows<Delivery>(await get<unknown>(`notifications/deliveries${qs({ notification_id: id })}`), 'deliveries')),
  action: (t, a) => call('action', async () => { await post('notifications/action', { t, a }); }),
  // the existing WisKey release route (routers/access_control.py): `confirmed` is sent only after the in-app confirmation; `origin` names the notification
  openDoor: (notificationId, doorId) => call('user', async () => { await post(`intercom/stations/${enc(doorId)}/release`, { confirmed: true, origin: `notification:${notificationId}`, ...commandEnvelope() }); }),
  settings: () => call('settings', () => get<NotifySettings>('notify/settings')),
  saveSettings: (body, base) => call('settings', () => api<NotifySettings>('notify/settings', { method: 'PUT', body: JSON.stringify({ ...body, base_revision: base }), headers: { 'If-Match': String(base) } })),
  policies: () => call('policy', async () => rows<NotifyPolicy>(await get<unknown>('notify/policies'), 'policies')),
  savePolicy: (source, body, base) => call('policy', () => api<NotifyPolicy>(`notify/policies/${enc(source)}`, { method: 'PUT', body: JSON.stringify({ ...body, base_revision: base }), headers: { 'If-Match': String(base) } })),
  saveEmail: (body) => call('email', () => put<EmailSettings>('notify/email', body)),
  testEmail: () => call('email_test', () => post<EmailTestResult>('notify/email/test')),
  adminDeliveries: (q = {}) => call('admin', async () => rows<Delivery>(await get<unknown>(`notify/deliveries${qs({ status: q.status, channel: q.channel, since: q.since, limit: q.limit })}`), 'deliveries')),
  stats: () => call('admin', () => get<NotifyStats>('notify/stats')),
};

/** The mock behind a dynamic import: the two modules never import each other statically (the mock reuses this file's helpers). Same selector as the
 * media clients (`isApi() ? http : mock`). */
const mockAdapter = (): Promise<NotifyAdapter> => import('./notifications-mock').then((m) => m.notifyMock());
function lazyMock(): NotifyAdapter {
  const m = (): Promise<NotifyAdapter> => mockAdapter();
  return {
    list: async (q) => (await m()).list(q), summary: async () => (await m()).summary(), read: async (id) => (await m()).read(id), readAll: async () => (await m()).readAll(),
    snooze: async (id, c) => (await m()).snooze(id, c), ack: async (id) => (await m()).ack(id),
    // the one synchronous method: the mock's snapshot is a data URI built from the id (no store needed)
    snapshotUrl: (id) => `data:image/svg+xml;utf8,${enc(`<svg xmlns="http://www.w3.org/2000/svg" width="320" height="180"><rect width="320" height="180" fill="#cfd8e3"/><text x="160" y="95" text-anchor="middle" font-size="14" fill="#5a6b7d">${id}</text></svg>`)}`,
    test: async () => (await m()).test(), deliveries: async (id) => (await m()).deliveries(id), action: async (t, a) => (await m()).action(t, a),
    openDoor: async (n, d) => (await m()).openDoor(n, d), settings: async () => (await m()).settings(), saveSettings: async (b, r) => (await m()).saveSettings(b, r),
    policies: async () => (await m()).policies(), savePolicy: async (s, b, r) => (await m()).savePolicy(s, b, r), saveEmail: async (b) => (await m()).saveEmail(b),
    testEmail: async () => (await m()).testEmail(), adminDeliveries: async (q) => (await m()).adminDeliveries(q), stats: async () => (await m()).stats(),
  };
}
let lazy: NotifyAdapter | null = null;
/** The adapter in force: HTTP with a backend, the mock otherwise. */
export const notify = (): NotifyAdapter => (isApi() ? httpNotify : (lazy ??= lazyMock()));
