/**
 * CR-014 schedules ("תזמונים"): the typed client of the schedules API. The binding contract is
 * docs/architecture/SCHEDULER_API.md - section numbers below (§) refer to it. The backend is the authority for every
 * permission, class, allow-list and validation rule; the helpers here only format, compute geometry for the grids and
 * approximate next runs for demo mode / an unsaved draft's local preview.
 *
 * Without a backend (static preview, design review) every call is answered by the in-memory demo store in
 * ./schedules-mock.ts, so the screens and their specs run unchanged; mutations work there too.
 *
 * Owned by the coordinator (contract). The implementation agents do not edit this file; a needed change is a contract
 * change (SCHEDULER_API.md §12.6).
 */
import { apiUrl, get, post, put, patch } from './client';
import { invalidateSettings } from './prefs';
import { commandId } from './request-id';
import { isApi } from './session';
import { demoStore } from './schedules-mock';

// ------------------------------------------------------------------------------------------------ vocabulary (§2)

/** The component's weekday tokens (V-SRC); only `daily` is verified in real data (P0-1). */
export type DayToken = 'sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'daily' | 'workday' | 'weekend';
export type DayId = 'sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat';
export type DaysKind = 'days' | 'daily' | 'workday' | 'weekend' | 'mixed';
export type RepeatType = 'repeat' | 'pause' | 'single';
/** The schedule switch's state (V-LIVE on/off; the others V-SRC). */
export type ScheduleState = 'on' | 'off' | 'triggered' | 'completed' | 'unavailable' | 'unknown';
/** Arx's server-side class of an action entity (§5.1). */
export type ScheduleClass = 'light' | 'switch' | 'cover' | 'climate' | 'fan' | 'alarm' | 'lock' | 'door';
export type MatchType = 'is' | 'not' | 'above' | 'below';
export type ConditionType = 'and' | 'or';
export type ConditionPreset = 'only_holy_days' | 'not_holy_days';
export type ScheduleSource = 'arx' | 'external';
export type RunResult = 'pending' | 'confirmed' | 'not_confirmed' | 'skipped' | 'unknown';

export const DAY_ORDER: DayId[] = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'];
export const DAY_SHORT: Record<DayId, string> = { sun: 'א׳', mon: 'ב׳', tue: 'ג׳', wed: 'ד׳', thu: 'ה׳', fri: 'ו׳', sat: 'ש׳' };
export const DAY_LONG: Record<DayId, string> = { sun: 'ראשון', mon: 'שני', tue: 'שלישי', wed: 'רביעי', thu: 'חמישי', fri: 'שישי', sat: 'שבת' };
export const ALL_CLASSES: ScheduleClass[] = ['light', 'switch', 'cover', 'climate', 'fan', 'alarm', 'lock', 'door'];
export const SENSITIVE_CLASSES: ScheduleClass[] = ['alarm', 'lock', 'door'];
export const CLASS_LABEL: Record<ScheduleClass, string> = {
  light: 'תאורה',
  switch: 'מתגים',
  cover: 'תריסים',
  climate: 'מיזוג',
  fan: 'מאווררים',
  alarm: 'אזעקה',
  lock: 'מנעולים',
  door: 'דלתות ושערים',
};
export const STATE_LABEL: Record<ScheduleState, string> = {
  on: 'פעיל',
  off: 'מושבת',
  triggered: 'מתבצע עכשיו',
  completed: 'הסתיים',
  unavailable: 'אין הרצות קרובות',
  unknown: 'לא ידוע',
};
export const REPEAT_LABEL: Record<RepeatType, string> = { repeat: 'חוזר', pause: 'פעם אחת ואז מושהה (נשמר)', single: 'פעם אחת ואז נמחק' };
export const RESULT_LABEL: Record<RunResult, string> = { pending: 'ממתין לאישור', confirmed: 'אושר', not_confirmed: 'לא אושר', skipped: 'דולג', unknown: 'לא ידוע' };
export const MATCH_LABEL: Record<MatchType, string> = { is: 'שווה ל', not: 'שונה מ', above: 'מעל', below: 'מתחת' };
export const PRESET_LABEL: Record<ConditionPreset, string> = { only_holy_days: 'רק בשבת ובחג', not_holy_days: 'לא בשבת ובחג' };

// ------------------------------------------------------------------------------------------------ read model (§2.1)

export type TimeSpec =
  | { kind: 'fixed'; time: string; raw: string }
  | { kind: 'sun'; event: 'sunrise' | 'sunset'; offset_min: number; raw: string };

export interface ScheduleAction {
  service: string;
  entity_id: string | null;
  data: Record<string, unknown>;
  supported: boolean;
  class: ScheduleClass | null;
  sensitive: boolean;
  lowering: boolean;
}

export type UnsupportedCode =
  | 'action_without_entity'
  | 'action_not_allowed'
  | 'argument_not_allowed'
  | 'contains_code'
  | 'alarm_managed_control'
  | 'conditions_differ'
  | 'unknown_fields';

export interface Problem<C extends string = string> {
  code: C;
  message: string;
  path?: string;
}

export interface ScheduleSlot {
  index: number;
  start: TimeSpec;
  stop: TimeSpec | null;
  actions: ScheduleAction[];
  supported: boolean;
  unsupported: Problem<UnsupportedCode>[];
}

export interface ConditionView {
  entity_id: string;
  name: string;
  attribute: string;
  match_type: MatchType;
  value: string | number;
  /** The caller may read the entity (§4.3); `state` is null otherwise. */
  readable: boolean;
  state: string | null;
  available: boolean | null;
  /** Outside the caller's read scope: must be sent back unchanged (§4.4). */
  locked: boolean;
}

export interface ScheduleConditions {
  items: ConditionView[];
  type: ConditionType | null;
  track: boolean;
  /** False when slots carry different conditions (content then read-only, `conditions_differ`). */
  uniform: boolean;
  summary: string | null;
  preset: ConditionPreset | null;
}

export interface ScheduleEntity {
  entity_id: string;
  name: string;
  domain: string;
  role: 'action';
  area_id: string | null;
  area_name: string | null;
  floor_id: string | null;
  floor_name: string | null;
  class: ScheduleClass | null;
  sensitive: boolean;
  available: boolean;
}

export interface UpcomingRun {
  at: string;
  slot_index: number;
  summary?: string;
}

export interface NextRun extends UpcomingRun {
  source: 'component' | 'computed';
  /** The schedule has conditions: the run happens only if they hold then - show "בתנאי", never a promise (§6.5). */
  conditional: boolean;
}

export interface LastRun {
  at: string;
  slot_index: number | null;
  result: RunResult;
}

export interface ScheduleCan {
  edit: boolean;
  toggle: boolean;
  run: boolean;
  delete: boolean;
  copy: boolean;
}

export type ReadOnlyCode =
  | 'no_manage_permission'
  | 'entity_not_controllable'
  | 'grant_required'
  | 'sensitive_permission_required'
  | 'class_disabled'
  | 'unsupported_content'
  | 'feature_disabled'
  | 'component_unavailable'
  | 'ha_unavailable'
  | 'bridge_unavailable';

export interface ReadOnlyReason {
  code: ReadOnlyCode;
  message: string;
  entity_id?: string;
}

export interface PersonRef {
  user_id?: string;
  username: string;
  display_name: string;
}

export interface Schedule {
  id: string;
  /** Opaque (V-LIVE): never derive it from the name. */
  entity_id: string | null;
  name: string | null;
  display_name: string;
  enabled: boolean;
  state: ScheduleState;
  days: { tokens: DayToken[]; kind: DaysKind; days: DayId[] | null };
  start_date: string | null;
  end_date: string | null;
  repeat: RepeatType;
  slots: ScheduleSlot[];
  conditions: ScheduleConditions;
  entities: ScheduleEntity[];
  tags: string[];
  folder_id: string | null;
  order: number | null;
  pinned: boolean;
  next_run: NextRun | null;
  upcoming: UpcomingRun[];
  last_run: LastRun | null;
  sensitive: boolean;
  sensitive_classes: ScheduleClass[];
  lowering: boolean;
  source: ScheduleSource;
  owner: PersonRef | null;
  created_at: string | null;
  updated_at: string | null;
  revision: string;
  can: ScheduleCan;
  read_only: { reasons: ReadOnlyReason[] } | null;
  warnings: Problem[];
  /** Detail route only: the component's item, verbatim. */
  raw?: Record<string, unknown>;
}

// ------------------------------------------------------------------------------------------------ write model (§2.2)

export interface DraftAction {
  service: string;
  entity_id: string | null;
  data: Record<string, unknown>;
}

export interface DraftSlot {
  /** Stored form: "HH:MM:SS", "sunrise+HH:MM:SS", "sunset+HH:MM:SS". */
  start: string;
  stop: string | null;
  actions: DraftAction[];
}

export interface DraftCondition {
  entity_id: string;
  attribute: string;
  match_type: MatchType;
  value: string | number;
}

export interface DraftConditions {
  items: DraftCondition[];
  type: ConditionType | null;
  track: boolean;
}

export interface ScheduleDraft {
  name: string | null;
  weekdays: DayToken[];
  start_date: string | null;
  end_date: string | null;
  repeat: RepeatType;
  tags: string[];
  conditions: DraftConditions;
  slots: DraftSlot[];
}

// ------------------------------------------------------------------------------------------------ status (§3.1)

export type Availability = 'ok' | 'component_missing' | 'ha_unavailable' | 'not_configured' | 'feature_disabled' | 'error';
export type WriteBlock = 'feature_disabled' | 'component_missing' | 'ha_unavailable' | 'bridge_missing' | 'bridge_unpaired' | 'bridge_too_old';

export interface ShabbatSensor {
  entity_id: string;
  name: string;
  state: string | null;
  available: boolean;
}

export interface ScheduleSettingsView {
  snap_minutes: 5 | 15 | 30;
  default_repeat: RepeatType;
  classes: ScheduleClass[];
  shabbat_sensor: ShabbatSensor | null;
}

export interface ScheduleStatus {
  available: Availability;
  feature_enabled: boolean;
  stale: boolean;
  last_sync_at: string | null;
  writable: boolean;
  write_block: WriteBlock | null;
  capabilities: { tags: boolean; negative_sun_offset: boolean };
  can: { view: boolean; manage: boolean; sensitive: boolean; configure: boolean };
  counts: { visible: number; enabled: number; attention: number; hidden: number | null };
  settings: ScheduleSettingsView;
  admin?: { component: 'found' | 'missing' | 'unknown'; component_version: string | null; bridge_version: string | null; bridge_required: string; ha_version: string | null };
}

// ------------------------------------------------------------------------------------------------ list (§3.2)

export interface ScheduleQuery {
  q?: string;
  floor?: string;
  area?: string;
  entity?: string;
  condition?: string;
  has_conditions?: boolean;
  preset?: ConditionPreset;
  day?: DayId;
  state?: 'enabled' | 'disabled' | 'triggered' | 'completed' | 'unavailable';
  tag?: string;
  folder?: string;
  source?: ScheduleSource;
  sensitive?: boolean;
  editable?: boolean;
  sort?: 'next_run' | 'name' | 'order' | 'updated';
  limit?: number;
  offset?: number;
}

export interface ScheduleList {
  items: Schedule[];
  total: number;
  offset: number;
  limit: number;
  status: { available: Availability; stale: boolean; last_sync_at: string | null };
}

// ------------------------------------------------------------------------------------------------ catalogue (§3.4, §3.4b)

export interface ArgSpec {
  name: string;
  type: 'int' | 'float' | 'enum' | 'str' | 'bool';
  min?: number;
  max?: number;
  choices?: string[];
  required: boolean;
}

export interface CatalogAction {
  service: string;
  label: string;
  lowering: boolean;
  args: ArgSpec[];
}

export interface CatalogEntity {
  entity_id: string;
  name: string;
  domain: string;
  class: ScheduleClass;
  sensitive: boolean;
  area_id: string | null;
  area_name: string | null;
  floor_id: string | null;
  floor_name: string | null;
  available: boolean;
  selectable: boolean;
  reason: Problem | null;
  attributes: Record<string, unknown>;
  actions: CatalogAction[];
}

export interface ConditionCandidate {
  entity_id: string;
  name: string;
  domain: 'binary_sensor' | 'sensor' | 'sun' | 'input_boolean';
  device_class: string | null;
  state: string | null;
  unit: string | null;
  numeric: boolean;
  suggested_shabbat: boolean;
}

// ------------------------------------------------------------------------------------------------ preview and writes (§3.5-§3.14)

export interface PreviewResult {
  valid: boolean;
  errors: Problem[];
  warnings: Problem[];
  upcoming: UpcomingRun[];
  conditional: boolean;
  sensitive: boolean;
  lowering: boolean;
  requires: { sensitive_permission: boolean; confirm_lowering: boolean; alarm_code: boolean };
}

export interface WriteOptions {
  confirm_lowering?: boolean;
  alarm_code?: string | null;
  client_request_id?: string;
}

export type CreateResult = { schedule: Schedule; op_id: string } | { status: 'unknown'; op_id: string; message: string };

export interface TrashItem {
  trash_id: string;
  schedule_id: string;
  name: string | null;
  deleted_at: string;
  expires_at: string;
  deleted_by: PersonRef | null;
  entities: ScheduleEntity[];
  sensitive: boolean;
  can_restore: boolean;
}

export interface RunItem {
  id: string;
  schedule_id: string;
  schedule_name: string;
  slot_index: number | null;
  started_at: string;
  settled_at: string | null;
  result: RunResult;
  via: 'component' | 'run_now';
  sensitive: boolean;
  detail: { entities: { entity_id: string; expected: string | null; observed: string | null; result: RunResult }[] };
}

export type ReviewIssue =
  | 'owner_lost_rights'
  | 'owner_inactive'
  | 'no_owner_sensitive'
  | 'contains_code'
  | 'unsupported_content'
  | 'class_disabled'
  | 'sensitive_condition_unavailable'
  | 'alarm_may_need_code'
  | 'requested_disabled';

export const REVIEW_LABEL: Record<ReviewIssue, string> = {
  owner_lost_rights: 'מי שיצר או ערך אחרון כבר אינו מורשה לכל ההתקנים',
  owner_inactive: 'מי שיצר או ערך אחרון אינו פעיל',
  no_owner_sensitive: 'תזמון רגיש שנוצר מחוץ למערכת',
  contains_code: 'התזמון שומר קוד',
  unsupported_content: 'תוכן שהמערכת אינה מציגה במלואו',
  class_disabled: 'סוג התקן שכובה בהגדרות',
  sensitive_condition_unavailable: 'פעולה רגישה תלויה בחיישן לא זמין',
  alarm_may_need_code: 'לוח האזעקה עשוי לדרוש קוד',
  requested_disabled: 'התזמון התבקש כבוי אך לא נכבה - יש לכבות אותו ידנית',
};

export interface ReviewItem {
  schedule: Schedule;
  issues: ReviewIssue[];
}

export interface BulkResult {
  results: ({ id: string; ok: true; changed: boolean } | { id: string; ok: false; code: string; message: string })[];
}

export interface Organisation {
  folders: { id: string; name: string; position: number }[];
  items: { schedule_id: string; folder_id: string | null; order: number | null; pinned: boolean }[];
}

/** Error codes of §3.20 (the server's `user_message` is shown as is). */
export type ScheduleErrorCode =
  | 'forbidden'
  | 'entity_not_controllable'
  | 'sensitive_permission_required'
  | 'grant_required'
  | 'condition_locked'
  | 'condition_not_readable'
  | 'remote_control_disabled'
  | 'remote_disarm_disabled'
  | 'wrong_code'
  | 'schedule_not_found'
  | 'trash_not_found'
  | 'schedule_changed'
  | 'confirmation_required'
  | 'lowering_confirmation_required'
  | 'code_required'
  | 'feature_disabled'
  | 'validation'
  | 'action_not_allowed'
  | 'class_not_allowed'
  | 'alarm_managed_control'
  | 'alarm_code_needed'
  | 'lock_code_needed'
  | 'code_not_allowed'
  | 'arm_mode_not_supported'
  | 'condition_domain_not_allowed'
  | 'slots_overlap'
  | 'slot_required'
  | 'split_not_possible'
  | 'unsupported_content'
  | 'tags_not_supported'
  | 'rate_limited'
  | 'run_too_soon'
  | 'code_locked'
  | 'scheduler_refused'
  | 'split_incomplete'
  | 'scheduler_unavailable'
  | 'ha_unavailable'
  | 'bridge_not_paired'
  | 'bridge_too_old'
  | 'scheduler_timeout';

// ------------------------------------------------------------------------------------------------ calls

function qs(query: object): string {
  const p = new URLSearchParams();
  for (const [k, v] of Object.entries(query)) if (v !== undefined && v !== null && v !== '') p.set(k, String(v));
  const s = p.toString();
  return s ? `?${s}` : '';
}

const rid = (o?: WriteOptions) => o?.client_request_id ?? commandId();
const enc = encodeURIComponent;

export function getScheduleStatus(): Promise<ScheduleStatus> {
  return isApi() ? get<ScheduleStatus>('schedules/status') : demoStore().status();
}

export function listSchedules(query: ScheduleQuery = {}): Promise<ScheduleList> {
  return isApi() ? get<ScheduleList>(`schedules${qs(query)}`) : demoStore().list(query);
}

export function getSchedule(id: string): Promise<Schedule> {
  return isApi() ? get<Schedule>(`schedules/${enc(id)}`) : demoStore().get(id);
}

export function getScheduleCatalog(query: { q?: string; floor?: string; area?: string; class?: ScheduleClass } = {}): Promise<{ entities: CatalogEntity[]; truncated: boolean }> {
  return isApi() ? get(`schedules/catalog${qs(query)}`) : demoStore().catalog(query);
}

export function getConditionCandidates(query: { q?: string; domain?: ConditionCandidate['domain'] } = {}): Promise<{ entities: ConditionCandidate[]; truncated: boolean }> {
  return isApi() ? get(`schedules/condition-candidates${qs(query)}`) : demoStore().conditionCandidates(query);
}

export function previewSchedule(draft: ScheduleDraft, scheduleId: string | null = null, count = 5): Promise<PreviewResult> {
  return isApi() ? post<PreviewResult>('schedules/preview', { draft, schedule_id: scheduleId, count }) : demoStore().preview(draft, scheduleId, count);
}

export function createSchedule(draft: ScheduleDraft, opts: WriteOptions & { enabled?: boolean } = {}): Promise<CreateResult> {
  const body = { draft, enabled: opts.enabled ?? true, client_request_id: rid(opts), confirm_lowering: opts.confirm_lowering ?? false, alarm_code: opts.alarm_code ?? null };
  return isApi() ? post<CreateResult>('schedules', body) : demoStore().create(draft, body.enabled, body.confirm_lowering);
}

export function updateSchedule(id: string, draft: ScheduleDraft, baseRevision: string, opts: WriteOptions = {}): Promise<{ schedule: Schedule; op_id: string }> {
  const body = { draft, base_revision: baseRevision, client_request_id: rid(opts), confirm_lowering: opts.confirm_lowering ?? false, alarm_code: opts.alarm_code ?? null };
  return isApi() ? put(`schedules/${enc(id)}`, body) : demoStore().update(id, draft, baseRevision, body.confirm_lowering);
}

export function setScheduleEnabled(id: string, enabled: boolean, opts: WriteOptions = {}): Promise<{ schedule: Schedule; changed: boolean }> {
  const body = { client_request_id: rid(opts), confirm_lowering: opts.confirm_lowering ?? false, alarm_code: opts.alarm_code ?? null };
  return isApi() ? post(`schedules/${enc(id)}/${enabled ? 'enable' : 'disable'}`, body) : demoStore().setEnabled(id, enabled, body.confirm_lowering);
}

export function runSchedule(id: string, slotIndex: number | null, opts: WriteOptions & { skip_conditions?: boolean; confirm?: boolean } = {}): Promise<{ run_id: string; note: string }> {
  const body = { slot_index: slotIndex, skip_conditions: opts.skip_conditions ?? false, confirm: opts.confirm ?? false, client_request_id: rid(opts), alarm_code: opts.alarm_code ?? null };
  return isApi() ? post(`schedules/${enc(id)}/run`, body) : demoStore().run(id, slotIndex, body.confirm);
}

export function splitSchedule(id: string, baseRevision: string, days: DayId[], name: string | null = null, opts: WriteOptions = {}): Promise<{ original: Schedule; created: Schedule }> {
  const body = { base_revision: baseRevision, days, name, confirm: true, client_request_id: rid(opts) };
  return isApi() ? post(`schedules/${enc(id)}/split`, body) : demoStore().split(id, baseRevision, days, name);
}

export function deleteSchedule(id: string, baseRevision: string, opts: WriteOptions = {}): Promise<{ trash_id: string; expires_at: string }> {
  const body = { base_revision: baseRevision, confirm: true, client_request_id: rid(opts) };
  return isApi() ? post(`schedules/${enc(id)}/delete`, body) : demoStore().remove(id, baseRevision);
}

export function copySchedule(id: string, name: string, opts: WriteOptions = {}): Promise<{ schedule: Schedule }> {
  return isApi() ? post(`schedules/${enc(id)}/copy`, { name, client_request_id: rid(opts) }) : demoStore().copy(id, name);
}

export function listTrash(): Promise<{ items: TrashItem[] }> {
  return isApi() ? get('schedules/trash') : demoStore().trash();
}

export function restoreFromTrash(trashId: string, opts: WriteOptions = {}): Promise<{ schedule: Schedule }> {
  const body = { client_request_id: rid(opts), confirm_lowering: opts.confirm_lowering ?? false, alarm_code: opts.alarm_code ?? null };
  return isApi() ? post(`schedules/trash/${enc(trashId)}/restore`, body) : demoStore().restore(trashId);
}

export function purgeTrash(trashId: string): Promise<{ ok: true }> {
  return isApi() ? post(`schedules/trash/${enc(trashId)}/purge`, { confirm: true }) : demoStore().purge(trashId);
}

export function bulkSchedules(op: 'enable' | 'disable', ids: string[], opts: WriteOptions = {}): Promise<BulkResult> {
  const body = { op, ids, confirm: true, client_request_id: rid(opts) };
  return isApi() ? post<BulkResult>('schedules/bulk', body) : demoStore().bulk(op, ids);
}

export function getOrganisation(): Promise<Organisation> {
  return isApi() ? get<Organisation>('schedules/organisation') : demoStore().organisation();
}

export function putOrganisation(body: Organisation): Promise<Organisation> {
  return isApi() ? put<Organisation>('schedules/organisation', body) : demoStore().setOrganisation(body);
}

export function listScheduleRuns(query: { schedule_id?: string; since?: string; result?: RunResult; limit?: number } = {}): Promise<{ items: RunItem[] }> {
  return isApi() ? get(`schedules/runs${qs(query)}`) : demoStore().runs(query);
}

export function getScheduleReview(): Promise<{ items: ReviewItem[] }> {
  return isApi() ? get('schedules/review') : demoStore().review();
}

export function listScheduleTags(): Promise<{ tags: { name: string; count: number }[] }> {
  return isApi() ? get('schedules/tags') : demoStore().tags();
}

/**
 * Live refresh: calls `onChange` when the server says schedules changed (`schedules_changed`, no ids) or a schedule
 * switch's state changed (`switch.schedule_*`, e.g. `triggered`), throttled to one call per second. It opens its own
 * `/ha/ws` socket (the frames are filtered by the caller's scope on the server). No-op in demo mode; returns a stop
 * function.
 */
export function subscribeSchedules(onChange: () => void, onSocket?: (connected: boolean) => void): () => void {
  if (!isApi()) return () => undefined;
  let ws: WebSocket | null = null;
  let stopped = false;
  let delay = 2000;
  let pending = 0;
  const fire = () => {
    if (pending) return;
    pending = window.setTimeout(() => {
      pending = 0;
      if (!stopped) onChange();
    }, 1000);
  };
  const url = (() => {
    const u = new URL(apiUrl('ha/ws'));
    u.protocol = u.protocol === 'https:' ? 'wss:' : 'ws:';
    return u.toString();
  })();
  const open = () => {
    if (stopped) return;
    try {
      ws = new WebSocket(url);
    } catch {
      return;
    }
    ws.onopen = () => {
      delay = 2000;
      onSocket?.(true);
    };
    ws.onmessage = (m) => {
      try {
        const env = JSON.parse(m.data as string) as { type: string; payload?: { entity?: { entity_id?: string } } };
        if (env.type === 'schedules_changed') fire();
        else if (env.type === 'entity_state_changed' && String(env.payload?.entity?.entity_id ?? '').startsWith('switch.schedule_')) fire();
      } catch {
        /* ignore malformed frames */
      }
    };
    ws.onclose = (ev) => {
      onSocket?.(false);
      if (!stopped && ev.code !== 4403 && ev.code !== 4401) {
        window.setTimeout(open, delay);
        delay = Math.min(30000, delay * 2);
      }
    };
  };
  open();
  return () => {
    stopped = true;
    if (pending) window.clearTimeout(pending);
    ws?.close();
  };
}

// ------------------------------------------------------------------------------------------------ settings (§10.1)

export interface ScheduleSettings {
  enabled: boolean;
  classes: ScheduleClass[];
  snapMinutes: 5 | 15 | 30;
  defaultRepeat: RepeatType;
  runsRetentionDays: number;
  shabbatSensor: string;
}

export const SCHEDULE_SETTINGS_DEFAULT: ScheduleSettings = { enabled: true, classes: [...ALL_CLASSES], snapMinutes: 15, defaultRepeat: 'repeat', runsRetentionDays: 90, shabbatSensor: '' };

export function scheduleSettingsOf(s: Record<string, unknown> | null | undefined): ScheduleSettings {
  const d = SCHEDULE_SETTINGS_DEFAULT;
  let classes: unknown = s?.['schedules.classes'];
  if (typeof classes === 'string') {
    try {
      classes = JSON.parse(classes);
    } catch {
      classes = null;
    }
  }
  const snap = Number(s?.['schedules.snap_minutes']);
  const repeat = s?.['schedules.default_repeat'];
  const days = Number(s?.['schedules.runs_retention_days']);
  const sensor = s?.['schedules.shabbat_sensor'];
  return {
    enabled: String(s?.['schedules.enabled'] ?? 'true') !== 'false',
    classes: Array.isArray(classes) ? ALL_CLASSES.filter((c) => (classes as unknown[]).includes(c)) : d.classes,
    snapMinutes: snap === 5 || snap === 30 ? snap : 15,
    defaultRepeat: repeat === 'pause' || repeat === 'single' ? repeat : 'repeat',
    runsRetentionDays: Number.isFinite(days) && days >= 7 && days <= 365 ? days : d.runsRetentionDays,
    shabbatSensor: typeof sensor === 'string' ? sensor : '',
  };
}

/** The PATCH /settings body for what differs (system.configure; audited by the server). */
export function scheduleSettingsPatch(from: ScheduleSettings, to: ScheduleSettings): Record<string, unknown> {
  const body: Record<string, unknown> = {};
  if (from.enabled !== to.enabled) body['schedules.enabled'] = String(to.enabled);
  if (JSON.stringify(from.classes) !== JSON.stringify(to.classes)) body['schedules.classes'] = to.classes;
  if (from.snapMinutes !== to.snapMinutes) body['schedules.snap_minutes'] = String(to.snapMinutes);
  if (from.defaultRepeat !== to.defaultRepeat) body['schedules.default_repeat'] = to.defaultRepeat;
  if (from.runsRetentionDays !== to.runsRetentionDays) body['schedules.runs_retention_days'] = to.runsRetentionDays;
  if (from.shabbatSensor !== to.shabbatSensor) body['schedules.shabbat_sensor'] = to.shabbatSensor;
  return body;
}

export async function saveScheduleSettings(from: ScheduleSettings, to: ScheduleSettings): Promise<ScheduleSettings> {
  const body = scheduleSettingsPatch(from, to);
  if (!Object.keys(body).length) return to;
  if (!isApi()) return demoStore().saveSettings(to);
  const r = await patch<{ settings: Record<string, unknown> }>('settings', body);
  invalidateSettings();
  return scheduleSettingsOf(r.settings);
}

// ------------------------------------------------------------------------------------------------ time helpers

export interface SunTimes {
  /** Minutes from local midnight, today. */
  sunrise: number;
  sunset: number;
}

/** Fallback when no sun entity is known (the UI marks sun times as "משוער" anyway). */
export const SUN_FALLBACK: SunTimes = { sunrise: 6 * 60 + 30, sunset: 18 * 60 + 15 };

const FIXED_RE = /^(\d{1,2}):(\d{2})(?::(\d{2}))?$/;
const SUN_RE = /^(sunrise|sunset)([+-])(\d{1,2}):(\d{2})(?::(\d{2}))?$/;

function pad(n: number): string {
  return String(n).padStart(2, '0');
}

/** A component time string ("07:30:00", "07:30", "sunset+00:30:00") as a TimeSpec; null when not recognised. */
export function parseTime(raw: string | null | undefined): TimeSpec | null {
  const s = (raw ?? '').trim();
  let m = FIXED_RE.exec(s);
  if (m) {
    const h = Number(m[1]);
    const min = Number(m[2]);
    if (h > 23 || min > 59) return null;
    return { kind: 'fixed', time: `${pad(h)}:${pad(min)}`, raw: s };
  }
  m = SUN_RE.exec(s);
  if (m) {
    const off = Number(m[3]) * 60 + Number(m[4]);
    return { kind: 'sun', event: m[1] as 'sunrise' | 'sunset', offset_min: m[2] === '-' ? -off : off, raw: s };
  }
  return null;
}

/** The stored form Arx writes (§2.2): "HH:MM:SS" or "sunset+HH:MM:SS". */
export function timeToRaw(spec: { kind: 'fixed'; time: string } | { kind: 'sun'; event: 'sunrise' | 'sunset'; offset_min: number }): string {
  if (spec.kind === 'fixed') return `${spec.time.slice(0, 5)}:00`;
  const a = Math.abs(spec.offset_min);
  return `${spec.event}${spec.offset_min < 0 ? '-' : '+'}${pad(Math.floor(a / 60))}:${pad(a % 60)}:00`;
}

export function minutesToRaw(minutes: number): string {
  const m = ((Math.round(minutes) % 1440) + 1440) % 1440;
  return `${pad(Math.floor(m / 60))}:${pad(m % 60)}:00`;
}

/** Hebrew display: "07:30", "שקיעה +00:30", "זריחה −00:15", "שקיעה". */
export function formatTime(spec: TimeSpec | null): string {
  if (!spec) return '—';
  if (spec.kind === 'fixed') return spec.time;
  const word = spec.event === 'sunrise' ? 'זריחה' : 'שקיעה';
  if (!spec.offset_min) return word;
  const a = Math.abs(spec.offset_min);
  return `${word} ${spec.offset_min < 0 ? '−' : '+'}${pad(Math.floor(a / 60))}:${pad(a % 60)}`;
}

/** Minutes from midnight (sun times from today's values, clamped like the component to 00:00..23:59). */
export function timeMinutes(spec: TimeSpec, sun: SunTimes | null = null): number {
  if (spec.kind === 'fixed') {
    const [h, m] = spec.time.split(':').map(Number);
    return h * 60 + m;
  }
  const base = (sun ?? SUN_FALLBACK)[spec.event];
  return Math.min(1439, Math.max(0, base + spec.offset_min));
}

/** A slot's span in minutes: a point action occupies one minute; a stop of 00:00 (or before the start) = end of day. */
export function slotSpan(slot: { start: TimeSpec; stop: TimeSpec | null }, sun: SunTimes | null = null): { start: number; end: number } {
  const start = timeMinutes(slot.start, sun);
  if (!slot.stop) return { start, end: Math.min(1440, start + 1) };
  let end = timeMinutes(slot.stop, sun);
  if (end <= start) end = 1440;
  return { start, end };
}

export function draftSlotSpan(slot: DraftSlot, sun: SunTimes | null = null): { start: number; end: number } | null {
  const start = parseTime(slot.start);
  if (!start) return null;
  const stop = slot.stop ? parseTime(slot.stop) : null;
  if (slot.stop && !stop) return null;
  return slotSpan({ start, stop }, sun);
}

/** Index pairs of overlapping slots (half-open intervals; contiguous slots do not overlap). */
export function findOverlaps(slots: DraftSlot[], sun: SunTimes | null = null): [number, number][] {
  const spans = slots.map((s) => draftSlotSpan(s, sun));
  const out: [number, number][] = [];
  for (let i = 0; i < spans.length; i++)
    for (let j = i + 1; j < spans.length; j++) {
      const a = spans[i];
      const b = spans[j];
      if (a && b && a.start < b.end && b.start < a.end) out.push([i, j]);
    }
  return out;
}

/** Snap minutes to the editor's grid (5 / 15 / 30), within the day. */
export function snapMinutes(minutes: number, step: number): number {
  return Math.min(1440, Math.max(0, Math.round(minutes / step) * step));
}

// ------------------------------------------------------------------------------------------------ day helpers

export function resolveDays(tokens: DayToken[]): DayId[] | null {
  if (tokens.includes('daily')) return [...DAY_ORDER];
  if (tokens.includes('workday') || tokens.includes('weekend')) return null;
  return DAY_ORDER.filter((d) => tokens.includes(d));
}

export function daysKind(tokens: DayToken[]): DaysKind {
  if (tokens.includes('daily')) return 'daily';
  const named = tokens.filter((t) => (DAY_ORDER as string[]).includes(t));
  if (tokens.includes('workday')) return named.length ? 'mixed' : 'workday';
  if (tokens.includes('weekend')) return named.length ? 'mixed' : 'weekend';
  return 'days';
}

/** "כל יום", "א׳–ה׳", "א׳, ג׳, ה׳", "ימי עבודה". */
export function daysLabel(tokens: DayToken[]): string {
  if (tokens.includes('daily')) return 'כל יום';
  const parts: string[] = [];
  if (tokens.includes('workday')) parts.push('ימי עבודה');
  if (tokens.includes('weekend')) parts.push('סוף שבוע');
  const days = DAY_ORDER.filter((d) => tokens.includes(d));
  if (days.length === 7) return 'כל יום';
  if (days.length >= 3) {
    const idx = days.map((d) => DAY_ORDER.indexOf(d));
    const contiguous = idx.every((v, i) => i === 0 || v === idx[i - 1] + 1);
    if (contiguous) parts.unshift(`${DAY_SHORT[days[0]]}–${DAY_SHORT[days[days.length - 1]]}`);
    else parts.unshift(days.map((d) => DAY_SHORT[d]).join(', '));
  } else if (days.length) parts.unshift(days.map((d) => DAY_SHORT[d]).join(', '));
  return parts.join(' · ') || '—';
}

// ------------------------------------------------------------------------------------------------ action helpers

const SERVICE_LABEL: Record<string, string> = {
  'light.turn_on': 'הדלקה',
  'light.turn_off': 'כיבוי',
  'switch.turn_on': 'הדלקה',
  'switch.turn_off': 'כיבוי',
  'fan.turn_on': 'הפעלה',
  'fan.turn_off': 'כיבוי',
  'fan.set_percentage': 'עוצמת מאוורר',
  'cover.open_cover': 'פתיחה',
  'cover.close_cover': 'סגירה',
  'cover.stop_cover': 'עצירה',
  'cover.set_cover_position': 'מיקום',
  'cover.set_cover_tilt_position': 'מיקום הטיה',
  'climate.set_hvac_mode': 'מצב פעולה',
  'climate.set_temperature': 'טמפרטורת יעד',
  'climate.set_fan_mode': 'מצב מאוורר',
  'climate.set_preset_mode': 'מצב מוגדר מראש',
  'climate.turn_off': 'כיבוי מיזוג',
  'alarm_control_panel.alarm_arm_home': 'דריכה בבית',
  'alarm_control_panel.alarm_arm_away': 'דריכה מלאה',
  'alarm_control_panel.alarm_arm_night': 'דריכת לילה',
  'alarm_control_panel.alarm_arm_vacation': 'דריכת חופשה',
  'alarm_control_panel.alarm_arm_custom_bypass': 'דריכה עם עקיפה',
  'alarm_control_panel.alarm_disarm': 'נטרול',
  'lock.lock': 'נעילה',
  'lock.unlock': 'פתיחת נעילה',
  'button.press': 'לחיצה',
};

const HVAC_LABEL: Record<string, string> = { cool: 'קירור', heat: 'חימום', heat_cool: 'אוטומטי', auto: 'אוטומטי', dry: 'ייבוש', fan_only: 'מאוורר', off: 'כבוי' };

/** "הדלקה · בהירות 20%", "קירור 25°", "מיקום 10%", "סקריפט (לא נתמך)". */
export function actionLabel(a: { service: string; data?: Record<string, unknown> }): string {
  const d = a.data ?? {};
  if (a.service.startsWith('script.')) return 'סקריפט';
  if (a.service === 'climate.set_temperature') {
    const mode = typeof d.hvac_mode === 'string' ? HVAC_LABEL[d.hvac_mode] ?? d.hvac_mode : 'יעד';
    return `${mode} ${d.temperature ?? ''}°`.trim();
  }
  if (a.service === 'climate.set_hvac_mode' && typeof d.hvac_mode === 'string') return HVAC_LABEL[d.hvac_mode] ?? d.hvac_mode;
  const base = SERVICE_LABEL[a.service] ?? a.service;
  if (typeof d.brightness_pct === 'number') return `${base} · בהירות ${d.brightness_pct}%`;
  if (typeof d.brightness === 'number') return `${base} · בהירות ${Math.round((d.brightness / 255) * 100)}%`;
  if (typeof d.position === 'number') return `${base} ${d.position}%`;
  if (typeof d.tilt_position === 'number') return `${base} ${d.tilt_position}%`;
  if (typeof d.percentage === 'number') return `${base} ${d.percentage}%`;
  if (typeof d.fan_mode === 'string') return `${base}: ${d.fan_mode}`;
  if (typeof d.preset_mode === 'string') return `${base}: ${d.preset_mode}`;
  return base;
}

const ON_TO_OFF: Record<string, string> = {
  'light.turn_on': 'light.turn_off',
  'switch.turn_on': 'switch.turn_off',
  'fan.turn_on': 'fan.turn_off',
  'fan.set_percentage': 'fan.turn_off',
  'climate.set_temperature': 'climate.turn_off',
  'climate.set_hvac_mode': 'climate.turn_off',
  'climate.set_fan_mode': 'climate.turn_off',
  'climate.set_preset_mode': 'climate.turn_off',
};

/** The off counterpart of an "on"-type action (for "כיבוי בסיום", §2.7); null when there is none. */
export function offActionFor(a: DraftAction): DraftAction | null {
  if (a.service === 'climate.set_hvac_mode' && a.data.hvac_mode === 'off') return null;
  const off = ON_TO_OFF[a.service];
  return off && a.entity_id ? { service: off, entity_id: a.entity_id, data: {} } : null;
}

/** "כיבוי בסיום": the companion slot starting at `slot.stop` (or `at`), with the off actions; null when nothing to add. */
export function makeOffSlot(slot: DraftSlot, at?: string): DraftSlot | null {
  const actions = slot.actions.map(offActionFor).filter((x): x is DraftAction => !!x);
  const start = slot.stop ?? at ?? null;
  if (!actions.length || !start || start === '00:00:00') return null;
  return { start, stop: null, actions };
}

/** Index of the slot that is `index`'s "כיבוי בסיום" companion (starts at its stop with the off counterparts). */
export function pairedOffSlot(slots: DraftSlot[], index: number): number | null {
  const s = slots[index];
  if (!s?.stop) return null;
  const wanted = s.actions.map(offActionFor).filter((x): x is DraftAction => !!x);
  if (!wanted.length) return null;
  const j = slots.findIndex(
    (o, k) => k !== index && o.start === s.stop && wanted.every((w) => o.actions.some((a) => a.service === w.service && a.entity_id === w.entity_id)),
  );
  return j >= 0 ? j : null;
}

// ------------------------------------------------------------------------------------------------ conditions (§2.4, §12.5)

export const NO_CONDITIONS: DraftConditions = { items: [], type: null, track: false };

/** The preset blocks (V-LIVE form: attribute "state", match "is"). */
export function presetConditions(preset: ConditionPreset, sensor: string): DraftConditions {
  return { items: [{ entity_id: sensor, attribute: 'state', match_type: 'is', value: preset === 'only_holy_days' ? 'on' : 'off' }], type: 'or', track: false };
}

export function detectPreset(block: { items: { entity_id: string; attribute: string; match_type: MatchType; value: string | number }[] }, sensor: string | null | undefined): ConditionPreset | null {
  if (!sensor || block.items.length !== 1) return null;
  const c = block.items[0];
  if (c.entity_id !== sensor || c.attribute !== 'state' || c.match_type !== 'is') return null;
  return c.value === 'on' ? 'only_holy_days' : c.value === 'off' ? 'not_holy_days' : null;
}

/** "רק בשבת ובחג", "בתנאי: איסור מלאכה פעיל", "בתנאי: טמפרטורה מעל 28 או נוכחות פעיל"; null without conditions. */
export function conditionSummary(block: DraftConditions | ScheduleConditions, names: Record<string, string>, sensor: string | null | undefined): string | null {
  if (!block.items.length) return null;
  const preset = detectPreset(block, sensor);
  if (preset) return PRESET_LABEL[preset];
  const parts = block.items.map((c) => {
    const name = names[c.entity_id] ?? ('name' in c ? (c as ConditionView).name : c.entity_id);
    if (c.attribute === 'state' && (c.value === 'on' || c.value === 'off')) return `${name} ${(c.match_type === 'is') === (c.value === 'on') ? 'פעיל' : 'כבוי'}`;
    return `${name} ${MATCH_LABEL[c.match_type]} ${c.value}`;
  });
  return `בתנאי: ${parts.join(block.type === 'and' ? ' וגם ' : ' או ')}`;
}

// ------------------------------------------------------------------------------------------------ drafts

export function emptyDraft(repeat: RepeatType = 'repeat'): ScheduleDraft {
  return { name: '', weekdays: ['daily'], start_date: null, end_date: null, repeat, tags: [], conditions: { ...NO_CONDITIONS, items: [] }, slots: [] };
}

/** The editable draft of a read schedule: stored strings kept as they are (untouched slots re-send byte-identical). */
export function draftFromSchedule(s: Schedule): ScheduleDraft {
  return {
    name: s.name,
    weekdays: [...s.days.tokens],
    start_date: s.start_date,
    end_date: s.end_date,
    repeat: s.repeat,
    tags: [...s.tags],
    conditions: {
      items: s.conditions.items.map((c) => ({ entity_id: c.entity_id, attribute: c.attribute, match_type: c.match_type, value: c.value })),
      type: s.conditions.type,
      track: s.conditions.track,
    },
    slots: s.slots.map((sl) => ({ start: sl.start.raw, stop: sl.stop ? sl.stop.raw : null, actions: sl.actions.map((a) => ({ service: a.service, entity_id: a.entity_id, data: { ...a.data } })) })),
  };
}

/**
 * Next occurrence of each slot, soonest first - the shape of the component's `timestamps` / `next_entries` (V-LIVE).
 * Local (browser) time, today's sun times for every day; `workday` / `weekend` are not computed (empty result). For demo
 * mode and a draft's instant feedback only - the server's preview is the answer in API mode.
 */
export function approximateUpcoming(
  draft: Pick<ScheduleDraft, 'weekdays' | 'start_date' | 'end_date' | 'slots'>,
  now: Date = new Date(),
  sun: SunTimes | null = null,
): UpcomingRun[] {
  const days = resolveDays(draft.weekdays);
  if (!days || !days.length) return [];
  const from = draft.start_date ? new Date(`${draft.start_date}T00:00:00`) : null;
  const to = draft.end_date ? new Date(`${draft.end_date}T23:59:59`) : null;
  const out: UpcomingRun[] = [];
  draft.slots.forEach((slot, index) => {
    const spec = parseTime(slot.start);
    if (!spec) return;
    const minutes = timeMinutes(spec, sun);
    for (let k = 0; k < 400; k++) {
      const d = new Date(now.getFullYear(), now.getMonth(), now.getDate() + k, Math.floor(minutes / 60), minutes % 60, 0, 0);
      if (d.getTime() <= now.getTime()) continue;
      if (!days.includes(DAY_ORDER[d.getDay()])) continue;
      if (from && d < from) continue;
      if (to && d > to) break;
      out.push({ at: d.toISOString(), slot_index: index });
      break;
    }
  });
  return out.sort((a, b) => a.at.localeCompare(b.at));
}

/** "היום 18:00", "מחר 07:30", "יום ה׳ 06:00", "12.10 06:00" (local time). */
export function whenLabel(iso: string | null | undefined, now: Date = new Date()): string {
  if (!iso) return '—';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '—';
  const hm = `${pad(d.getHours())}:${pad(d.getMinutes())}`;
  const day0 = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
  const diff = Math.round((new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime() - day0) / 86_400_000);
  if (diff === 0) return `היום ${hm}`;
  if (diff === 1) return `מחר ${hm}`;
  if (diff > 1 && diff < 7) return `יום ${DAY_SHORT[DAY_ORDER[d.getDay()]]} ${hm}`;
  return `${d.getDate()}.${d.getMonth() + 1} ${hm}`;
}

/** The next-run text of a schedule: "היום 18:00" or "היום 18:00 · בתנאי" (§6.5: conditions are never a promise). */
export function nextRunLabel(s: Pick<Schedule, 'next_run' | 'enabled'>, now: Date = new Date()): string {
  if (!s.enabled) return 'מושבת';
  if (!s.next_run) return 'אין הרצה קרובה';
  return s.next_run.conditional ? `${whenLabel(s.next_run.at, now)} · בתנאי` : whenLabel(s.next_run.at, now);
}

export const newClientRequestId = commandId;
