"""Write contracts/API_INVENTORY.md from the running application's route table (T008 contract lock).

The table is generated, never hand-edited: every FastAPI route under /api/v1 with its methods, the router it
comes from and the first line of its docstring. Run after adding or changing endpoints:

    python scripts/api_inventory.py
"""
from __future__ import annotations

import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "smplwise_vms" / "backend"
OUT = ROOT / "contracts" / "API_INVENTORY.md"
sys.path.insert(0, str(BACKEND))


def main() -> None:
    from smplwise import __version__
    from smplwise.config import Settings
    from smplwise.main import create_app

    tmp = Path(tempfile.mkdtemp())
    settings = Settings(
        data_dir=tmp / "data",
        www_dir=None,
        in_addon=False,
        trusted_proxies=("172.30.32.2",),
        dev_user="joni",
        bootstrap_admin_username="joni",
        nvr_host=None,
        nvr_http_port=80,
        nvr_user=None,
        nvr_password=None,
        go2rtc_url=None,
        log_level="warning",
    )
    app = create_app(settings)
    # FastAPI keeps included routers lazily; the OpenAPI document is the reliable route table for HTTP routes
    spec = app.openapi()
    rows: list[tuple[str, str, str, str]] = []
    for path, ops in spec.get("paths", {}).items():
        if not path.startswith("/api/v1"):
            continue
        for method, op in ops.items():
            if method.upper() in ("HEAD", "OPTIONS"):
                continue
            tag = (op.get("tags") or ["?"])[0]
            doc = (op.get("description") or "").strip().splitlines()
            rows.append((path, method.upper(), tag, (doc[0] if doc else "").replace("|", "\\|")))

    # websocket routes are not part of OpenAPI: walk the included routers
    def walk(routes, prefix=""):
        for r in routes:
            inner = getattr(r, "routes", None)
            if inner is not None and getattr(r, "endpoint", None) is None:
                yield from walk(inner, prefix + (getattr(r, "prefix", "") or ""))
            elif type(r).__name__ in ("APIWebSocketRoute", "WebSocketRoute"):
                yield prefix + getattr(r, "path", ""), r

    for path, r in walk(app.routes):
        if path.startswith("/api/v1"):
            doc = ((getattr(r.endpoint, "__doc__", None) or "").strip().splitlines() or [""])[0]
            rows.append((path, "WS", "websocket", doc.replace("|", "\\|")))
    rows.sort(key=lambda x: (x[2], x[0], x[1]))
    lines = [
        "# API inventory (generated)",
        "",
        f"Version {__version__} · {len(rows)} routes under `/api/v1` · generated by `scripts/api_inventory.py`. Every route sits behind the",
        "Ingress identity and the scoped role check named in its handler; errors use the `ApiError` model",
        "(`code`, `user_message`, `details`, `retryable`). Ids are 16-hex strings; instants are UTC ISO-8601 with `Z`.",
        "",
        "| Router | Method | Path | Purpose |",
        "|---|---|---|---|",
    ]
    for path, methods, module, doc in rows:
        lines.append(f"| {module} | {methods} | `{path}` | {doc} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{len(rows)} routes -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
